#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from amogh.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "amogh.y"

	void yyerror(char* s);
	int yylex();
	#include "stdio.h"
	#include "stdlib.h"
	#include "ctype.h"
	#include "string.h"
	#include "stdarg.h"
	void ins();
	void insV();
	int flag=0;


	#define ANSI_COLOR_RED		"\x1b[31m"
	#define ANSI_COLOR_GREEN	"\x1b[32m"
	#define ANSI_COLOR_CYAN		"\x1b[36m"
	#define ANSI_COLOR_RESET	"\x1b[0m"
	extern char curid[20];
	extern char curtype[20];
	extern char curval[20];
	extern int currnest;
	void deletedata (int );
	int checkscope(char*);
	int check_id_is_func(char *);
	void insertST(char*, char*);
	void insertSTnest(char*, int);
	void insertSTparamscount(char*, int);
	int getSTparamscount(char*);
	int check_duplicate(char*);
	int check_declaration(char*, char *);
	int check_params(char*);
	int duplicate(char *s);
	int checkarray(char*);
	char currfunctype[100];
	char currfunc[100];
	char currfunccall[100];
	void insertSTF(char*);
	char gettype(char*,int);
	char getfirst(char*);
	extern int params_count;
	int call_params_count;

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	IF	258
#define	INT	259
#define	CHAR	260
#define	FLOAT	261
#define	DOUBLE	262
#define	LONG	263
#define	SHORT	264
#define	SIGNED	265
#define	UNSIGNED	266
#define	STRUCT	267
#define	RETURN	268
#define	MAIN	269
#define	VOID	270
#define	WHILE	271
#define	FOR	272
#define	DO	273
#define	BREAK	274
#define	PRINTF	275
#define	CONTINUE	276
#define	ENDIF	277
#define	identifier	278
#define	array_identifier	279
#define	integer_constant	280
#define	string_constant	281
#define	float_constant	282
#define	character_constant	283
#define	ELSE	284
#define	leftshift_assignment_operator	285
#define	rightshift_assignment_operator	286
#define	XOR_assignment_operator	287
#define	OR_assignment_operator	288
#define	AND_assignment_operator	289
#define	modulo_assignment_operator	290
#define	multiplication_assignment_operator	291
#define	division_assignment_operator	292
#define	addition_assignment_operator	293
#define	subtraction_assignment_operator	294
#define	assignment_operator	295
#define	OR_operator	296
#define	AND_operator	297
#define	pipe_operator	298
#define	caret_operator	299
#define	amp_operator	300
#define	equality_operator	301
#define	inequality_operator	302
#define	lessthan_assignment_operator	303
#define	lessthan_operator	304
#define	greaterthan_assignment_operator	305
#define	greaterthan_operator	306
#define	leftshift_operator	307
#define	rightshift_operator	308
#define	add_operator	309
#define	subtract_operator	310
#define	multiplication_operator	311
#define	division_operator	312
#define	modulo_operator	313
#define	SIZEOF	314
#define	tilde_operator	315
#define	exclamation_operator	316
#define	increment_operator	317
#define	decrement_operator	318


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int IF;
static const int INT;
static const int CHAR;
static const int FLOAT;
static const int DOUBLE;
static const int LONG;
static const int SHORT;
static const int SIGNED;
static const int UNSIGNED;
static const int STRUCT;
static const int RETURN;
static const int MAIN;
static const int VOID;
static const int WHILE;
static const int FOR;
static const int DO;
static const int BREAK;
static const int PRINTF;
static const int CONTINUE;
static const int ENDIF;
static const int identifier;
static const int array_identifier;
static const int integer_constant;
static const int string_constant;
static const int float_constant;
static const int character_constant;
static const int ELSE;
static const int leftshift_assignment_operator;
static const int rightshift_assignment_operator;
static const int XOR_assignment_operator;
static const int OR_assignment_operator;
static const int AND_assignment_operator;
static const int modulo_assignment_operator;
static const int multiplication_assignment_operator;
static const int division_assignment_operator;
static const int addition_assignment_operator;
static const int subtraction_assignment_operator;
static const int assignment_operator;
static const int OR_operator;
static const int AND_operator;
static const int pipe_operator;
static const int caret_operator;
static const int amp_operator;
static const int equality_operator;
static const int inequality_operator;
static const int lessthan_assignment_operator;
static const int lessthan_operator;
static const int greaterthan_assignment_operator;
static const int greaterthan_operator;
static const int leftshift_operator;
static const int rightshift_operator;
static const int add_operator;
static const int subtract_operator;
static const int multiplication_operator;
static const int division_operator;
static const int modulo_operator;
static const int SIZEOF;
static const int tilde_operator;
static const int exclamation_operator;
static const int increment_operator;
static const int decrement_operator;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,IF=258
	,INT=259
	,CHAR=260
	,FLOAT=261
	,DOUBLE=262
	,LONG=263
	,SHORT=264
	,SIGNED=265
	,UNSIGNED=266
	,STRUCT=267
	,RETURN=268
	,MAIN=269
	,VOID=270
	,WHILE=271
	,FOR=272
	,DO=273
	,BREAK=274
	,PRINTF=275
	,CONTINUE=276
	,ENDIF=277
	,identifier=278
	,array_identifier=279
	,integer_constant=280
	,string_constant=281
	,float_constant=282
	,character_constant=283
	,ELSE=284
	,leftshift_assignment_operator=285
	,rightshift_assignment_operator=286
	,XOR_assignment_operator=287
	,OR_assignment_operator=288
	,AND_assignment_operator=289
	,modulo_assignment_operator=290
	,multiplication_assignment_operator=291
	,division_assignment_operator=292
	,addition_assignment_operator=293
	,subtraction_assignment_operator=294
	,assignment_operator=295
	,OR_operator=296
	,AND_operator=297
	,pipe_operator=298
	,caret_operator=299
	,amp_operator=300
	,equality_operator=301
	,inequality_operator=302
	,lessthan_assignment_operator=303
	,lessthan_operator=304
	,greaterthan_assignment_operator=305
	,greaterthan_operator=306
	,leftshift_operator=307
	,rightshift_operator=308
	,add_operator=309
	,subtract_operator=310
	,multiplication_operator=311
	,division_operator=312
	,modulo_operator=313
	,SIZEOF=314
	,tilde_operator=315
	,exclamation_operator=316
	,increment_operator=317
	,decrement_operator=318


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::IF=258;
const int YY_parse_CLASS::INT=259;
const int YY_parse_CLASS::CHAR=260;
const int YY_parse_CLASS::FLOAT=261;
const int YY_parse_CLASS::DOUBLE=262;
const int YY_parse_CLASS::LONG=263;
const int YY_parse_CLASS::SHORT=264;
const int YY_parse_CLASS::SIGNED=265;
const int YY_parse_CLASS::UNSIGNED=266;
const int YY_parse_CLASS::STRUCT=267;
const int YY_parse_CLASS::RETURN=268;
const int YY_parse_CLASS::MAIN=269;
const int YY_parse_CLASS::VOID=270;
const int YY_parse_CLASS::WHILE=271;
const int YY_parse_CLASS::FOR=272;
const int YY_parse_CLASS::DO=273;
const int YY_parse_CLASS::BREAK=274;
const int YY_parse_CLASS::PRINTF=275;
const int YY_parse_CLASS::CONTINUE=276;
const int YY_parse_CLASS::ENDIF=277;
const int YY_parse_CLASS::identifier=278;
const int YY_parse_CLASS::array_identifier=279;
const int YY_parse_CLASS::integer_constant=280;
const int YY_parse_CLASS::string_constant=281;
const int YY_parse_CLASS::float_constant=282;
const int YY_parse_CLASS::character_constant=283;
const int YY_parse_CLASS::ELSE=284;
const int YY_parse_CLASS::leftshift_assignment_operator=285;
const int YY_parse_CLASS::rightshift_assignment_operator=286;
const int YY_parse_CLASS::XOR_assignment_operator=287;
const int YY_parse_CLASS::OR_assignment_operator=288;
const int YY_parse_CLASS::AND_assignment_operator=289;
const int YY_parse_CLASS::modulo_assignment_operator=290;
const int YY_parse_CLASS::multiplication_assignment_operator=291;
const int YY_parse_CLASS::division_assignment_operator=292;
const int YY_parse_CLASS::addition_assignment_operator=293;
const int YY_parse_CLASS::subtraction_assignment_operator=294;
const int YY_parse_CLASS::assignment_operator=295;
const int YY_parse_CLASS::OR_operator=296;
const int YY_parse_CLASS::AND_operator=297;
const int YY_parse_CLASS::pipe_operator=298;
const int YY_parse_CLASS::caret_operator=299;
const int YY_parse_CLASS::amp_operator=300;
const int YY_parse_CLASS::equality_operator=301;
const int YY_parse_CLASS::inequality_operator=302;
const int YY_parse_CLASS::lessthan_assignment_operator=303;
const int YY_parse_CLASS::lessthan_operator=304;
const int YY_parse_CLASS::greaterthan_assignment_operator=305;
const int YY_parse_CLASS::greaterthan_operator=306;
const int YY_parse_CLASS::leftshift_operator=307;
const int YY_parse_CLASS::rightshift_operator=308;
const int YY_parse_CLASS::add_operator=309;
const int YY_parse_CLASS::subtract_operator=310;
const int YY_parse_CLASS::multiplication_operator=311;
const int YY_parse_CLASS::division_operator=312;
const int YY_parse_CLASS::modulo_operator=313;
const int YY_parse_CLASS::SIZEOF=314;
const int YY_parse_CLASS::tilde_operator=315;
const int YY_parse_CLASS::exclamation_operator=316;
const int YY_parse_CLASS::increment_operator=317;
const int YY_parse_CLASS::decrement_operator=318;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		290
#define	YYFLAG		-32768
#define	YYNTBASE	72

#define YYTRANSLATE(x) ((unsigned)(x) <= 318 ? yytranslate[x] : 155)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,    70,
    71,     2,     2,    65,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    64,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    66,     2,    67,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    68,     2,    69,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54,    55,
    56,    57,    58,    59,    60,    61,    62,    63
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     5,     7,     8,    10,    12,    16,    19,    22,
    23,    24,    28,    29,    33,    35,    37,    40,    41,    46,
    54,    56,    58,    60,    62,    65,    71,    77,    82,    86,
    89,    91,    93,    97,   100,   103,   105,   107,   108,   113,
   118,   123,   129,   133,   135,   141,   145,   147,   149,   153,
   155,   157,   159,   161,   163,   166,   169,   172,   175,   177,
   179,   182,   185,   186,   188,   191,   194,   195,   197,   198,
   200,   201,   204,   208,   212,   214,   215,   216,   220,   223,
   226,   227,   228,   232,   235,   236,   238,   240,   242,   244,
   246,   248,   250,   252,   254,   255,   260,   263,   264,   267,
   269,   270,   278,   281,   282,   283,   290,   291,   301,   302,
   311,   314,   318,   325,   329,   333,   334,   337,   340,   343,
   348,   353,   356,   359,   362,   365,   366,   369,   370,   374,
   378,   382,   386,   390,   394,   397,   400,   402,   406,   408,
   412,   414,   417,   419,   423,   425,   427,   429,   431,   433,
   435,   437,   441,   443,   445,   447,   451,   453,   455,   457,
   459,   461,   463,   465,   467,   471,   473,   475,   476,   482,
   484,   485,   486,   490,   491,   496,   497,   499,   501,   503
};

static const short yyrhs[] = {    73,
     0,    75,    74,     0,    73,     0,     0,    76,     0,   100,
     0,    95,    77,    64,     0,    79,    78,     0,    65,    77,
     0,     0,     0,    23,    80,    82,     0,     0,    24,    81,
    82,     0,    85,     0,    86,     0,    40,   134,     0,     0,
    24,    66,    84,    67,     0,    24,    66,    84,    67,    66,
    84,    67,     0,    25,     0,    23,     0,    83,     0,   134,
     0,    66,    89,     0,    66,    25,    67,    66,    87,     0,
    66,    23,    67,    66,    87,     0,    66,    67,    66,    87,
     0,    88,    67,    91,     0,    88,    67,     0,    25,     0,
    23,     0,    25,    67,    90,     0,    67,    90,     0,    67,
   128,     0,   128,     0,   129,     0,     0,    40,    68,    92,
    69,     0,    40,    68,    93,    69,     0,    40,    68,    94,
    69,     0,    68,   130,    69,    65,    92,     0,    68,   130,
    69,     0,    25,     0,    68,   131,    69,    65,    93,     0,
    68,   131,    69,     0,    25,     0,    27,     0,    26,    65,
    94,     0,    26,     0,     4,     0,     5,     0,     6,     0,
     7,     0,     8,    98,     0,     9,    99,     0,    11,    96,
     0,    10,    97,     0,    15,     0,     4,     0,     8,    98,
     0,     9,    99,     0,     0,     4,     0,     8,    98,     0,
     9,    99,     0,     0,     4,     0,     0,     4,     0,     0,
   101,   102,     0,    95,    23,    70,     0,   103,    71,   111,
     0,   104,     0,     0,     0,    95,   105,   106,     0,   108,
   107,     0,    65,   104,     0,     0,     0,    23,   109,   110,
     0,    66,    67,     0,     0,   115,     0,   112,     0,   116,
     0,   119,     0,   123,     0,   127,     0,   126,     0,    76,
     0,   124,     0,     0,   113,    68,   114,    69,     0,   111,
   114,     0,     0,   134,    64,     0,    64,     0,     0,     3,
    70,   135,    71,   117,   111,   118,     0,    29,   111,     0,
     0,     0,    16,    70,   135,    71,   120,   111,     0,     0,
    17,    70,   134,    64,   135,    64,   121,   134,    71,     0,
     0,    18,   111,    16,    70,   135,    71,   122,    64,     0,
    13,    64,     0,    13,   134,    64,     0,    20,    70,    26,
   125,    71,    64,     0,    65,    23,   125,     0,    65,    83,
   125,     0,     0,    21,    64,     0,    19,    64,     0,    40,
    26,     0,    40,    68,   130,    69,     0,    40,    68,   131,
    69,     0,    25,   132,     0,    27,   133,     0,    25,   133,
     0,    65,   130,     0,     0,    65,   131,     0,     0,   145,
    40,   134,     0,   145,    38,   134,     0,   145,    39,   134,
     0,   145,    36,   134,     0,   145,    37,   134,     0,   145,
    35,   134,     0,   145,    62,     0,   145,    63,     0,   135,
     0,   135,    41,   136,     0,   136,     0,   136,    42,   137,
     0,   137,     0,    61,   137,     0,   138,     0,   138,   139,
   140,     0,   140,     0,    50,     0,    48,     0,    51,     0,
    49,     0,    46,     0,    47,     0,   140,   141,   142,     0,
   142,     0,    54,     0,    55,     0,   142,   143,   144,     0,
   144,     0,    56,     0,    57,     0,    58,     0,   146,     0,
   145,     0,    23,     0,    83,     0,    70,   134,    71,     0,
   147,     0,   154,     0,     0,    23,    70,   148,   149,    71,
     0,   150,     0,     0,     0,   134,   151,   152,     0,     0,
    65,   134,   153,   152,     0,     0,    25,     0,    26,     0,
    27,     0,    28,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    87,    90,    93,    94,    97,    98,   101,   104,   107,   108,
   111,   112,   112,   112,   117,   118,   119,   120,   125,   126,
   129,   130,   131,   132,   135,   138,   139,   140,   144,   145,
   148,   149,   152,   153,   154,   157,   158,   159,   162,   163,
   164,   167,   168,   169,   172,   173,   174,   175,   178,   179,
   182,   182,   182,   182,   183,   184,   185,   186,   187,   190,
   190,   190,   190,   193,   193,   193,   193,   196,   196,   199,
   199,   202,   205,   208,   211,   211,   214,   214,   217,   220,
   221,   224,   224,   227,   228,   231,   232,   233,   234,   235,
   236,   237,   238,   239,   242,   242,   245,   246,   249,   250,
   253,   253,   256,   257,   260,   261,   261,   261,   262,   262,
   265,   266,   279,   282,   283,   284,   287,   290,   293,   296,
   297,   300,   303,   304,   307,   308,   311,   312,   315,   323,
   329,   335,   341,   347,   353,   354,   355,   359,   360,   363,
   364,   368,   369,   372,   373,   376,   376,   376,   377,   377,
   377,   380,   381,   384,   385,   388,   389,   392,   392,   392,
   395,   396,   399,   412,   420,   421,   422,   425,   430,   443,
   443,   446,   446,   449,   450,   450,   453,   454,   455,   456
};

static const char * const yytname[] = {   "$","error","$illegal.","IF","INT",
"CHAR","FLOAT","DOUBLE","LONG","SHORT","SIGNED","UNSIGNED","STRUCT","RETURN",
"MAIN","VOID","WHILE","FOR","DO","BREAK","PRINTF","CONTINUE","ENDIF","identifier",
"array_identifier","integer_constant","string_constant","float_constant","character_constant",
"ELSE","leftshift_assignment_operator","rightshift_assignment_operator","XOR_assignment_operator",
"OR_assignment_operator","AND_assignment_operator","modulo_assignment_operator",
"multiplication_assignment_operator","division_assignment_operator","addition_assignment_operator",
"subtraction_assignment_operator","assignment_operator","OR_operator","AND_operator",
"pipe_operator","caret_operator","amp_operator","equality_operator","inequality_operator",
"lessthan_assignment_operator","lessthan_operator","greaterthan_assignment_operator",
"greaterthan_operator","leftshift_operator","rightshift_operator","add_operator",
"subtract_operator","multiplication_operator","division_operator","modulo_operator",
"SIZEOF","tilde_operator","exclamation_operator","increment_operator","decrement_operator",
"';'","','","'['","']'","'{'","'}'","'('","')'","program","declaration_list",
"D","declaration","variable_declaration","variable_declaration_list","V","variable_declaration_identifier",
"@1","@2","vdi","array_random_access","array_random_access_breakup","identifier_array_type",
"identifier_twod_array_type","initialization_params_new","initialization_params_2d",
"initialization_params","initialization","initialization_2d","array_init_int_2d",
"array_init_float_2d","array_init_string_2d","type_specifier","unsigned_grammar",
"signed_grammar","long_grammar","short_grammar","function_declaration","function_declaration_type",
"function_declaration_param_statement","params","parameters_list","@3","parameters_identifier_list",
"parameters_identifier_list_breakup","param_identifier","@4","param_identifier_breakup",
"statement","compound_statement","@5","statment_list","expression_statment",
"conditional_statements","@6","conditional_statements_breakup","iterative_statements",
"@7","@8","@9","return_statement","printf_statement","printf_identifier_list",
"continue_statement","break_statement","string_initialization","array_initialization",
"array_int_declarations","array_float_declarations","array_int_declarations_breakup",
"array_float_declarations_breakup","expression","simple_expression","and_expression",
"unary_relation_expression","regular_expression","relational_operators","sum_expression",
"sum_operators","term","MULOP","factor","mutable","immutable","call","@10","arguments",
"arguments_list","@11","A","@12","constant",""
};
#endif

static const short yyr1[] = {     0,
    72,    73,    74,    74,    75,    75,    76,    77,    78,    78,
    80,    79,    81,    79,    82,    82,    82,    82,    83,    83,
    84,    84,    84,    84,    85,    86,    86,    86,    87,    87,
    88,    88,    89,    89,    89,    90,    90,    90,    91,    91,
    91,    92,    92,    92,    93,    93,    93,    93,    94,    94,
    95,    95,    95,    95,    95,    95,    95,    95,    95,    96,
    96,    96,    96,    97,    97,    97,    97,    98,    98,    99,
    99,   100,   101,   102,   103,   103,   105,   104,   106,   107,
   107,   109,   108,   110,   110,   111,   111,   111,   111,   111,
   111,   111,   111,   111,   113,   112,   114,   114,   115,   115,
   117,   116,   118,   118,   120,   119,   121,   119,   122,   119,
   123,   123,   124,   125,   125,   125,   126,   127,   128,   129,
   129,   130,   131,   131,   132,   132,   133,   133,   134,   134,
   134,   134,   134,   134,   134,   134,   134,   135,   135,   136,
   136,   137,   137,   138,   138,   139,   139,   139,   139,   139,
   139,   140,   140,   141,   141,   142,   142,   143,   143,   143,
   144,   144,   145,   145,   146,   146,   146,   148,   147,   149,
   149,   151,   150,   153,   152,   152,   154,   154,   154,   154
};

static const short yyr2[] = {     0,
     1,     2,     1,     0,     1,     1,     3,     2,     2,     0,
     0,     3,     0,     3,     1,     1,     2,     0,     4,     7,
     1,     1,     1,     1,     2,     5,     5,     4,     3,     2,
     1,     1,     3,     2,     2,     1,     1,     0,     4,     4,
     4,     5,     3,     1,     5,     3,     1,     1,     3,     1,
     1,     1,     1,     1,     2,     2,     2,     2,     1,     1,
     2,     2,     0,     1,     2,     2,     0,     1,     0,     1,
     0,     2,     3,     3,     1,     0,     0,     3,     2,     2,
     0,     0,     3,     2,     0,     1,     1,     1,     1,     1,
     1,     1,     1,     1,     0,     4,     2,     0,     2,     1,
     0,     7,     2,     0,     0,     6,     0,     9,     0,     8,
     2,     3,     6,     3,     3,     0,     2,     2,     2,     4,
     4,     2,     2,     2,     2,     0,     2,     0,     3,     3,
     3,     3,     3,     3,     2,     2,     1,     3,     1,     3,
     1,     2,     1,     3,     1,     1,     1,     1,     1,     1,
     1,     3,     1,     1,     1,     3,     1,     1,     1,     1,
     1,     1,     1,     1,     3,     1,     1,     0,     5,     1,
     0,     0,     3,     0,     4,     0,     1,     1,     1,     1
};

static const short yydefact[] = {     0,
    51,    52,    53,    54,    69,    71,    67,    63,    59,     1,
     4,     5,     0,     6,    76,    68,    55,    70,    56,    64,
    69,    71,    58,    60,    69,    71,    57,     3,     2,    11,
    13,     0,    10,    77,    72,     0,    75,    65,    66,    61,
    62,    73,    18,    18,     7,     0,     8,     0,    95,     0,
     0,    12,    15,    16,    14,    11,     9,    82,    78,    81,
     0,     0,     0,     0,    95,     0,     0,     0,   163,     0,
   177,   178,   179,   180,     0,   100,     0,    93,   164,     0,
    74,    87,     0,    86,    88,    89,    90,    94,    92,    91,
     0,   137,   139,   141,   143,   145,   153,   157,   162,   161,
   166,   167,    17,     0,     0,    38,    25,    85,     0,    79,
     0,   111,     0,     0,     0,     0,   118,     0,   117,   168,
     0,   142,   162,     0,    95,    99,     0,     0,   150,   151,
   147,   149,   146,   148,     0,   154,   155,     0,   158,   159,
   160,     0,     0,     0,     0,     0,     0,     0,   135,   136,
     0,    38,     0,     0,    34,    35,    37,     0,    83,    80,
     0,   112,     0,     0,     0,   116,   171,   163,   177,   164,
     0,    24,   165,    95,     0,   138,   140,   144,   152,   156,
   134,   132,   133,   130,   131,   129,     0,     0,    33,    36,
   119,     0,    32,    31,    28,     0,    84,   101,   105,     0,
     0,     0,     0,   172,     0,   170,    19,    97,    96,    27,
    26,   126,   128,     0,     0,    30,    95,    95,     0,     0,
   116,   116,     0,   176,   169,     0,     0,   122,   124,     0,
   123,   120,   121,     0,    29,   104,   106,   107,   109,   114,
   115,   113,     0,   173,     0,   125,   127,   128,     0,    95,
   102,     0,     0,   174,    20,    44,    50,    48,     0,     0,
     0,     0,   103,     0,   110,   176,     0,     0,     0,    39,
    40,    41,   108,   175,    49,    43,    46,     0,     0,    44,
     0,    42,    47,     0,    45,   126,     0,     0,     0,     0
};

static const short yydefgoto[] = {   288,
    10,    29,    11,    78,    32,    47,    33,    43,    44,    52,
    79,   171,    53,    54,   195,   196,   107,   155,   235,   260,
   261,   262,    80,    27,    23,    17,    19,    14,    15,    35,
    36,    37,    48,    59,   110,    60,   108,   159,   174,    82,
    83,   175,    84,    85,   217,   251,    86,   218,   252,   253,
    87,    88,   203,    89,    90,   156,   157,   246,   247,   228,
   229,    91,    92,    93,    94,    95,   135,    96,   138,    97,
   142,    98,    99,   100,   101,   167,   205,   206,   224,   244,
   266,   102
};

static const short yypact[] = {   226,
-32768,-32768,-32768,-32768,     6,    34,    83,   101,-32768,-32768,
   226,-32768,    88,-32768,   226,-32768,-32768,-32768,-32768,-32768,
     6,    34,-32768,-32768,     6,    34,-32768,-32768,-32768,     0,
-32768,    99,   -10,-32768,-32768,    76,-32768,-32768,-32768,-32768,
-32768,-32768,    17,    17,-32768,   144,-32768,   146,   201,    18,
   -17,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,   109,
   105,     5,   113,   120,   201,   127,   126,   128,   129,   132,
-32768,-32768,-32768,-32768,    18,-32768,    18,-32768,-32768,   144,
-32768,-32768,   133,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
   136,   156,   171,-32768,   131,    70,    58,-32768,   122,-32768,
-32768,-32768,-32768,   148,   172,    20,-32768,   157,   226,-32768,
    18,-32768,   174,    18,    18,   224,-32768,   216,-32768,-32768,
    95,-32768,-32768,   173,   125,-32768,    18,    18,-32768,-32768,
-32768,-32768,-32768,-32768,    -3,-32768,-32768,    -3,-32768,-32768,
-32768,    -3,    18,    18,    18,    18,    18,    18,-32768,-32768,
   177,    23,    -9,   114,-32768,-32768,-32768,   178,-32768,-32768,
   -15,-32768,     7,   182,   179,   183,    18,    15,   180,   184,
   185,-32768,-32768,   125,   181,   171,-32768,    70,    58,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,   114,   114,-32768,-32768,
-32768,    79,-32768,-32768,-32768,   186,-32768,-32768,-32768,    18,
    18,   149,   187,-32768,   188,-32768,   189,-32768,-32768,-32768,
-32768,   191,   192,   194,   195,   214,   201,   201,   -25,    10,
   183,   183,   196,   202,-32768,    95,    79,-32768,-32768,   139,
-32768,-32768,-32768,   193,-32768,   237,-32768,-32768,-32768,-32768,
-32768,-32768,    18,-32768,   203,-32768,-32768,   192,     9,   201,
-32768,    18,   204,-32768,-32768,-32768,   207,-32768,    79,   200,
   205,   206,-32768,   208,-32768,   202,   247,   209,   211,-32768,
-32768,-32768,-32768,-32768,-32768,   212,   217,   -16,    22,-32768,
   251,-32768,-32768,   139,-32768,   218,   251,   281,   284,-32768
};

static const short yypgoto[] = {-32768,
   274,-32768,-32768,    62,   240,-32768,-32768,-32768,-32768,   243,
  -118,    63,-32768,-32768,   -33,-32768,-32768,   138,-32768,    13,
    14,    21,     4,-32768,-32768,    51,    81,-32768,-32768,-32768,
-32768,   190,-32768,-32768,-32768,-32768,-32768,-32768,   -47,-32768,
-32768,   118,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,   -34,-32768,-32768,   142,-32768,  -179,  -185,-32768,
    82,   -50,  -100,   169,   -70,-32768,-32768,   162,-32768,   160,
-32768,   158,   -74,-32768,-32768,-32768,-32768,-32768,-32768,    35,
-32768,-32768
};


#define	YYLAST		301


static const short yytable[] = {   103,
   123,    81,   170,    13,   122,   104,   215,   105,   280,    16,
   161,   113,   214,   163,    13,   127,   191,   116,    34,    69,
    70,    71,    72,    73,    74,   127,   124,    69,    70,    71,
    72,    73,    74,   256,   257,   258,   123,    18,   238,   123,
    69,    70,    71,    72,    73,    74,   283,   127,   258,   106,
   127,   281,   123,   123,    46,   198,    50,   177,   192,   153,
   123,    12,   153,   123,   164,    75,    77,   123,   112,    42,
   172,    38,    12,   269,    77,    40,   259,   199,    75,   268,
   239,   -22,    51,   222,   120,   154,    20,    77,   188,   284,
    21,    22,   181,   182,   183,   184,   185,   186,   269,   219,
   220,   268,    39,   212,    24,   213,    41,   170,    25,    26,
    30,    31,    34,   139,   140,   141,   204,   168,    70,   169,
    72,    73,    74,   136,   137,   123,   123,    61,     1,     2,
     3,     4,     5,     6,     7,     8,   193,    62,   194,     9,
    63,    64,    65,    66,    67,    68,    49,    69,    70,    71,
    72,    73,    74,   210,   211,    75,   143,   144,   145,   146,
   147,   148,    45,   248,    77,   213,    56,    31,    58,   236,
   237,   221,    70,   109,   111,   172,   129,   130,   131,   132,
   133,   134,   114,   149,   150,    75,   240,   241,    76,   115,
   117,   119,   254,   -98,    77,   118,   127,   121,   120,   126,
   125,   264,   263,    61,     1,     2,     3,     4,     5,     6,
     7,     8,   128,    62,   151,     9,    63,    64,    65,    66,
    67,    68,   158,    69,    70,    71,    72,    73,    74,     1,
     2,     3,     4,     5,     6,     7,     8,   162,   152,   165,
     9,   166,   187,   173,   197,   200,   -21,   202,   201,   209,
   -23,   207,   216,   234,   226,   227,   230,   223,   225,   242,
   249,    75,   232,   233,    76,   250,   243,   265,   270,   255,
    77,   267,   257,   271,   272,   286,   278,   276,   273,   277,
   289,   279,   287,   290,    28,    57,    55,   275,   245,   189,
   282,   208,   285,   190,   231,   176,   178,   179,   160,   180,
   274
};

static const short yycheck[] = {    50,
    75,    49,   121,     0,    75,    23,   192,    25,    25,     4,
   111,    62,   192,   114,    11,    41,    26,    65,    15,    23,
    24,    25,    26,    27,    28,    41,    77,    23,    24,    25,
    26,    27,    28,    25,    26,    27,   111,     4,    64,   114,
    23,    24,    25,    26,    27,    28,    25,    41,    27,    67,
    41,    68,   127,   128,    65,    71,    40,   128,    68,    40,
   135,     0,    40,   138,   115,    61,    70,   142,    64,    70,
   121,    21,    11,   259,    70,    25,    68,    71,    61,   259,
    71,    67,    66,   202,    70,    66,     4,    70,    66,    68,
     8,     9,   143,   144,   145,   146,   147,   148,   284,   200,
   201,   281,    22,    25,     4,    27,    26,   226,     8,     9,
    23,    24,   109,    56,    57,    58,   167,    23,    24,    25,
    26,    27,    28,    54,    55,   200,   201,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    23,    13,    25,    15,
    16,    17,    18,    19,    20,    21,    71,    23,    24,    25,
    26,    27,    28,   187,   188,    61,    35,    36,    37,    38,
    39,    40,    64,    25,    70,    27,    23,    24,    23,   217,
   218,    23,    24,    65,    70,   226,    46,    47,    48,    49,
    50,    51,    70,    62,    63,    61,   221,   222,    64,    70,
    64,    64,   243,    69,    70,    70,    41,    66,    70,    64,
    68,   252,   250,     3,     4,     5,     6,     7,     8,     9,
    10,    11,    42,    13,    67,    15,    16,    17,    18,    19,
    20,    21,    66,    23,    24,    25,    26,    27,    28,     4,
     5,     6,     7,     8,     9,    10,    11,    64,    67,    16,
    15,    26,    66,    71,    67,    64,    67,    65,    70,    69,
    67,    67,    67,    40,    66,    65,    65,    71,    71,    64,
    68,    61,    69,    69,    64,    29,    65,    64,    69,    67,
    70,    65,    26,    69,    69,    25,    65,    69,    71,    69,
     0,    65,    65,     0,    11,    46,    44,   267,   226,   152,
   278,   174,   279,   152,   213,   127,   135,   138,   109,   142,
   266
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 11:
#line 111 "amogh.y"
{if(duplicate(curid)){printf("Duplicate\n");exit(0);}insertSTnest(curid,currnest); ins();  ;
    break;}
case 13:
#line 112 "amogh.y"
{if(duplicate(curid)){printf("Duplicate\n");exit(0);}insertSTnest(curid,currnest); ins();  ;
    break;}
case 73:
#line 205 "amogh.y"
{ strcpy(currfunctype, curtype); strcpy(currfunc, curid); check_duplicate(curid); insertSTF(curid); ins(); ;
    break;}
case 77:
#line 214 "amogh.y"
{ check_params(curtype); ;
    break;}
case 78:
#line 214 "amogh.y"
{ insertSTparamscount(currfunc, params_count); ;
    break;}
case 82:
#line 224 "amogh.y"
{ ins();insertSTnest(curid,1); params_count++; ;
    break;}
case 95:
#line 242 "amogh.y"
{currnest++;;
    break;}
case 96:
#line 242 "amogh.y"
{deletedata(currnest);currnest--;;
    break;}
case 101:
#line 253 "amogh.y"
{if(yyvsp[-1]!=1){printf("Condition checking is not of type int\n");exit(0);};
    break;}
case 105:
#line 260 "amogh.y"
{if(yyvsp[-1]!=1){printf("Condition checking is not of type int\n");exit(0);};
    break;}
case 107:
#line 261 "amogh.y"
{if(yyvsp[-1]!=1){printf("Condition checking is not of type int\n");exit(0);};
    break;}
case 109:
#line 262 "amogh.y"
{if(yyvsp[-1]!=1){printf("Condition checking is not of type int\n");exit(0);};
    break;}
case 111:
#line 265 "amogh.y"
{if(strcmp(currfunctype,"void")) {printf("Returning void of a non-void function\n"); exit(0);};
    break;}
case 112:
#line 266 "amogh.y"
{ 	if(!strcmp(currfunctype, "void"))
										{ 
											yyerror("Function is void");
										}

										if((currfunctype[0]=='i' || currfunctype[0]=='c') && yyvsp[-1]!=1)
										{
											printf("Expression doesn't match return type of function\n"); exit(0);
										}
			              
			                     	;
    break;}
case 119:
#line 293 "amogh.y"
{insV();;
    break;}
case 129:
#line 315 "amogh.y"
{
																	  if(yyvsp[-2]==1 && yyvsp[0]==1) 
																	  {
			                                                          yyval=1;
			                                                          } 
			                                                          else 
			                                                          {yyval=-1; printf("Type mismatch\n"); exit(0);} 
			                                                       ;
    break;}
case 130:
#line 323 "amogh.y"
{
																	  if(yyvsp[-2]==1 && yyvsp[0]==1) 
			                                                          yyval=1; 
			                                                          else 
			                                                          {yyval=-1; printf("Type mismatch\n"); exit(0);} 
			                                                       ;
    break;}
case 131:
#line 329 "amogh.y"
{
																	  if(yyvsp[-2]==1 && yyvsp[0]==1) 
			                                                          yyval=1; 
			                                                          else 
			                                                          {yyval=-1; printf("Type mismatch\n"); exit(0);} 
			                                                       ;
    break;}
case 132:
#line 335 "amogh.y"
{
																	  if(yyvsp[-2]==1 && yyvsp[0]==1) 
			                                                          yyval=1; 
			                                                          else 
			                                                          {yyval=-1; printf("Type mismatch\n"); exit(0);} 
			                                                       ;
    break;}
case 133:
#line 341 "amogh.y"
{
																	  if(yyvsp[-2]==1 && yyvsp[0]==1) 
			                                                          yyval=1; 
			                                                          else 
			                                                          {yyval=-1; printf("Type mismatch\n"); exit(0);} 
			                                                       ;
    break;}
case 134:
#line 347 "amogh.y"
{
																	  if(yyvsp[-2]==1 && yyvsp[0]==1) 
			                                                          yyval=1; 
			                                                          else 
			                                                          {yyval=-1; printf("Type mismatch\n"); exit(0);} 
			                                                       ;
    break;}
case 135:
#line 353 "amogh.y"
{if(yyvsp[-1] == 1) yyval=1; else yyval=-1;;
    break;}
case 136:
#line 354 "amogh.y"
{if(yyvsp[-1] == 1) yyval=1; else yyval=-1;;
    break;}
case 137:
#line 355 "amogh.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 138:
#line 359 "amogh.y"
{if(yyvsp[-2] == 1 && yyvsp[0]==1) yyval=1; else yyval=-1;;
    break;}
case 139:
#line 360 "amogh.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 140:
#line 363 "amogh.y"
{if(yyvsp[-2] == 1 && yyvsp[0]==1) yyval=1; else yyval=-1;;
    break;}
case 141:
#line 364 "amogh.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 142:
#line 368 "amogh.y"
{if(yyvsp[0]==1) yyval=1; else yyval=-1;;
    break;}
case 143:
#line 369 "amogh.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 144:
#line 372 "amogh.y"
{if(yyvsp[-2] == 1 && yyvsp[0]==1) yyval=1; else yyval=-1;;
    break;}
case 145:
#line 373 "amogh.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 152:
#line 380 "amogh.y"
{if(yyvsp[-2] == 1 && yyvsp[0]==1) yyval=1; else yyval=-1;;
    break;}
case 153:
#line 381 "amogh.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 156:
#line 388 "amogh.y"
{if(yyvsp[-2] == 1 && yyvsp[0]==1) yyval=1; else yyval=-1;;
    break;}
case 157:
#line 389 "amogh.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 161:
#line 395 "amogh.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 162:
#line 396 "amogh.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 163:
#line 399 "amogh.y"
{
						  if(check_id_is_func(curid))
						  {printf("Function name used as Identifier\n"); exit(8);}
			              if(!checkscope(curid))
			              {printf("%s\n",curid);printf("Undeclared\n");exit(0);} 
			              if(!checkarray(curid))
			              {printf("%s\n",curid);printf("Array ID has no subscript\n");exit(0);}
			              if(gettype(curid,0)=='i' || gettype(curid,1)== 'c')
			              yyval = 1;
			              else
			              yyval = -1;
			              ;
    break;}
case 165:
#line 420 "amogh.y"
{if(yyvsp[-1]==1) yyval=1; else yyval=-1;;
    break;}
case 167:
#line 422 "amogh.y"
{if(yyvsp[0]==1) yyval=1; else yyval=-1;;
    break;}
case 168:
#line 425 "amogh.y"
{
			             if(!check_declaration(curid, "Function"))
			             { printf("Function not declared"); exit(0);} 
			             insertSTF(curid); 
						 strcpy(currfunccall,curid);
			             ;
    break;}
case 169:
#line 431 "amogh.y"
{ if(strcmp(currfunccall,"printf"))
							{ 
								if(getSTparamscount(currfunccall)!=call_params_count)
								{	
									yyerror("Number of arguments in function call doesn't match number of parameters");
									//printf("Number of arguments in function call %s doesn't match number of parameters\n", currfunccall);
									exit(8);
								}
							} 
						 ;
    break;}
case 172:
#line 446 "amogh.y"
{ call_params_count++; ;
    break;}
case 174:
#line 449 "amogh.y"
{ call_params_count++; ;
    break;}
case 177:
#line 453 "amogh.y"
{  insV(); yyval=1; ;
    break;}
case 178:
#line 454 "amogh.y"
{  insV(); yyval=-1;;
    break;}
case 179:
#line 455 "amogh.y"
{  insV(); ;
    break;}
case 180:
#line 456 "amogh.y"
{  insV();yyval=1; ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 458 "amogh.y"


extern FILE *yyin;
extern int yylineno;
extern char *yytext;
void insertSTtype(char *,char *);
void insertSTvalue(char *, char *);
void incertCT(char *, char *);
void printST();
void printCT();



int main(int argc , char **argv)
{
	yyin = fopen(argv[1], "r");
	yyparse();

	if(flag == 0)
	{
		printf(ANSI_COLOR_GREEN "Status: Parsing Complete - Valid" ANSI_COLOR_RESET "\n");
		printf("%30s" ANSI_COLOR_CYAN "SYMBOL TABLE" ANSI_COLOR_RESET "\n", " ");
		printf("%30s %s\n", " ", "------------");
		printST();

		printf("\n\n%30s" ANSI_COLOR_CYAN "CONSTANT TABLE" ANSI_COLOR_RESET "\n", " ");
		printf("%30s %s\n", " ", "--------------");
		printCT();
	}

printf("\n........................Prakhar doing task 4...................\n");

}

void yyerror(char *s)
{
	printf(ANSI_COLOR_RED "%d %s %s\n", yylineno, s, yytext);
	flag=1;
	printf(ANSI_COLOR_RED "Status: Parsing Failed - Invalid\n" ANSI_COLOR_RESET);
	exit(7);
}

void ins()
{
	insertSTtype(curid,curtype);
}

void insV()
{
	insertSTvalue(curid,curval);
}

int yywrap()
{
	return 1;
}