#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from parser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "parser.y"

	void yyerror(char* s);
	int yylex();
	#include "stdio.h"
	#include "stdlib.h"
	#include "ctype.h"
	#include "string.h"
	void ins();
	void insV();
	int flag=0;
	#define ANSI_COLOR_RED		"\x1b[31m"
	#define ANSI_COLOR_GREEN	"\x1b[32m"
	#define ANSI_COLOR_CYAN		"\x1b[36m"
	#define ANSI_COLOR_RESET	"\x1b[0m"
	extern char curid[20];
	extern char curtype[20];
	extern char curval[20];
	extern int currnest;
	void deletedata (int );
	int checkscope(char*);
	int check_id_is_func(char *);
	void insertST(char*, char*);
	void insertSTnest(char*, int);
	void insertSTparamscount(char*, int);
	int getSTparamscount(char*);
	int check_duplicate(char*);
	int check_declaration(char*, char *);
	int check_params(char*);
	int duplicate(char *s);
	int checkarray(char*);
	char currfunctype[100];
	char currfunc[100];
	char currfunccall[100];
	void insertSTF(char*);
	char gettype(char*,int);
	char getfirst(char*);
	extern int params_count;
	int call_params_count;

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	IF	258
#define	INT	259
#define	CHAR	260
#define	FLOAT	261
#define	DOUBLE	262
#define	LONG	263
#define	SHORT	264
#define	SIGNED	265
#define	UNSIGNED	266
#define	STRUCT	267
#define	RETURN	268
#define	MAIN	269
#define	VOID	270
#define	WHILE	271
#define	FOR	272
#define	DO	273
#define	BREAK	274
#define	ENDIF	275
#define	identifier	276
#define	array_identifier	277
#define	func_identifier	278
#define	integer_constant	279
#define	string_constant	280
#define	float_constant	281
#define	character_constant	282
#define	ELSE	283
#define	leftshift_assignment_operator	284
#define	rightshift_assignment_operator	285
#define	XOR_assignment_operator	286
#define	OR_assignment_operator	287
#define	AND_assignment_operator	288
#define	modulo_assignment_operator	289
#define	multiplication_assignment_operator	290
#define	division_assignment_operator	291
#define	addition_assignment_operator	292
#define	subtraction_assignment_operator	293
#define	assignment_operator	294
#define	OR_operator	295
#define	AND_operator	296
#define	pipe_operator	297
#define	caret_operator	298
#define	amp_operator	299
#define	equality_operator	300
#define	inequality_operator	301
#define	lessthan_assignment_operator	302
#define	lessthan_operator	303
#define	greaterthan_assignment_operator	304
#define	greaterthan_operator	305
#define	leftshift_operator	306
#define	rightshift_operator	307
#define	add_operator	308
#define	subtract_operator	309
#define	multiplication_operator	310
#define	division_operator	311
#define	modulo_operator	312
#define	SIZEOF	313
#define	tilde_operator	314
#define	exclamation_operator	315
#define	increment_operator	316
#define	decrement_operator	317


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int IF;
static const int INT;
static const int CHAR;
static const int FLOAT;
static const int DOUBLE;
static const int LONG;
static const int SHORT;
static const int SIGNED;
static const int UNSIGNED;
static const int STRUCT;
static const int RETURN;
static const int MAIN;
static const int VOID;
static const int WHILE;
static const int FOR;
static const int DO;
static const int BREAK;
static const int ENDIF;
static const int identifier;
static const int array_identifier;
static const int func_identifier;
static const int integer_constant;
static const int string_constant;
static const int float_constant;
static const int character_constant;
static const int ELSE;
static const int leftshift_assignment_operator;
static const int rightshift_assignment_operator;
static const int XOR_assignment_operator;
static const int OR_assignment_operator;
static const int AND_assignment_operator;
static const int modulo_assignment_operator;
static const int multiplication_assignment_operator;
static const int division_assignment_operator;
static const int addition_assignment_operator;
static const int subtraction_assignment_operator;
static const int assignment_operator;
static const int OR_operator;
static const int AND_operator;
static const int pipe_operator;
static const int caret_operator;
static const int amp_operator;
static const int equality_operator;
static const int inequality_operator;
static const int lessthan_assignment_operator;
static const int lessthan_operator;
static const int greaterthan_assignment_operator;
static const int greaterthan_operator;
static const int leftshift_operator;
static const int rightshift_operator;
static const int add_operator;
static const int subtract_operator;
static const int multiplication_operator;
static const int division_operator;
static const int modulo_operator;
static const int SIZEOF;
static const int tilde_operator;
static const int exclamation_operator;
static const int increment_operator;
static const int decrement_operator;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,IF=258
	,INT=259
	,CHAR=260
	,FLOAT=261
	,DOUBLE=262
	,LONG=263
	,SHORT=264
	,SIGNED=265
	,UNSIGNED=266
	,STRUCT=267
	,RETURN=268
	,MAIN=269
	,VOID=270
	,WHILE=271
	,FOR=272
	,DO=273
	,BREAK=274
	,ENDIF=275
	,identifier=276
	,array_identifier=277
	,func_identifier=278
	,integer_constant=279
	,string_constant=280
	,float_constant=281
	,character_constant=282
	,ELSE=283
	,leftshift_assignment_operator=284
	,rightshift_assignment_operator=285
	,XOR_assignment_operator=286
	,OR_assignment_operator=287
	,AND_assignment_operator=288
	,modulo_assignment_operator=289
	,multiplication_assignment_operator=290
	,division_assignment_operator=291
	,addition_assignment_operator=292
	,subtraction_assignment_operator=293
	,assignment_operator=294
	,OR_operator=295
	,AND_operator=296
	,pipe_operator=297
	,caret_operator=298
	,amp_operator=299
	,equality_operator=300
	,inequality_operator=301
	,lessthan_assignment_operator=302
	,lessthan_operator=303
	,greaterthan_assignment_operator=304
	,greaterthan_operator=305
	,leftshift_operator=306
	,rightshift_operator=307
	,add_operator=308
	,subtract_operator=309
	,multiplication_operator=310
	,division_operator=311
	,modulo_operator=312
	,SIZEOF=313
	,tilde_operator=314
	,exclamation_operator=315
	,increment_operator=316
	,decrement_operator=317


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::IF=258;
const int YY_parse_CLASS::INT=259;
const int YY_parse_CLASS::CHAR=260;
const int YY_parse_CLASS::FLOAT=261;
const int YY_parse_CLASS::DOUBLE=262;
const int YY_parse_CLASS::LONG=263;
const int YY_parse_CLASS::SHORT=264;
const int YY_parse_CLASS::SIGNED=265;
const int YY_parse_CLASS::UNSIGNED=266;
const int YY_parse_CLASS::STRUCT=267;
const int YY_parse_CLASS::RETURN=268;
const int YY_parse_CLASS::MAIN=269;
const int YY_parse_CLASS::VOID=270;
const int YY_parse_CLASS::WHILE=271;
const int YY_parse_CLASS::FOR=272;
const int YY_parse_CLASS::DO=273;
const int YY_parse_CLASS::BREAK=274;
const int YY_parse_CLASS::ENDIF=275;
const int YY_parse_CLASS::identifier=276;
const int YY_parse_CLASS::array_identifier=277;
const int YY_parse_CLASS::func_identifier=278;
const int YY_parse_CLASS::integer_constant=279;
const int YY_parse_CLASS::string_constant=280;
const int YY_parse_CLASS::float_constant=281;
const int YY_parse_CLASS::character_constant=282;
const int YY_parse_CLASS::ELSE=283;
const int YY_parse_CLASS::leftshift_assignment_operator=284;
const int YY_parse_CLASS::rightshift_assignment_operator=285;
const int YY_parse_CLASS::XOR_assignment_operator=286;
const int YY_parse_CLASS::OR_assignment_operator=287;
const int YY_parse_CLASS::AND_assignment_operator=288;
const int YY_parse_CLASS::modulo_assignment_operator=289;
const int YY_parse_CLASS::multiplication_assignment_operator=290;
const int YY_parse_CLASS::division_assignment_operator=291;
const int YY_parse_CLASS::addition_assignment_operator=292;
const int YY_parse_CLASS::subtraction_assignment_operator=293;
const int YY_parse_CLASS::assignment_operator=294;
const int YY_parse_CLASS::OR_operator=295;
const int YY_parse_CLASS::AND_operator=296;
const int YY_parse_CLASS::pipe_operator=297;
const int YY_parse_CLASS::caret_operator=298;
const int YY_parse_CLASS::amp_operator=299;
const int YY_parse_CLASS::equality_operator=300;
const int YY_parse_CLASS::inequality_operator=301;
const int YY_parse_CLASS::lessthan_assignment_operator=302;
const int YY_parse_CLASS::lessthan_operator=303;
const int YY_parse_CLASS::greaterthan_assignment_operator=304;
const int YY_parse_CLASS::greaterthan_operator=305;
const int YY_parse_CLASS::leftshift_operator=306;
const int YY_parse_CLASS::rightshift_operator=307;
const int YY_parse_CLASS::add_operator=308;
const int YY_parse_CLASS::subtract_operator=309;
const int YY_parse_CLASS::multiplication_operator=310;
const int YY_parse_CLASS::division_operator=311;
const int YY_parse_CLASS::modulo_operator=312;
const int YY_parse_CLASS::SIZEOF=313;
const int YY_parse_CLASS::tilde_operator=314;
const int YY_parse_CLASS::exclamation_operator=315;
const int YY_parse_CLASS::increment_operator=316;
const int YY_parse_CLASS::decrement_operator=317;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		217
#define	YYFLAG		-32768
#define	YYNTBASE	71

#define YYTRANSLATE(x) ((unsigned)(x) <= 317 ? yytranslate[x] : 140)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,    67,
    68,     2,     2,    64,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    63,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    65,     2,    66,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    69,     2,    70,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54,    55,
    56,    57,    58,    59,    60,    61,    62
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     5,     7,     8,    10,    12,    16,    20,    22,
    23,    27,    28,    32,    34,    37,    40,    41,    45,    48,
    50,    52,    53,    55,    57,    59,    61,    64,    67,    70,
    73,    75,    77,    80,    83,    84,    86,    89,    92,    93,
    95,    96,    98,    99,   102,   106,   110,   112,   113,   114,
   118,   121,   124,   125,   126,   130,   133,   134,   136,   138,
   140,   142,   144,   146,   148,   149,   154,   157,   158,   161,
   163,   164,   172,   175,   176,   177,   184,   185,   195,   196,
   205,   208,   212,   215,   218,   223,   226,   229,   230,   234,
   238,   242,   246,   250,   254,   257,   260,   262,   266,   268,
   272,   274,   277,   279,   283,   285,   287,   289,   291,   293,
   295,   297,   301,   303,   305,   307,   311,   313,   315,   317,
   319,   321,   323,   325,   326,   332,   336,   338,   340,   341,
   347,   349,   350,   351,   355,   356,   361,   362,   364,   366,
   368
};

static const short yyrhs[] = {    72,
     0,    74,    73,     0,    72,     0,     0,    75,     0,    89,
     0,    84,    76,    63,     0,    76,    64,    77,     0,    77,
     0,     0,    21,    78,    80,     0,     0,    22,    79,    80,
     0,    81,     0,    39,   119,     0,    65,    82,     0,     0,
    24,    66,    83,     0,    66,   114,     0,   114,     0,   115,
     0,     0,     4,     0,     5,     0,     6,     0,     7,     0,
     8,    87,     0,     9,    88,     0,    11,    85,     0,    10,
    86,     0,    15,     0,     4,     0,     8,    87,     0,     9,
    88,     0,     0,     4,     0,     8,    87,     0,     9,    88,
     0,     0,     4,     0,     0,     4,     0,     0,    90,    91,
     0,    84,    21,    67,     0,    92,    68,   100,     0,    93,
     0,     0,     0,    84,    94,    95,     0,    97,    96,     0,
    64,    93,     0,     0,     0,    21,    98,    99,     0,    65,
    66,     0,     0,   104,     0,   101,     0,   105,     0,   108,
     0,   112,     0,   113,     0,    75,     0,     0,   102,    69,
   103,    70,     0,   100,   103,     0,     0,   118,    63,     0,
    63,     0,     0,     3,    67,   119,    68,   106,   100,   107,
     0,    28,   100,     0,     0,     0,    16,    67,   119,    68,
   109,   100,     0,     0,    17,    67,   118,    63,   119,    63,
   110,   118,    68,     0,     0,    18,   100,    16,    67,   119,
    68,   111,    63,     0,    13,    63,     0,    13,   118,    63,
     0,    19,    63,     0,    39,    25,     0,    39,    69,   116,
    70,     0,    24,   117,     0,    64,   116,     0,     0,   129,
    39,   118,     0,   129,    37,   118,     0,   129,    38,   118,
     0,   129,    35,   118,     0,   129,    36,   118,     0,   129,
    34,   118,     0,   129,    61,     0,   129,    62,     0,   119,
     0,   119,    40,   120,     0,   120,     0,   120,    41,   121,
     0,   121,     0,    60,   121,     0,   122,     0,   122,   123,
   124,     0,   124,     0,    49,     0,    47,     0,    50,     0,
    48,     0,    45,     0,    46,     0,   124,   125,   126,     0,
   126,     0,    53,     0,    54,     0,   126,   127,   128,     0,
   128,     0,    55,     0,    56,     0,    57,     0,   131,     0,
   129,     0,    21,     0,     0,    22,   130,    65,   118,    66,
     0,    67,   118,    68,     0,   132,     0,   139,     0,     0,
    21,    67,   133,   134,    68,     0,   135,     0,     0,     0,
   118,   136,   137,     0,     0,    64,   118,   138,   137,     0,
     0,    24,     0,    25,     0,    26,     0,    27,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    82,    85,    88,    89,    92,    93,    96,    99,    99,   102,
   103,   103,   103,   107,   107,   110,   111,   114,   115,   118,
   119,   120,   123,   123,   123,   123,   124,   125,   126,   127,
   128,   131,   131,   131,   131,   134,   134,   134,   134,   137,
   137,   140,   140,   143,   146,   149,   152,   152,   155,   155,
   158,   161,   162,   165,   165,   168,   169,   172,   172,   173,
   173,   174,   174,   175,   178,   178,   181,   182,   185,   186,
   189,   189,   192,   193,   196,   197,   197,   197,   198,   198,
   200,   201,   214,   217,   220,   223,   226,   227,   230,   238,
   244,   250,   256,   262,   268,   269,   270,   274,   275,   278,
   279,   283,   284,   287,   288,   291,   291,   291,   292,   292,
   292,   295,   296,   299,   300,   303,   304,   307,   307,   307,
   310,   311,   314,   326,   326,   334,   335,   336,   339,   344,
   357,   357,   360,   360,   363,   364,   364,   367,   368,   369,
   370
};

static const char * const yytname[] = {   "$","error","$illegal.","IF","INT",
"CHAR","FLOAT","DOUBLE","LONG","SHORT","SIGNED","UNSIGNED","STRUCT","RETURN",
"MAIN","VOID","WHILE","FOR","DO","BREAK","ENDIF","identifier","array_identifier",
"func_identifier","integer_constant","string_constant","float_constant","character_constant",
"ELSE","leftshift_assignment_operator","rightshift_assignment_operator","XOR_assignment_operator",
"OR_assignment_operator","AND_assignment_operator","modulo_assignment_operator",
"multiplication_assignment_operator","division_assignment_operator","addition_assignment_operator",
"subtraction_assignment_operator","assignment_operator","OR_operator","AND_operator",
"pipe_operator","caret_operator","amp_operator","equality_operator","inequality_operator",
"lessthan_assignment_operator","lessthan_operator","greaterthan_assignment_operator",
"greaterthan_operator","leftshift_operator","rightshift_operator","add_operator",
"subtract_operator","multiplication_operator","division_operator","modulo_operator",
"SIZEOF","tilde_operator","exclamation_operator","increment_operator","decrement_operator",
"';'","','","'['","']'","'('","')'","'{'","'}'","program","declaration_list",
"D","declaration","variable_declaration","variable_declaration_list","variable_declaration_identifier",
"@1","@2","vdi","identifier_array_type","initilization_params","initilization",
"type_specifier","unsigned_grammar","signed_grammar","long_grammar","short_grammar",
"function_declaration","function_declaration_type","function_declaration_param_statement",
"params","parameters_list","@3","parameters_identifier_list","parameters_identifier_list_breakup",
"param_identifier","@4","param_identifier_breakup","statement","compound_statement",
"@5","statment_list","expression_statment","conditional_statements","@6","conditional_statements_breakup",
"iterative_statements","@7","@8","@9","return_statement","break_statement","string_initilization",
"array_initialization","array_int_declarations","array_int_declarations_breakup",
"expression","simple_expression","and_expression","unary_relation_expression",
"regular_expression","relational_operators","sum_expression","sum_operators",
"term","MULOP","factor","mutable","@10","immutable","call","@11","arguments",
"arguments_list","@12","A","@13","constant",""
};
#endif

static const short yyr1[] = {     0,
    71,    72,    73,    73,    74,    74,    75,    76,    76,    78,
    77,    79,    77,    80,    80,    81,    81,    82,    82,    83,
    83,    83,    84,    84,    84,    84,    84,    84,    84,    84,
    84,    85,    85,    85,    85,    86,    86,    86,    86,    87,
    87,    88,    88,    89,    90,    91,    92,    92,    94,    93,
    95,    96,    96,    98,    97,    99,    99,   100,   100,   100,
   100,   100,   100,   100,   102,   101,   103,   103,   104,   104,
   106,   105,   107,   107,   109,   108,   110,   108,   111,   108,
   112,   112,   113,   114,   115,   116,   117,   117,   118,   118,
   118,   118,   118,   118,   118,   118,   118,   119,   119,   120,
   120,   121,   121,   122,   122,   123,   123,   123,   123,   123,
   123,   124,   124,   125,   125,   126,   126,   127,   127,   127,
   128,   128,   129,   130,   129,   131,   131,   131,   133,   132,
   134,   134,   136,   135,   138,   137,   137,   139,   139,   139,
   139
};

static const short yyr2[] = {     0,
     1,     2,     1,     0,     1,     1,     3,     3,     1,     0,
     3,     0,     3,     1,     2,     2,     0,     3,     2,     1,
     1,     0,     1,     1,     1,     1,     2,     2,     2,     2,
     1,     1,     2,     2,     0,     1,     2,     2,     0,     1,
     0,     1,     0,     2,     3,     3,     1,     0,     0,     3,
     2,     2,     0,     0,     3,     2,     0,     1,     1,     1,
     1,     1,     1,     1,     0,     4,     2,     0,     2,     1,
     0,     7,     2,     0,     0,     6,     0,     9,     0,     8,
     2,     3,     2,     2,     4,     2,     2,     0,     3,     3,
     3,     3,     3,     3,     2,     2,     1,     3,     1,     3,
     1,     2,     1,     3,     1,     1,     1,     1,     1,     1,
     1,     3,     1,     1,     1,     3,     1,     1,     1,     1,
     1,     1,     1,     0,     5,     3,     1,     1,     0,     5,
     1,     0,     0,     3,     0,     4,     0,     1,     1,     1,
     1
};

static const short yydefact[] = {     0,
    23,    24,    25,    26,    41,    43,    39,    35,    31,     1,
     4,     5,     0,     6,    48,    40,    27,    42,    28,    36,
    41,    43,    30,    32,    41,    43,    29,     3,     2,    10,
    12,     0,     9,    49,    44,     0,    47,    37,    38,    33,
    34,    45,    17,    17,     7,     0,     0,    65,     0,     0,
    11,    14,    13,    10,     8,    54,    50,    53,     0,     0,
     0,     0,    65,     0,   123,   124,   138,   139,   140,   141,
     0,    70,     0,    64,     0,    46,    59,     0,    58,    60,
    61,    62,    63,     0,    97,    99,   101,   103,   105,   113,
   117,   122,   121,   127,   128,    15,   122,     0,     0,    16,
    57,     0,    51,     0,    81,     0,     0,     0,     0,    83,
   129,     0,   102,     0,    65,    69,     0,     0,   110,   111,
   107,   109,   106,   108,     0,   114,   115,     0,   118,   119,
   120,     0,     0,     0,     0,     0,     0,     0,    95,    96,
    22,     0,    19,     0,    55,    52,     0,    82,     0,     0,
     0,   132,     0,   126,    65,     0,    98,   100,   104,   112,
   116,    94,    92,    93,    90,    91,    89,     0,    18,    20,
    21,    84,    56,    71,    75,     0,     0,   133,     0,   131,
     0,    67,    66,     0,    65,    65,     0,     0,   137,   130,
   125,    88,     0,    74,    76,    77,    79,     0,   134,     0,
    86,    85,    65,    72,     0,     0,   135,    87,    73,     0,
    80,   137,    78,   136,     0,     0,     0
};

static const short yydefgoto[] = {   215,
    10,    29,    11,    74,    32,    33,    43,    44,    51,    52,
   100,   169,    75,    27,    23,    17,    19,    14,    15,    35,
    36,    37,    47,    57,   103,    58,   101,   145,   155,    77,
    78,   156,    79,    80,   185,   204,    81,   186,   205,   206,
    82,    83,   143,   171,   193,   201,    84,    85,    86,    87,
    88,   125,    89,   128,    90,   132,    91,    92,   112,    93,
    94,   152,   179,   180,   189,   199,   212,    95
};

static const short yypact[] = {   177,
-32768,-32768,-32768,-32768,     8,    67,    60,    77,-32768,-32768,
   177,-32768,    69,-32768,   177,-32768,-32768,-32768,-32768,-32768,
     8,    67,-32768,-32768,     8,    67,-32768,-32768,-32768,   -58,
-32768,    62,-32768,-32768,-32768,    14,-32768,-32768,-32768,-32768,
-32768,-32768,   -22,   -22,-32768,   106,    63,   153,    76,    -5,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,    40,    45,     3,
    68,    75,   153,    82,    83,-32768,-32768,-32768,-32768,-32768,
    76,-32768,    76,-32768,   106,-32768,-32768,    78,-32768,-32768,
-32768,-32768,-32768,    86,   112,   113,-32768,    74,    80,   -34,
-32768,    79,-32768,-32768,-32768,   112,-32768,    87,   126,-32768,
   102,   177,-32768,    76,-32768,   110,    76,    76,   160,-32768,
-32768,   124,-32768,   123,    29,-32768,    76,    76,-32768,-32768,
-32768,-32768,-32768,-32768,    84,-32768,-32768,    84,-32768,-32768,
-32768,    84,    76,    76,    76,    76,    76,    76,-32768,-32768,
   151,   168,-32768,   128,-32768,-32768,   -37,-32768,   -27,   132,
   129,    76,    76,-32768,    29,   127,   113,-32768,    80,   -34,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,   -17,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,    76,    76,-32768,   130,-32768,
   133,-32768,-32768,   176,   153,   153,    25,    27,   137,-32768,
-32768,   138,   134,   175,-32768,-32768,-32768,    76,-32768,   176,
-32768,-32768,   153,-32768,    76,   142,-32768,-32768,-32768,   139,
-32768,   137,-32768,-32768,   206,   208,-32768
};

static const short yypgoto[] = {-32768,
   198,-32768,-32768,     7,-32768,   164,-32768,-32768,   167,-32768,
-32768,-32768,     5,-32768,-32768,   -15,   122,-32768,-32768,-32768,
-32768,   115,-32768,-32768,-32768,-32768,-32768,-32768,   -48,-32768,
-32768,    57,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,    73,-32768,    15,-32768,   -59,   -47,   101,   -60,
-32768,-32768,    94,-32768,    93,-32768,    90,   -45,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,    11,-32768,-32768
};


#define	YYLAST		223


static const short yytable[] = {    76,
   106,    96,   117,    97,    13,    38,    12,   172,    42,    40,
   113,    16,   117,   114,   109,    13,    49,    12,    98,    34,
   129,   130,   131,    65,    66,    97,    67,    68,    69,    70,
   174,    59,     1,     2,     3,     4,     5,     6,     7,     8,
   175,    60,    50,     9,    61,    62,    63,    64,   150,    65,
    66,   184,    67,    68,    69,    70,   147,   158,    97,   149,
    99,    97,    71,    20,   117,   105,   117,    21,    22,    73,
    18,    97,    97,   162,   163,   164,   165,   166,   167,    97,
    24,    48,    97,    56,    25,    26,    97,   196,    71,    30,
    31,    72,   178,   181,   197,    73,    65,    66,   -68,    67,
    68,    69,    70,   102,    65,    66,    34,    67,    68,    69,
    70,   104,   133,   134,   135,   136,   137,   138,   119,   120,
   121,   122,   123,   124,    45,    46,    54,    31,   187,   188,
    97,    97,   126,   127,   107,    71,   194,   195,   207,   139,
   140,   108,    73,    39,   110,   210,   115,    41,   116,   111,
    73,   117,   141,   118,   209,    59,     1,     2,     3,     4,
     5,     6,     7,     8,   142,    60,   144,     9,    61,    62,
    63,    64,   148,    65,    66,   151,    67,    68,    69,    70,
     1,     2,     3,     4,     5,     6,     7,     8,   153,   168,
   154,     9,   172,   173,   176,   177,   183,   190,   191,   192,
   198,   200,   203,   202,   211,   216,   213,   217,    28,    55,
    53,   182,    71,   170,   208,    72,   146,   157,   159,    73,
   160,   161,   214
};

static const short yycheck[] = {    48,
    60,    49,    40,    49,     0,    21,     0,    25,    67,    25,
    71,     4,    40,    73,    63,    11,    39,    11,    24,    15,
    55,    56,    57,    21,    22,    71,    24,    25,    26,    27,
    68,     3,     4,     5,     6,     7,     8,     9,    10,    11,
    68,    13,    65,    15,    16,    17,    18,    19,   108,    21,
    22,    69,    24,    25,    26,    27,   104,   118,   104,   107,
    66,   107,    60,     4,    40,    63,    40,     8,     9,    67,
     4,   117,   118,   133,   134,   135,   136,   137,   138,   125,
     4,    68,   128,    21,     8,     9,   132,    63,    60,    21,
    22,    63,   152,   153,    68,    67,    21,    22,    70,    24,
    25,    26,    27,    64,    21,    22,   102,    24,    25,    26,
    27,    67,    34,    35,    36,    37,    38,    39,    45,    46,
    47,    48,    49,    50,    63,    64,    21,    22,   176,   177,
   176,   177,    53,    54,    67,    60,   185,   186,   198,    61,
    62,    67,    67,    22,    63,   205,    69,    26,    63,    67,
    67,    40,    66,    41,   203,     3,     4,     5,     6,     7,
     8,     9,    10,    11,    39,    13,    65,    15,    16,    17,
    18,    19,    63,    21,    22,    16,    24,    25,    26,    27,
     4,     5,     6,     7,     8,     9,    10,    11,    65,    39,
    68,    15,    25,    66,    63,    67,    70,    68,    66,    24,
    64,    64,    28,    70,    63,     0,    68,     0,    11,    46,
    44,   155,    60,   141,   200,    63,   102,   117,   125,    67,
   128,   132,   212
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 10:
#line 102 "parser.y"
{if(duplicate(curid)){printf("Duplicate\n");exit(0);}insertSTnest(curid,currnest); ins();  ;
    break;}
case 12:
#line 103 "parser.y"
{if(duplicate(curid)){printf("Duplicate\n");exit(0);}insertSTnest(curid,currnest); ins();  ;
    break;}
case 18:
#line 114 "parser.y"
{if(yyval < 1) {printf("Wrong array size\n"); exit(0);} ;
    break;}
case 45:
#line 146 "parser.y"
{ strcpy(currfunctype, curtype); strcpy(currfunc, curid); check_duplicate(curid); insertSTF(curid); ins(); ;
    break;}
case 49:
#line 155 "parser.y"
{ check_params(curtype); ;
    break;}
case 50:
#line 155 "parser.y"
{ insertSTparamscount(currfunc, params_count); ;
    break;}
case 54:
#line 165 "parser.y"
{ ins();insertSTnest(curid,1); params_count++; ;
    break;}
case 65:
#line 178 "parser.y"
{currnest++;;
    break;}
case 66:
#line 178 "parser.y"
{deletedata(currnest);currnest--;;
    break;}
case 71:
#line 189 "parser.y"
{if(yyvsp[-1]!=1){printf("Condition checking is not of type int\n");exit(0);};
    break;}
case 75:
#line 196 "parser.y"
{if(yyvsp[-1]!=1){printf("Condition checking is not of type int\n");exit(0);};
    break;}
case 77:
#line 197 "parser.y"
{if(yyvsp[-1]!=1){printf("Condition checking is not of type int\n");exit(0);};
    break;}
case 79:
#line 198 "parser.y"
{if(yyvsp[-1]!=1){printf("Condition checking is not of type int\n");exit(0);};
    break;}
case 81:
#line 200 "parser.y"
{if(strcmp(currfunctype,"void")) {printf("Returning void of a non-void function\n"); exit(0);};
    break;}
case 82:
#line 201 "parser.y"
{ 	if(!strcmp(currfunctype, "void"))
										{ 
											yyerror("Function is void");
										}

										if((currfunctype[0]=='i' || currfunctype[0]=='c') && yyvsp[-1]!=1)
										{
											printf("Expression doesn't match return type of function\n"); exit(0);
										}
			              
			                     	;
    break;}
case 84:
#line 217 "parser.y"
{insV();;
    break;}
case 89:
#line 230 "parser.y"
{
																	  if(yyvsp[-2]==1 && yyvsp[0]==1) 
																	  {
			                                                          yyval=1;
			                                                          } 
			                                                          else 
			                                                          {yyval=-1; printf("Type mismatch\n"); exit(0);} 
			                                                       ;
    break;}
case 90:
#line 238 "parser.y"
{
																	  if(yyvsp[-2]==1 && yyvsp[0]==1) 
			                                                          yyval=1; 
			                                                          else 
			                                                          {yyval=-1; printf("Type mismatch\n"); exit(0);} 
			                                                       ;
    break;}
case 91:
#line 244 "parser.y"
{
																	  if(yyvsp[-2]==1 && yyvsp[0]==1) 
			                                                          yyval=1; 
			                                                          else 
			                                                          {yyval=-1; printf("Type mismatch\n"); exit(0);} 
			                                                       ;
    break;}
case 92:
#line 250 "parser.y"
{
																	  if(yyvsp[-2]==1 && yyvsp[0]==1) 
			                                                          yyval=1; 
			                                                          else 
			                                                          {yyval=-1; printf("Type mismatch\n"); exit(0);} 
			                                                       ;
    break;}
case 93:
#line 256 "parser.y"
{
																	  if(yyvsp[-2]==1 && yyvsp[0]==1) 
			                                                          yyval=1; 
			                                                          else 
			                                                          {yyval=-1; printf("Type mismatch\n"); exit(0);} 
			                                                       ;
    break;}
case 94:
#line 262 "parser.y"
{
																	  if(yyvsp[-2]==1 && yyvsp[0]==1) 
			                                                          yyval=1; 
			                                                          else 
			                                                          {yyval=-1; printf("Type mismatch\n"); exit(0);} 
			                                                       ;
    break;}
case 95:
#line 268 "parser.y"
{if(yyvsp[-1] == 1) yyval=1; else yyval=-1;;
    break;}
case 96:
#line 269 "parser.y"
{if(yyvsp[-1] == 1) yyval=1; else yyval=-1;;
    break;}
case 97:
#line 270 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 98:
#line 274 "parser.y"
{if(yyvsp[-2] == 1 && yyvsp[0]==1) yyval=1; else yyval=-1;;
    break;}
case 99:
#line 275 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 100:
#line 278 "parser.y"
{if(yyvsp[-2] == 1 && yyvsp[0]==1) yyval=1; else yyval=-1;;
    break;}
case 101:
#line 279 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 102:
#line 283 "parser.y"
{if(yyvsp[0]==1) yyval=1; else yyval=-1;;
    break;}
case 103:
#line 284 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 104:
#line 287 "parser.y"
{if(yyvsp[-2] == 1 && yyvsp[0]==1) yyval=1; else yyval=-1;;
    break;}
case 105:
#line 288 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 112:
#line 295 "parser.y"
{if(yyvsp[-2] == 1 && yyvsp[0]==1) yyval=1; else yyval=-1;;
    break;}
case 113:
#line 296 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 116:
#line 303 "parser.y"
{if(yyvsp[-2] == 1 && yyvsp[0]==1) yyval=1; else yyval=-1;;
    break;}
case 117:
#line 304 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 121:
#line 310 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 122:
#line 311 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 123:
#line 314 "parser.y"
{
						  if(check_id_is_func(curid))
						  {printf("Function name used as Identifier\n"); exit(8);}
			              if(!checkscope(curid))
			              {printf("%s\n",curid);printf("Undeclared\n");exit(0);} 
			              if(!checkarray(curid))
			              {printf("%s\n",curid);printf("Array ID has no subscript\n");exit(0);}
			              if(gettype(curid,0)=='i' || gettype(curid,1)== 'c')
			              yyval = 1;
			              else
			              yyval = -1;
			              ;
    break;}
case 124:
#line 326 "parser.y"
{if(!checkscope(curid)){printf("%s\n",curid);printf("Undeclared\n");exit(0);};
    break;}
case 125:
#line 327 "parser.y"
{if(gettype(curid,0)=='i' || gettype(curid,1)== 'c')
			              		yyval = 1;
			              		else
			              		yyval = -1;
			              		;
    break;}
case 126:
#line 334 "parser.y"
{if(yyvsp[-1]==1) yyval=1; else yyval=-1;;
    break;}
case 128:
#line 336 "parser.y"
{if(yyvsp[0]==1) yyval=1; else yyval=-1;;
    break;}
case 129:
#line 339 "parser.y"
{
			             if(!check_declaration(curid, "Function"))
			             { printf("Function not declared"); exit(0);} 
			             insertSTF(curid); 
						 strcpy(currfunccall,curid);
			             ;
    break;}
case 130:
#line 345 "parser.y"
{ if(strcmp(currfunccall,"printf"))
							{ 
								if(getSTparamscount(currfunccall)!=call_params_count)
								{	
									yyerror("Number of arguments in function call doesn't match number of parameters");
									//printf("Number of arguments in function call %s doesn't match number of parameters\n", currfunccall);
									exit(8);
								}
							} 
						 ;
    break;}
case 133:
#line 360 "parser.y"
{ call_params_count++; ;
    break;}
case 135:
#line 363 "parser.y"
{ call_params_count++; ;
    break;}
case 138:
#line 367 "parser.y"
{  insV(); yyval=1; ;
    break;}
case 139:
#line 368 "parser.y"
{  insV(); yyval=-1;;
    break;}
case 140:
#line 369 "parser.y"
{  insV(); ;
    break;}
case 141:
#line 370 "parser.y"
{  insV();yyval=1; ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 372 "parser.y"


extern FILE *yyin;
extern int yylineno;
extern char *yytext;
void insertSTtype(char *,char *);
void insertSTvalue(char *, char *);
void incertCT(char *, char *);
void printST();
void printCT();

int main(int argc , char **argv)
{
	yyin = fopen(argv[1], "r");
	yyparse();

	if(flag == 0)
	{
		printf(ANSI_COLOR_GREEN "Status: Parsing Complete - Valid" ANSI_COLOR_RESET "\n");
		printf("%30s" ANSI_COLOR_CYAN "SYMBOL TABLE" ANSI_COLOR_RESET "\n", " ");
		printf("%30s %s\n", " ", "------------");
		printST();

		printf("\n\n%30s" ANSI_COLOR_CYAN "CONSTANT TABLE" ANSI_COLOR_RESET "\n", " ");
		printf("%30s %s\n", " ", "--------------");
		printCT();
	}
}

void yyerror(char *s)
{
	printf(ANSI_COLOR_RED "%d %s %s\n", yylineno, s, yytext);
	flag=1;
	printf(ANSI_COLOR_RED "Status: Parsing Failed - Invalid\n" ANSI_COLOR_RESET);
	exit(7);
}

void ins()
{
	insertSTtype(curid,curtype);
}

void insV()
{
	insertSTvalue(curid,curval);
}

int yywrap()
{
	return 1;
}