#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from parser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "parser.y"

	#include <stdio.h>
	#include <string.h>
	#include <stdlib.h>
	
	void yyerror(char* s);
	int yylex();
	void ins();
	void insV();
	int flag=0;
	#define ANSI_COLOR_RED		"\x1b[31m"
	#define ANSI_COLOR_GREEN	"\x1b[32m"
	#define ANSI_COLOR_CYAN		"\x1b[36m"
	#define ANSI_COLOR_RESET	"\x1b[0m"
	extern char curid[20];
	extern char curtype[20];
	extern char curval[20];
	extern int currnest;
	void deletedata (int );
	int checkscope(char*);
	int check_id_is_func(char *);
	void insertST(char*, char*);
	void insertSTnest(char*, int);
	void insertSTparamscount(char*, int);
	int getSTparamscount(char*);
	int check_duplicate(char*);
	int check_declaration(char*, char *);
	int check_params(char*);
	int duplicate(char *s);
	int checkarray(char*);
	char currfunctype[100];
	char currfunc[100];
	char currfunccall[100];
	void insertSTF(char*);
	char gettype(char*,int);
	char getfirst(char*);
	void push(char *s);
	void codegen();
	void codeassign();
	char* itoa(int num, char* str, int base);
	void reverse(char str[], int length); 
	void swap(char*,char*);
	void label1();
	void label2();
	void label3();
	void label4();
	void label5();
	void label6();
	void genunary();
	void codegencon();
	void funcgen();
	void funcgenend();
	void arggen();
	void callgen();
	void print();

	int params_count=0;
	int call_params_count=0;
	int top = 0,count=0,ltop=0,lno=0;
	char temp[3] = "t";

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	IF	258
#define	INT	259
#define	CHAR	260
#define	FLOAT	261
#define	DOUBLE	262
#define	LONG	263
#define	SHORT	264
#define	SIGNED	265
#define	UNSIGNED	266
#define	STRUCT	267
#define	RETURN	268
#define	MAIN	269
#define	VOID	270
#define	WHILE	271
#define	FOR	272
#define	DO	273
#define	BREAK	274
#define	ENDIF	275
#define	PRINTF	276
#define	CONTINUE	277
#define	identifier	278
#define	array_identifier	279
#define	func_identifier	280
#define	integer_constant	281
#define	string_constant	282
#define	float_constant	283
#define	character_constant	284
#define	ELSE	285
#define	leftshift_assignment_operator	286
#define	rightshift_assignment_operator	287
#define	XOR_assignment_operator	288
#define	OR_assignment_operator	289
#define	AND_assignment_operator	290
#define	modulo_assignment_operator	291
#define	multiplication_assignment_operator	292
#define	division_assignment_operator	293
#define	addition_assignment_operator	294
#define	subtraction_assignment_operator	295
#define	assignment_operator	296
#define	OR_operator	297
#define	AND_operator	298
#define	pipe_operator	299
#define	caret_operator	300
#define	amp_operator	301
#define	equality_operator	302
#define	inequality_operator	303
#define	lessthan_assignment_operator	304
#define	lessthan_operator	305
#define	greaterthan_assignment_operator	306
#define	greaterthan_operator	307
#define	leftshift_operator	308
#define	rightshift_operator	309
#define	add_operator	310
#define	subtract_operator	311
#define	multiplication_operator	312
#define	division_operator	313
#define	modulo_operator	314
#define	SIZEOF	315
#define	tilde_operator	316
#define	exclamation_operator	317
#define	increment_operator	318
#define	decrement_operator	319


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int IF;
static const int INT;
static const int CHAR;
static const int FLOAT;
static const int DOUBLE;
static const int LONG;
static const int SHORT;
static const int SIGNED;
static const int UNSIGNED;
static const int STRUCT;
static const int RETURN;
static const int MAIN;
static const int VOID;
static const int WHILE;
static const int FOR;
static const int DO;
static const int BREAK;
static const int ENDIF;
static const int PRINTF;
static const int CONTINUE;
static const int identifier;
static const int array_identifier;
static const int func_identifier;
static const int integer_constant;
static const int string_constant;
static const int float_constant;
static const int character_constant;
static const int ELSE;
static const int leftshift_assignment_operator;
static const int rightshift_assignment_operator;
static const int XOR_assignment_operator;
static const int OR_assignment_operator;
static const int AND_assignment_operator;
static const int modulo_assignment_operator;
static const int multiplication_assignment_operator;
static const int division_assignment_operator;
static const int addition_assignment_operator;
static const int subtraction_assignment_operator;
static const int assignment_operator;
static const int OR_operator;
static const int AND_operator;
static const int pipe_operator;
static const int caret_operator;
static const int amp_operator;
static const int equality_operator;
static const int inequality_operator;
static const int lessthan_assignment_operator;
static const int lessthan_operator;
static const int greaterthan_assignment_operator;
static const int greaterthan_operator;
static const int leftshift_operator;
static const int rightshift_operator;
static const int add_operator;
static const int subtract_operator;
static const int multiplication_operator;
static const int division_operator;
static const int modulo_operator;
static const int SIZEOF;
static const int tilde_operator;
static const int exclamation_operator;
static const int increment_operator;
static const int decrement_operator;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,IF=258
	,INT=259
	,CHAR=260
	,FLOAT=261
	,DOUBLE=262
	,LONG=263
	,SHORT=264
	,SIGNED=265
	,UNSIGNED=266
	,STRUCT=267
	,RETURN=268
	,MAIN=269
	,VOID=270
	,WHILE=271
	,FOR=272
	,DO=273
	,BREAK=274
	,ENDIF=275
	,PRINTF=276
	,CONTINUE=277
	,identifier=278
	,array_identifier=279
	,func_identifier=280
	,integer_constant=281
	,string_constant=282
	,float_constant=283
	,character_constant=284
	,ELSE=285
	,leftshift_assignment_operator=286
	,rightshift_assignment_operator=287
	,XOR_assignment_operator=288
	,OR_assignment_operator=289
	,AND_assignment_operator=290
	,modulo_assignment_operator=291
	,multiplication_assignment_operator=292
	,division_assignment_operator=293
	,addition_assignment_operator=294
	,subtraction_assignment_operator=295
	,assignment_operator=296
	,OR_operator=297
	,AND_operator=298
	,pipe_operator=299
	,caret_operator=300
	,amp_operator=301
	,equality_operator=302
	,inequality_operator=303
	,lessthan_assignment_operator=304
	,lessthan_operator=305
	,greaterthan_assignment_operator=306
	,greaterthan_operator=307
	,leftshift_operator=308
	,rightshift_operator=309
	,add_operator=310
	,subtract_operator=311
	,multiplication_operator=312
	,division_operator=313
	,modulo_operator=314
	,SIZEOF=315
	,tilde_operator=316
	,exclamation_operator=317
	,increment_operator=318
	,decrement_operator=319


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::IF=258;
const int YY_parse_CLASS::INT=259;
const int YY_parse_CLASS::CHAR=260;
const int YY_parse_CLASS::FLOAT=261;
const int YY_parse_CLASS::DOUBLE=262;
const int YY_parse_CLASS::LONG=263;
const int YY_parse_CLASS::SHORT=264;
const int YY_parse_CLASS::SIGNED=265;
const int YY_parse_CLASS::UNSIGNED=266;
const int YY_parse_CLASS::STRUCT=267;
const int YY_parse_CLASS::RETURN=268;
const int YY_parse_CLASS::MAIN=269;
const int YY_parse_CLASS::VOID=270;
const int YY_parse_CLASS::WHILE=271;
const int YY_parse_CLASS::FOR=272;
const int YY_parse_CLASS::DO=273;
const int YY_parse_CLASS::BREAK=274;
const int YY_parse_CLASS::ENDIF=275;
const int YY_parse_CLASS::PRINTF=276;
const int YY_parse_CLASS::CONTINUE=277;
const int YY_parse_CLASS::identifier=278;
const int YY_parse_CLASS::array_identifier=279;
const int YY_parse_CLASS::func_identifier=280;
const int YY_parse_CLASS::integer_constant=281;
const int YY_parse_CLASS::string_constant=282;
const int YY_parse_CLASS::float_constant=283;
const int YY_parse_CLASS::character_constant=284;
const int YY_parse_CLASS::ELSE=285;
const int YY_parse_CLASS::leftshift_assignment_operator=286;
const int YY_parse_CLASS::rightshift_assignment_operator=287;
const int YY_parse_CLASS::XOR_assignment_operator=288;
const int YY_parse_CLASS::OR_assignment_operator=289;
const int YY_parse_CLASS::AND_assignment_operator=290;
const int YY_parse_CLASS::modulo_assignment_operator=291;
const int YY_parse_CLASS::multiplication_assignment_operator=292;
const int YY_parse_CLASS::division_assignment_operator=293;
const int YY_parse_CLASS::addition_assignment_operator=294;
const int YY_parse_CLASS::subtraction_assignment_operator=295;
const int YY_parse_CLASS::assignment_operator=296;
const int YY_parse_CLASS::OR_operator=297;
const int YY_parse_CLASS::AND_operator=298;
const int YY_parse_CLASS::pipe_operator=299;
const int YY_parse_CLASS::caret_operator=300;
const int YY_parse_CLASS::amp_operator=301;
const int YY_parse_CLASS::equality_operator=302;
const int YY_parse_CLASS::inequality_operator=303;
const int YY_parse_CLASS::lessthan_assignment_operator=304;
const int YY_parse_CLASS::lessthan_operator=305;
const int YY_parse_CLASS::greaterthan_assignment_operator=306;
const int YY_parse_CLASS::greaterthan_operator=307;
const int YY_parse_CLASS::leftshift_operator=308;
const int YY_parse_CLASS::rightshift_operator=309;
const int YY_parse_CLASS::add_operator=310;
const int YY_parse_CLASS::subtract_operator=311;
const int YY_parse_CLASS::multiplication_operator=312;
const int YY_parse_CLASS::division_operator=313;
const int YY_parse_CLASS::modulo_operator=314;
const int YY_parse_CLASS::SIZEOF=315;
const int YY_parse_CLASS::tilde_operator=316;
const int YY_parse_CLASS::exclamation_operator=317;
const int YY_parse_CLASS::increment_operator=318;
const int YY_parse_CLASS::decrement_operator=319;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		306
#define	YYFLAG		-32768
#define	YYNTBASE	73

#define YYTRANSLATE(x) ((unsigned)(x) <= 319 ? yytranslate[x] : 168)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,    71,
    72,     2,     2,    66,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    65,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    67,     2,    68,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    69,     2,    70,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54,    55,
    56,    57,    58,    59,    60,    61,    62,    63,    64
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     5,     7,     8,    10,    12,    16,    20,    22,
    23,    27,    28,    32,    34,    36,    39,    40,    45,    53,
    55,    57,    59,    61,    64,    70,    76,    81,    85,    88,
    90,    92,    96,    99,   102,   104,   106,   107,   112,   117,
   122,   128,   132,   134,   140,   144,   146,   148,   152,   154,
   156,   158,   160,   162,   165,   168,   171,   174,   176,   178,
   181,   184,   185,   187,   190,   193,   194,   196,   197,   199,
   200,   203,   207,   208,   209,   215,   217,   218,   219,   223,
   226,   229,   230,   231,   235,   238,   239,   241,   243,   245,
   247,   249,   251,   253,   255,   257,   258,   263,   266,   267,
   270,   272,   273,   274,   283,   286,   287,   288,   289,   297,
   298,   299,   311,   312,   313,   323,   326,   330,   337,   341,
   345,   346,   349,   352,   355,   360,   365,   368,   371,   374,
   377,   378,   381,   382,   383,   388,   389,   394,   395,   400,
   401,   406,   407,   412,   413,   418,   421,   424,   426,   427,
   432,   434,   435,   440,   442,   443,   447,   449,   453,   455,
   457,   459,   461,   463,   465,   467,   471,   473,   475,   477,
   481,   483,   485,   487,   489,   491,   493,   495,   497,   501,
   503,   505,   506,   512,   514,   515,   519,   521,   523,   525,
   527,   529,   531,   533,   535,   537
};

static const short yyrhs[] = {    74,
     0,    76,    75,     0,    74,     0,     0,    77,     0,   100,
     0,    95,    78,    65,     0,    78,    66,    79,     0,    79,
     0,     0,    23,    80,    82,     0,     0,    24,    81,    82,
     0,    85,     0,    86,     0,    41,   140,     0,     0,    24,
    67,    84,    68,     0,    24,    67,    84,    68,    67,    84,
    68,     0,    26,     0,    23,     0,    83,     0,   140,     0,
    67,    89,     0,    67,    26,    68,    67,    87,     0,    67,
    23,    68,    67,    87,     0,    67,    68,    67,    87,     0,
    88,    68,    91,     0,    88,    68,     0,    26,     0,    23,
     0,    26,    68,    90,     0,    68,    90,     0,    68,   134,
     0,   134,     0,   135,     0,     0,    41,    69,    92,    70,
     0,    41,    69,    93,    70,     0,    41,    69,    94,    70,
     0,    69,   136,    70,    66,    92,     0,    69,   136,    70,
     0,    26,     0,    69,   137,    70,    66,    93,     0,    69,
   137,    70,     0,    26,     0,    28,     0,    27,    66,    94,
     0,    27,     0,     4,     0,     5,     0,     6,     0,     7,
     0,     8,    98,     0,     9,    99,     0,    11,    96,     0,
    10,    97,     0,    15,     0,     4,     0,     8,    98,     0,
     9,    99,     0,     0,     4,     0,     8,    98,     0,     9,
    99,     0,     0,     4,     0,     0,     4,     0,     0,   101,
   102,     0,    95,    23,    71,     0,     0,     0,   103,   105,
    72,   104,   113,     0,   106,     0,     0,     0,    95,   107,
   108,     0,   110,   109,     0,    66,   106,     0,     0,     0,
    23,   111,   112,     0,    67,    68,     0,     0,   117,     0,
   114,     0,   118,     0,   122,     0,   129,     0,   132,     0,
   133,     0,   130,     0,    77,     0,     0,   115,    69,   116,
    70,     0,   113,   116,     0,     0,   140,    65,     0,    65,
     0,     0,     0,     3,    71,   147,    72,   119,   113,   120,
   121,     0,    30,   113,     0,     0,     0,     0,    16,    71,
   123,   147,    72,   124,   113,     0,     0,     0,    17,    71,
   140,    65,   125,   147,    65,   126,   140,    72,   113,     0,
     0,     0,   127,    18,   113,    16,    71,   147,    72,   128,
    65,     0,    13,    65,     0,    13,   140,    65,     0,    21,
    71,    27,   131,    72,    65,     0,    66,    23,   131,     0,
    66,    83,   131,     0,     0,    22,    65,     0,    19,    65,
     0,    41,    27,     0,    41,    69,   136,    70,     0,    41,
    69,   137,    70,     0,    26,   138,     0,    28,   139,     0,
    26,   139,     0,    66,   136,     0,     0,    66,   137,     0,
     0,     0,   160,    41,   141,   140,     0,     0,   160,    39,
   142,   140,     0,     0,   160,    40,   143,   140,     0,     0,
   160,    37,   144,   140,     0,     0,   160,    38,   145,   140,
     0,     0,   160,    36,   146,   140,     0,   160,    63,     0,
   160,    64,     0,   147,     0,     0,   147,    42,   149,   148,
     0,   149,     0,     0,   149,    43,   150,   151,     0,   151,
     0,     0,    62,   152,   151,     0,   153,     0,   153,   154,
   155,     0,   155,     0,    51,     0,    49,     0,    52,     0,
    50,     0,    47,     0,    48,     0,   155,   156,   157,     0,
   157,     0,    55,     0,    56,     0,   157,   158,   159,     0,
   159,     0,    57,     0,    58,     0,    59,     0,   161,     0,
   160,     0,    23,     0,    83,     0,    71,   140,    72,     0,
   162,     0,   167,     0,     0,    23,    71,   163,   164,    72,
     0,   165,     0,     0,   165,    66,   166,     0,   166,     0,
    23,     0,    26,     0,    27,     0,    28,     0,    29,     0,
    26,     0,    27,     0,    28,     0,    29,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
   106,   109,   112,   113,   116,   117,   120,   123,   123,   126,
   127,   127,   127,   131,   132,   133,   134,   137,   138,   141,
   142,   143,   144,   147,   150,   151,   152,   155,   156,   159,
   160,   163,   164,   165,   168,   169,   170,   173,   174,   175,
   178,   179,   180,   183,   184,   185,   186,   189,   190,   193,
   193,   193,   193,   194,   195,   196,   197,   198,   201,   201,
   201,   201,   204,   204,   204,   204,   207,   207,   210,   210,
   213,   216,   219,   219,   219,   222,   222,   225,   225,   228,
   231,   232,   235,   235,   238,   239,   242,   243,   244,   245,
   246,   247,   248,   249,   250,   253,   253,   256,   257,   260,
   261,   264,   264,   264,   267,   268,   271,   271,   271,   272,
   272,   272,   273,   273,   273,   275,   276,   289,   292,   293,
   294,   297,   300,   303,   306,   307,   310,   313,   314,   317,
   318,   321,   322,   325,   325,   334,   334,   341,   341,   348,
   348,   355,   355,   361,   361,   368,   369,   370,   374,   374,
   375,   378,   378,   379,   383,   383,   384,   387,   388,   391,
   391,   391,   391,   391,   391,   394,   395,   398,   399,   402,
   403,   406,   406,   406,   409,   410,   413,   426,   434,   435,
   436,   439,   453,   466,   466,   469,   470,   472,   472,   472,
   472,   472,   475,   476,   477,   478
};

static const char * const yytname[] = {   "$","error","$illegal.","IF","INT",
"CHAR","FLOAT","DOUBLE","LONG","SHORT","SIGNED","UNSIGNED","STRUCT","RETURN",
"MAIN","VOID","WHILE","FOR","DO","BREAK","ENDIF","PRINTF","CONTINUE","identifier",
"array_identifier","func_identifier","integer_constant","string_constant","float_constant",
"character_constant","ELSE","leftshift_assignment_operator","rightshift_assignment_operator",
"XOR_assignment_operator","OR_assignment_operator","AND_assignment_operator",
"modulo_assignment_operator","multiplication_assignment_operator","division_assignment_operator",
"addition_assignment_operator","subtraction_assignment_operator","assignment_operator",
"OR_operator","AND_operator","pipe_operator","caret_operator","amp_operator",
"equality_operator","inequality_operator","lessthan_assignment_operator","lessthan_operator",
"greaterthan_assignment_operator","greaterthan_operator","leftshift_operator",
"rightshift_operator","add_operator","subtract_operator","multiplication_operator",
"division_operator","modulo_operator","SIZEOF","tilde_operator","exclamation_operator",
"increment_operator","decrement_operator","';'","','","'['","']'","'{'","'}'",
"'('","')'","program","declaration_list","D","declaration","variable_declaration",
"variable_declaration_list","variable_declaration_identifier","@1","@2","vdi",
"array_random_access","array_random_access_breakup","identifier_array_type",
"identifier_twod_array_type","initialization_params_new","initialization_params_2d",
"initialization_params","initialization","initialization_2d","array_init_int_2d",
"array_init_float_2d","array_init_string_2d","type_specifier","unsigned_grammar",
"signed_grammar","long_grammar","short_grammar","function_declaration","function_declaration_type",
"function_declaration_param_statement","@3","@4","params","parameters_list",
"@5","parameters_identifier_list","parameters_identifier_list_breakup","param_identifier",
"@6","param_identifier_breakup","statement","compound_statement","@7","statment_list",
"expression_statment","conditional_statements","@8","@9","conditional_statements_breakup",
"iterative_statements","@10","@11","@12","@13","@14","@15","return_statement",
"printf_statement","printf_identifier_list","continue_statement","break_statement",
"string_initialization","array_initialization","array_int_declarations","array_float_declarations",
"array_int_declarations_breakup","array_float_declarations_breakup","expression",
"@16","@17","@18","@19","@20","@21","simple_expression","@22","and_expression",
"@23","unary_relation_expression","@24","regular_expression","relational_operators",
"sum_expression","sum_operators","term","MULOP","factor","mutable","immutable",
"call","@25","arguments","arguments_list","exp","constant",""
};
#endif

static const short yyr1[] = {     0,
    73,    74,    75,    75,    76,    76,    77,    78,    78,    80,
    79,    81,    79,    82,    82,    82,    82,    83,    83,    84,
    84,    84,    84,    85,    86,    86,    86,    87,    87,    88,
    88,    89,    89,    89,    90,    90,    90,    91,    91,    91,
    92,    92,    92,    93,    93,    93,    93,    94,    94,    95,
    95,    95,    95,    95,    95,    95,    95,    95,    96,    96,
    96,    96,    97,    97,    97,    97,    98,    98,    99,    99,
   100,   101,   103,   104,   102,   105,   105,   107,   106,   108,
   109,   109,   111,   110,   112,   112,   113,   113,   113,   113,
   113,   113,   113,   113,   113,   115,   114,   116,   116,   117,
   117,   119,   120,   118,   121,   121,   123,   124,   122,   125,
   126,   122,   127,   128,   122,   129,   129,   130,   131,   131,
   131,   132,   133,   134,   135,   135,   136,   137,   137,   138,
   138,   139,   139,   141,   140,   142,   140,   143,   140,   144,
   140,   145,   140,   146,   140,   140,   140,   140,   148,   147,
   147,   150,   149,   149,   152,   151,   151,   153,   153,   154,
   154,   154,   154,   154,   154,   155,   155,   156,   156,   157,
   157,   158,   158,   158,   159,   159,   160,   160,   161,   161,
   161,   163,   162,   164,   164,   165,   165,   166,   166,   166,
   166,   166,   167,   167,   167,   167
};

static const short yyr2[] = {     0,
     1,     2,     1,     0,     1,     1,     3,     3,     1,     0,
     3,     0,     3,     1,     1,     2,     0,     4,     7,     1,
     1,     1,     1,     2,     5,     5,     4,     3,     2,     1,
     1,     3,     2,     2,     1,     1,     0,     4,     4,     4,
     5,     3,     1,     5,     3,     1,     1,     3,     1,     1,
     1,     1,     1,     2,     2,     2,     2,     1,     1,     2,
     2,     0,     1,     2,     2,     0,     1,     0,     1,     0,
     2,     3,     0,     0,     5,     1,     0,     0,     3,     2,
     2,     0,     0,     3,     2,     0,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     0,     4,     2,     0,     2,
     1,     0,     0,     8,     2,     0,     0,     0,     7,     0,
     0,    11,     0,     0,     9,     2,     3,     6,     3,     3,
     0,     2,     2,     2,     4,     4,     2,     2,     2,     2,
     0,     2,     0,     0,     4,     0,     4,     0,     4,     0,
     4,     0,     4,     0,     4,     2,     2,     1,     0,     4,
     1,     0,     4,     1,     0,     3,     1,     3,     1,     1,
     1,     1,     1,     1,     1,     3,     1,     1,     1,     3,
     1,     1,     1,     1,     1,     1,     1,     1,     3,     1,
     1,     0,     5,     1,     0,     3,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     1
};

static const short yydefact[] = {     0,
    50,    51,    52,    53,    68,    70,    66,    62,    58,     1,
     4,     5,     0,     6,    73,    67,    54,    69,    55,    63,
    68,    70,    57,    59,    68,    70,    56,     3,     2,    10,
    12,     0,     9,    71,    77,    64,    65,    60,    61,    72,
    17,    17,     7,     0,    78,     0,    76,     0,     0,    11,
    14,    15,    13,    10,     8,     0,    74,   177,     0,   193,
   194,   195,   196,   155,     0,   178,    16,   148,   151,   154,
   157,   159,   167,   171,   176,   175,   180,   181,     0,     0,
    37,    24,    83,    79,    82,    96,   182,     0,     0,     0,
     0,   152,   164,   165,   161,   163,   160,   162,     0,   168,
   169,     0,   172,   173,   174,     0,   144,   140,   142,   136,
   138,   134,   146,   147,     0,    37,     0,     0,    33,    34,
    36,    86,     0,    80,     0,     0,     0,     0,     0,     0,
     0,   101,    95,     0,    75,    88,     0,    87,    89,    90,
     0,    91,    94,    92,    93,     0,   185,   177,   193,   178,
     0,    23,   156,   176,   179,   149,     0,   158,   166,   170,
     0,     0,     0,     0,     0,     0,     0,     0,    32,    35,
   124,     0,    31,    30,    27,     0,     0,    84,    81,     0,
   116,     0,   107,     0,   123,     0,   122,    96,    96,   100,
   188,   189,   190,   191,   192,     0,   184,   187,    18,   150,
   153,   145,   141,   143,   137,   139,   135,    26,    25,   131,
   133,     0,     0,    29,    85,     0,   117,     0,     0,   121,
    96,     0,     0,   183,     0,     0,     0,   127,   129,     0,
   128,   125,   126,     0,    28,   102,     0,   110,     0,     0,
    98,    97,     0,   186,     0,   130,   132,   133,     0,    96,
   108,     0,   121,   121,     0,     0,    19,    43,    49,    47,
     0,     0,     0,     0,   103,    96,     0,   119,   120,   118,
     0,     0,     0,     0,    38,    39,    40,   106,   109,   111,
   114,    48,    42,    45,    96,   104,     0,     0,     0,     0,
   105,     0,   115,    43,     0,    41,    46,     0,    44,    96,
   131,   112,     0,     0,     0,     0
};

static const short yydefgoto[] = {   304,
    10,    29,    11,   133,    32,    33,    41,    42,    50,    66,
   151,    51,    52,   175,   176,    82,   119,   235,   262,   263,
   264,   134,    27,    23,    17,    19,    14,    15,    34,    35,
    86,    46,    47,    56,    84,   124,    85,   122,   178,   221,
   136,   137,   222,   138,   139,   250,   278,   286,   140,   218,
   266,   252,   287,   141,   288,   142,   143,   240,   144,   145,
   120,   121,   246,   247,   228,   229,   146,   166,   164,   165,
   162,   163,   161,    68,   200,    69,   157,    70,    89,    71,
    99,    72,   102,    73,   106,    74,    75,    76,    77,   147,
   196,   197,   198,    78
};

static const short yypact[] = {   116,
-32768,-32768,-32768,-32768,    31,    37,   131,   145,-32768,-32768,
   116,-32768,   114,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
    31,    37,-32768,-32768,    31,    37,-32768,-32768,-32768,    -9,
-32768,   102,-32768,-32768,   116,-32768,-32768,-32768,-32768,-32768,
    -3,    -3,-32768,   148,-32768,     0,-32768,     5,    13,-32768,
-32768,-32768,-32768,-32768,-32768,    80,-32768,    41,    23,-32768,
-32768,-32768,-32768,-32768,     5,-32768,-32768,    77,    98,-32768,
    96,   118,    93,-32768,    70,-32768,-32768,-32768,    89,    94,
    34,-32768,-32768,-32768,   103,   249,-32768,    21,     5,    92,
     5,-32768,-32768,-32768,-32768,-32768,-32768,-32768,    28,-32768,
-32768,    28,-32768,-32768,-32768,    28,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,   110,    38,    -4,    74,-32768,-32768,
-32768,   115,   116,-32768,   121,    -2,   123,   134,   147,   142,
   149,-32768,-32768,   148,-32768,-32768,   150,-32768,-32768,-32768,
   198,-32768,-32768,-32768,-32768,   153,    59,    88,   154,   155,
   156,-32768,-32768,-32768,-32768,    98,     5,   118,    93,-32768,
     5,     5,     5,     5,     5,     5,    74,    74,-32768,-32768,
-32768,   132,-32768,-32768,-32768,   157,   158,-32768,-32768,     5,
-32768,   162,-32768,     5,-32768,   190,-32768,   180,   249,-32768,
-32768,-32768,-32768,-32768,-32768,   159,   163,-32768,   161,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,   164,
   166,   151,   165,   179,-32768,     1,-32768,     5,   168,   170,
   180,   167,   218,-32768,    59,    21,   132,-32768,-32768,   135,
-32768,-32768,-32768,   169,-32768,-32768,    24,-32768,   152,   171,
-32768,-32768,   173,-32768,   172,-32768,-32768,   166,   -16,   249,
-32768,     5,   170,   170,   176,     5,-32768,-32768,   181,-32768,
   132,   178,   191,   193,-32768,   249,   -28,-32768,-32768,-32768,
    26,   219,   199,   204,-32768,-32768,-32768,   250,-32768,-32768,
-32768,-32768,   183,   213,   249,-32768,     5,   216,   -11,    33,
-32768,   210,-32768,-32768,   257,-32768,-32768,   135,-32768,   249,
   220,-32768,   257,   284,   285,-32768
};

static const short yypgoto[] = {-32768,
   276,-32768,-32768,    19,-32768,   244,-32768,-32768,   247,   -84,
    64,-32768,-32768,    12,-32768,-32768,   175,-32768,     3,     4,
    25,     7,-32768,-32768,    49,    67,-32768,-32768,-32768,-32768,
-32768,-32768,   177,-32768,-32768,-32768,-32768,-32768,-32768,   -85,
-32768,-32768,    72,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,   -43,-32768,-32768,
   182,-32768,  -166,  -170,-32768,    84,   -48,-32768,-32768,-32768,
-32768,-32768,-32768,  -172,-32768,   205,-32768,   -80,-32768,-32768,
-32768,   200,-32768,   201,-32768,   195,   -86,-32768,-32768,-32768,
-32768,-32768,    79,-32768
};


#define	YYLAST		320


static const short yytable[] = {    67,
   135,   213,   154,   150,   154,   212,    13,   216,   153,   258,
   259,   260,   154,    91,   294,   154,    90,    13,    12,   154,
    58,    59,   171,    60,    61,    62,    63,    58,    59,    12,
    60,    61,    62,    63,    16,    79,   280,    48,    80,   152,
    18,    45,    91,   148,    59,   237,   149,    61,    62,    63,
    58,    59,   261,    60,    61,    62,    63,   295,   297,    64,
   260,    40,   181,    49,   172,    91,    64,    91,    65,    36,
   154,    57,   236,    38,   117,    65,   201,   182,   117,   267,
    81,   191,    64,   271,   192,   193,   194,   195,    37,    88,
   274,    65,    39,   154,   273,   251,   173,   281,    65,   174,
   118,   298,    83,   223,   168,   107,   108,   109,   110,   111,
   112,    87,   202,   203,   204,   205,   206,   207,    91,     1,
     2,     3,     4,     5,     6,     7,     8,   274,   273,    45,
     9,   154,   113,   114,    20,   219,    30,    31,    21,    22,
    92,   150,    93,    94,    95,    96,    97,    98,    24,   103,
   104,   105,    25,    26,   254,   -21,   115,   210,    87,   211,
   248,   116,   211,   155,   265,   154,    43,    44,   123,   154,
    54,    31,   100,   101,   253,    59,   167,   152,   208,   209,
   279,   177,   125,     1,     2,     3,     4,     5,     6,     7,
     8,   180,   126,   183,     9,   127,   128,  -113,   129,   291,
   130,   131,    58,    59,   184,    60,    61,    62,    63,   268,
   269,   185,   186,   187,   302,   189,   220,   190,   188,   234,
   232,   -20,   -22,   199,   214,   215,   217,   226,   225,   227,
   224,   230,   238,   243,   233,   239,   242,   249,   292,   257,
   270,    64,   255,   256,   132,   259,   272,   275,   289,   -99,
    65,   125,     1,     2,     3,     4,     5,     6,     7,     8,
   276,   126,   277,     9,   127,   128,  -113,   129,   283,   130,
   131,    58,    59,   284,    60,    61,    62,    63,   290,   285,
   293,   300,   301,   305,   306,   303,    28,    55,    53,   245,
   169,   296,   241,   299,   231,   156,   282,   170,   158,   179,
   160,     0,   159,   244,     0,     0,     0,     0,     0,     0,
    64,     0,     0,   132,     0,     0,     0,     0,     0,    65
};

static const short yycheck[] = {    48,
    86,   172,    89,    88,    91,   172,     0,   180,    89,    26,
    27,    28,    99,    42,    26,   102,    65,    11,     0,   106,
    23,    24,    27,    26,    27,    28,    29,    23,    24,    11,
    26,    27,    28,    29,     4,    23,    65,    41,    26,    88,
     4,    35,    42,    23,    24,   218,    26,    27,    28,    29,
    23,    24,    69,    26,    27,    28,    29,    69,    26,    62,
    28,    71,    65,    67,    69,    42,    62,    42,    71,    21,
   157,    72,    72,    25,    41,    71,   157,   126,    41,   252,
    68,    23,    62,   256,    26,    27,    28,    29,    22,    67,
   261,    71,    26,   180,   261,    72,    23,    72,    71,    26,
    67,    69,    23,   189,    67,    36,    37,    38,    39,    40,
    41,    71,   161,   162,   163,   164,   165,   166,    42,     4,
     5,     6,     7,     8,     9,    10,    11,   298,   295,   123,
    15,   218,    63,    64,     4,   184,    23,    24,     8,     9,
    43,   226,    47,    48,    49,    50,    51,    52,     4,    57,
    58,    59,     8,     9,   239,    68,    68,    26,    71,    28,
    26,    68,    28,    72,   250,   252,    65,    66,    66,   256,
    23,    24,    55,    56,    23,    24,    67,   226,   167,   168,
   266,    67,     3,     4,     5,     6,     7,     8,     9,    10,
    11,    71,    13,    71,    15,    16,    17,    18,    19,   285,
    21,    22,    23,    24,    71,    26,    27,    28,    29,   253,
   254,    65,    71,    65,   300,    18,    27,    65,    69,    41,
    70,    68,    68,    68,    68,    68,    65,    67,    66,    66,
    72,    66,    65,    16,    70,    66,    70,    69,   287,    68,
    65,    62,    72,    71,    65,    27,    66,    70,    66,    70,
    71,     3,     4,     5,     6,     7,     8,     9,    10,    11,
    70,    13,    70,    15,    16,    17,    18,    19,    70,    21,
    22,    23,    24,    70,    26,    27,    28,    29,    66,    30,
    65,    72,    26,     0,     0,    66,    11,    44,    42,   226,
   116,   289,   221,   290,   211,    91,   272,   116,    99,   123,
   106,    -1,   102,   225,    -1,    -1,    -1,    -1,    -1,    -1,
    62,    -1,    -1,    65,    -1,    -1,    -1,    -1,    -1,    71
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 10:
#line 126 "parser.y"
{if(duplicate(curid)){printf("Duplicate\n");exit(0);}insertSTnest(curid,currnest); ins();  ;
    break;}
case 12:
#line 127 "parser.y"
{if(duplicate(curid)){printf("Duplicate\n");exit(0);}insertSTnest(curid,currnest); ins();  ;
    break;}
case 32:
#line 163 "parser.y"
{if(yyval < 1) {printf("Wrong array size\n"); exit(0);} ;
    break;}
case 72:
#line 216 "parser.y"
{ strcpy(currfunctype, curtype); strcpy(currfunc, curid); check_duplicate(curid); insertSTF(curid); ins(); ;
    break;}
case 73:
#line 219 "parser.y"
{params_count=0;;
    break;}
case 74:
#line 219 "parser.y"
{funcgen();;
    break;}
case 75:
#line 219 "parser.y"
{funcgenend();;
    break;}
case 76:
#line 222 "parser.y"
{ insertSTparamscount(currfunc, params_count); ;
    break;}
case 77:
#line 222 "parser.y"
{ insertSTparamscount(currfunc, params_count); ;
    break;}
case 78:
#line 225 "parser.y"
{ check_params(curtype);;
    break;}
case 83:
#line 235 "parser.y"
{ ins();insertSTnest(curid,1); params_count++; ;
    break;}
case 96:
#line 253 "parser.y"
{currnest++;;
    break;}
case 97:
#line 253 "parser.y"
{deletedata(currnest);currnest--;;
    break;}
case 102:
#line 264 "parser.y"
{label1();if(yyvsp[-1]!=1){printf("Condition checking is not of type int\n");exit(0);};
    break;}
case 103:
#line 264 "parser.y"
{label2();;
    break;}
case 105:
#line 267 "parser.y"
{label3();;
    break;}
case 106:
#line 268 "parser.y"
{label3();;
    break;}
case 107:
#line 271 "parser.y"
{label4();;
    break;}
case 108:
#line 271 "parser.y"
{label1();if(yyvsp[-1]!=1){printf("Condition checking is not of type int\n");exit(0);};
    break;}
case 109:
#line 271 "parser.y"
{label5();;
    break;}
case 110:
#line 272 "parser.y"
{label4();;
    break;}
case 111:
#line 272 "parser.y"
{label1();if(yyvsp[-1]!=1){printf("Condition checking is not of type int\n");exit(0);};
    break;}
case 112:
#line 272 "parser.y"
{label5();;
    break;}
case 113:
#line 273 "parser.y"
{label4();;
    break;}
case 114:
#line 273 "parser.y"
{label1();label5();if(yyvsp[-1]!=1){printf("Condition checking is not of type int\n");exit(0);};
    break;}
case 116:
#line 275 "parser.y"
{if(strcmp(currfunctype,"void")) {printf("Returning void of a non-void function\n"); exit(0);};
    break;}
case 117:
#line 276 "parser.y"
{ 	if(!strcmp(currfunctype, "void"))
										{ 
											yyerror("Function is void");
										}

										if((currfunctype[0]=='i' || currfunctype[0]=='c') && yyvsp[-1]!=1)
										{
											printf("Expression doesn't match return type of function\n"); exit(0);
										}

									;
    break;}
case 118:
#line 289 "parser.y"
{print();;
    break;}
case 124:
#line 303 "parser.y"
{insV();;
    break;}
case 134:
#line 325 "parser.y"
{push("=");;
    break;}
case 135:
#line 325 "parser.y"
{   
																	  if(yyvsp[-3]==1 && yyvsp[0]==1) 
																	  {
			                                                          yyval=1;
			                                                          } 
			                                                          else 
			                                                          {yyval=-1; printf("Type mismatch\n"); exit(0);} 
			                                                          codeassign();
			                                                       ;
    break;}
case 136:
#line 334 "parser.y"
{push("+=");;
    break;}
case 137:
#line 334 "parser.y"
{  
																	  if(yyvsp[-3]==1 && yyvsp[0]==1) 
			                                                          yyval=1; 
			                                                          else 
			                                                          {yyval=-1; printf("Type mismatch\n"); exit(0);} 
			                                                          codeassign();
			                                                       ;
    break;}
case 138:
#line 341 "parser.y"
{push("-=");;
    break;}
case 139:
#line 341 "parser.y"
{	  
																	  if(yyvsp[-3]==1 && yyvsp[0]==1) 
			                                                          yyval=1; 
			                                                          else 
			                                                          {yyval=-1; printf("Type mismatch\n"); exit(0);} 
			                                                          codeassign();
			                                                       ;
    break;}
case 140:
#line 348 "parser.y"
{push("*=");;
    break;}
case 141:
#line 348 "parser.y"
{
																	  if(yyvsp[-3]==1 && yyvsp[0]==1) 
			                                                          yyval=1; 
			                                                          else 
			                                                          {yyval=-1; printf("Type mismatch\n"); exit(0);}
			                                                          codeassign(); 
			                                                       ;
    break;}
case 142:
#line 355 "parser.y"
{push("/=");;
    break;}
case 143:
#line 355 "parser.y"
{ 
																	  if(yyvsp[-3]==1 && yyvsp[0]==1) 
			                                                          yyval=1; 
			                                                          else 
			                                                          {yyval=-1; printf("Type mismatch\n"); exit(0);} 
			                                                       ;
    break;}
case 144:
#line 361 "parser.y"
{push("%=");;
    break;}
case 145:
#line 361 "parser.y"
{ 
																	  if(yyvsp[-3]==1 && yyvsp[-1]==1) 
			                                                          yyval=1; 
			                                                          else 
			                                                          {yyval=-1; printf("Type mismatch\n"); exit(0);} 
			                                                          codeassign();
																	;
    break;}
case 146:
#line 368 "parser.y"
{ push("++");if(yyvsp[-1] == 1) yyval=1; else yyval=-1; genunary();;
    break;}
case 147:
#line 369 "parser.y"
{push("--");if(yyvsp[-1] == 1) yyval=1; else yyval=-1;;
    break;}
case 148:
#line 370 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 149:
#line 374 "parser.y"
{push("||");;
    break;}
case 150:
#line 374 "parser.y"
{if(yyvsp[-3] == 1 && yyvsp[-1]==1) yyval=1; else yyval=-1; codegen();;
    break;}
case 151:
#line 375 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 152:
#line 378 "parser.y"
{push("&&");;
    break;}
case 153:
#line 378 "parser.y"
{if(yyvsp[-3] == 1 && yyvsp[-1]==1) yyval=1; else yyval=-1; codegen();;
    break;}
case 154:
#line 379 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 155:
#line 383 "parser.y"
{push("!");;
    break;}
case 156:
#line 383 "parser.y"
{if(yyvsp[-1]==1) yyval=1; else yyval=-1; codegen();;
    break;}
case 157:
#line 384 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 158:
#line 387 "parser.y"
{if(yyvsp[-2] == 1 && yyvsp[0]==1) yyval=1; else yyval=-1; codegen();;
    break;}
case 159:
#line 388 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 160:
#line 391 "parser.y"
{push(">=");;
    break;}
case 161:
#line 391 "parser.y"
{push("<=");;
    break;}
case 162:
#line 391 "parser.y"
{push(">");;
    break;}
case 163:
#line 391 "parser.y"
{push("<");;
    break;}
case 164:
#line 391 "parser.y"
{push("==");;
    break;}
case 165:
#line 391 "parser.y"
{push("!=");;
    break;}
case 166:
#line 394 "parser.y"
{if(yyvsp[-2] == 1 && yyvsp[0]==1) yyval=1; else yyval=-1; codegen();;
    break;}
case 167:
#line 395 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 168:
#line 398 "parser.y"
{push("+");;
    break;}
case 169:
#line 399 "parser.y"
{push("-");;
    break;}
case 170:
#line 402 "parser.y"
{if(yyvsp[-2] == 1 && yyvsp[0]==1) yyval=1; else yyval=-1; codegen();;
    break;}
case 171:
#line 403 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 172:
#line 406 "parser.y"
{push("*");;
    break;}
case 173:
#line 406 "parser.y"
{push("/");;
    break;}
case 174:
#line 406 "parser.y"
{push("%");;
    break;}
case 175:
#line 409 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 176:
#line 410 "parser.y"
{if(yyvsp[0] == 1) yyval=1; else yyval=-1;;
    break;}
case 177:
#line 413 "parser.y"
{
						  push(curid);
						  if(check_id_is_func(curid))
						  {printf("Function name used as Identifier\n"); exit(8);}
			              if(!checkscope(curid))
			              {printf("%s\n",curid);printf("Undeclared\n");exit(0);} 
			              if(!checkarray(curid))
			              {printf("%s\n",curid);printf("Array ID has no subscript\n");exit(0);}
			              if(gettype(curid,0)=='i' || gettype(curid,1)== 'c')
			              yyval = 1;
			              else
			              yyval = -1;
			              ;
    break;}
case 178:
#line 426 "parser.y"
{if(!checkscope(curid)){printf("%s\n",curid);printf("Undeclared\n");exit(0);}
			                   	if(gettype(curid,0)=='i' || gettype(curid,1)== 'c')
			              		yyval = 1;
			              		else
			              		yyval = -1;
			              		;
    break;}
case 179:
#line 434 "parser.y"
{if(yyvsp[-1]==1) yyval=1; else yyval=-1;;
    break;}
case 180:
#line 435 "parser.y"
{if(yyvsp[0]==-1) yyval=-1; else yyval=1;;
    break;}
case 181:
#line 436 "parser.y"
{if(yyvsp[0]==1) yyval=1; else yyval=-1;;
    break;}
case 182:
#line 439 "parser.y"
{

			             if(!check_declaration(curid, "Function"))
			             { printf("Function not declared"); exit(0);} 
			             insertSTF(curid); 
						 strcpy(currfunccall,curid);
						 if(gettype(curid,0)=='i' || gettype(curid,1)== 'c')
						 {
			             yyval = 1;
			             }
			             else
			             yyval = -1;
                         call_params_count=0;
			             ;
    break;}
case 183:
#line 454 "parser.y"
{ if(strcmp(currfunccall,"printf"))
							{ 
								if(getSTparamscount(currfunccall)!=call_params_count)
								{	
									yyerror("Number of arguments in function call doesn't match number of parameters");
									exit(8);
								}
							}
							callgen();
						 ;
    break;}
case 186:
#line 469 "parser.y"
{ call_params_count++; ;
    break;}
case 187:
#line 470 "parser.y"
{ call_params_count++; ;
    break;}
case 188:
#line 472 "parser.y"
{arggen(1);;
    break;}
case 189:
#line 472 "parser.y"
{arggen(2);;
    break;}
case 190:
#line 472 "parser.y"
{arggen(3);;
    break;}
case 191:
#line 472 "parser.y"
{arggen(4);;
    break;}
case 192:
#line 472 "parser.y"
{arggen(5);;
    break;}
case 193:
#line 475 "parser.y"
{  insV(); codegencon(); yyval=1; ;
    break;}
case 194:
#line 476 "parser.y"
{  insV(); codegencon();yyval=-1;;
    break;}
case 195:
#line 477 "parser.y"
{  insV(); codegencon();;
    break;}
case 196:
#line 478 "parser.y"
{  insV(); codegencon();yyval=1; ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 480 "parser.y"


extern FILE *yyin;
extern int yylineno;
extern char *yytext;
void insertSTtype(char *,char *);
void insertSTvalue(char *, char *);
void incertCT(char *, char *);
void printST();
void printCT();

struct stack
{
	char value[100];
	int labelvalue;
}s[100],label[100];


void push(char *x)
{
	strcpy(s[++top].value,x);
}

void swap(char *x, char *y)
{
	char temp = *x;
	*x = *y;
	*y = temp;
}

void print()
{
	printf("Print Statement \n");
}

void reverse(char str[], int length) 
{ 
    int start = 0; 
    int end = length -1; 
    while (start < end) 
    { 
        swap((str+start), (str+end)); 
        start++; 
        end--; 
    } 
} 
  
char* itoa(int num, char* str, int base) 
{ 
    int i = 0; 
    int isNegative = 0; 
  
   
    if (num == 0) 
    { 
        str[i++] = '0'; 
        str[i] = '\0'; 
        return str; 
    } 
  
    if (num < 0 && base == 10) 
    { 
        isNegative = 1; 
        num = -num; 
    } 
  
   
    while (num != 0) 
    { 
        int rem = num % base; 
        str[i++] = (rem > 9)? (rem-10) + 'a' : rem + '0'; 
        num = num/base; 
    } 
  
    if (isNegative) 
        str[i++] = '-'; 
  
    str[i] = '\0'; 
  
   
    reverse(str, i); 
  
    return str; 
} 

void codegen()
{
	strcpy(temp,"t");
	char buffer[100];
	itoa(count,buffer,10);
	strcat(temp,buffer);
	printf("%s = %s %s %s\n",temp,s[top-2].value,s[top-1].value,s[top].value);
	top = top - 2;
	strcpy(s[top].value,temp);
	count++; 
}

void codegencon()
{
	strcpy(temp,"t");
	char buffer[100];
	itoa(count,buffer,10);
	strcat(temp,buffer);
	printf("%s = %s\n",temp,curval);
	push(temp);
	count++;
	
}

int isunary(char *s)
{
	if(strcmp(s, "--")==0 || strcmp(s, "++")==0)
	{
		return 1;
	}
	return 0;
}

void genunary()
{
	char temp1[100], temp2[100], temp3[100];
	strcpy(temp1, s[top].value);
	strcpy(temp2, s[top-1].value);

	if(isunary(temp1))
	{
		strcpy(temp3, temp1);
		strcpy(temp1, temp2);
		strcpy(temp2, temp3);
	}
	strcpy(temp, "t");
	char buffer[100];
	itoa(count, buffer, 10);
	strcat(temp, buffer);
	count++;

	if(strcmp(temp2,"--")==0)
	{
		printf("%s = %s - 1\n", temp, temp1);
		printf("%s = %s\n", temp1, temp);
	}

	if(strcmp(temp2,"++")==0)
	{
		printf("%s = %s + 1\n", temp, temp1);
		printf("%s = %s\n", temp1, temp);
	}

	top = top -2;
}

void codeassign()
{
	printf("%s = %s\n",s[top-2].value,s[top].value);
	top = top - 2;
}

void label1()
{
	strcpy(temp,"L");
	char buffer[100];
	itoa(lno,buffer,10);
	strcat(temp,buffer);
	printf("IF not %s GoTo %s\n",s[top].value,temp);
	label[++ltop].labelvalue = lno++;
}

void label2()
{
	strcpy(temp,"L");
	char buffer[100];
	itoa(lno,buffer,10);
	strcat(temp,buffer);
	printf("GoTo %s\n",temp);
	strcpy(temp,"L");
	itoa(label[ltop].labelvalue,buffer,10);
	strcat(temp,buffer);
	printf("%s:\n",temp);
	ltop--;
	label[++ltop].labelvalue=lno++;
}

void label3()
{
	strcpy(temp,"L");
	char buffer[100];
	itoa(label[ltop].labelvalue,buffer,10);
	strcat(temp,buffer);
	printf("%s:\n",temp);
	ltop--;
	
}

void label4()
{
	strcpy(temp,"L");
	char buffer[100];
	itoa(lno,buffer,10);
	strcat(temp,buffer);
	printf("%s:\n",temp);
	label[++ltop].labelvalue = lno++;
}


void label5()
{
	strcpy(temp,"L");
	char buffer[100];
	itoa(label[ltop-1].labelvalue,buffer,10);
	strcat(temp,buffer);
	printf("GoTo %s:\n",temp);
	strcpy(temp,"L");
	itoa(label[ltop].labelvalue,buffer,10);
	strcat(temp,buffer);
	printf("%s:\n",temp);
	ltop = ltop - 2;
    
   
}

void funcgen()
{
	printf("func begin %s\n",currfunc);
}

void funcgenend()
{
	printf("func end\n\n");
}

void arggen(int i)
{
    if(i==1)
    {
	printf("refparam %s\n", curid);
	}
	else
	{
	printf("refparam %s\n", curval);
	}
}

void callgen()
{
	printf("refparam result\n");
	push("result");
	printf("call %s, %d\n",currfunccall,call_params_count);
}



int main(int argc , char **argv)
{
	yyin = fopen(argv[1], "r");
	yyparse();

	if(flag == 0)
	{
		printf(ANSI_COLOR_GREEN "Status: Parsing Complete - Valid" ANSI_COLOR_RESET "\n");
		// printf("%30s" ANSI_COLOR_CYAN "SYMBOL TABLE" ANSI_COLOR_RESET "\n", " ");
		// printf("%30s %s\n", " ", "------------");
		// // printST();

		// printf("\n\n%30s" ANSI_COLOR_CYAN "CONSTANT TABLE" ANSI_COLOR_RESET "\n", " ");
		// printf("%30s %s\n", " ", "--------------");
		// printCT();
	}
}

void yyerror(char *s)
{
	printf(ANSI_COLOR_RED "%d %s %s\n", yylineno, s, yytext);
	flag=1;
	printf(ANSI_COLOR_RED "Status: Parsing Failed - Invalid\n" ANSI_COLOR_RESET);
	exit(7);
}

void ins()
{
	insertSTtype(curid,curtype);
}

void insV()
{
	insertSTvalue(curid,curval);
}

int yywrap()
{
	return 1;
}