#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from parser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "parser.y"

	void yyerror(char* s);
	int yylex();
	#include "ctype.h"
	#include "string.h"
	#include "stdio.h"
	#include "stdlib.h"
	void ins();
	void insV();
	int flag=0;

	#define ANSI_COLOR_RED		"\x1b[31m"
	#define ANSI_COLOR_GREEN	"\x1b[32m"
	#define ANSI_COLOR_CYAN		"\x1b[36m"
	#define ANSI_COLOR_RESET	"\x1b[0m"

	extern char curid[20];
	extern char curtype[20];
	extern char curval[20];


#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	IF	258
#define	INT	259
#define	CHAR	260
#define	FLOAT	261
#define	RETURN	262
#define	MAIN	263
#define	VOID	264
#define	WHILE	265
#define	FOR	266
#define	BREAK	267
#define	ENDIF	268
#define	CONTINUE	269
#define	identifier	270
#define	integer_constant	271
#define	string_constant	272
#define	float_constant	273
#define	character_constant	274
#define	ELSE	275
#define	leftshift_assignment_operator	276
#define	rightshift_assignment_operator	277
#define	XOR_assignment_operator	278
#define	OR_assignment_operator	279
#define	AND_assignment_operator	280
#define	modulo_assignment_operator	281
#define	multiplication_assignment_operator	282
#define	division_assignment_operator	283
#define	addition_assignment_operator	284
#define	subtraction_assignment_operator	285
#define	assignment_operator	286
#define	OR_operator	287
#define	AND_operator	288
#define	pipe_operator	289
#define	caret_operator	290
#define	amp_operator	291
#define	equality_operator	292
#define	inequality_operator	293
#define	lessthan_assignment_operator	294
#define	lessthan_operator	295
#define	greaterthan_assignment_operator	296
#define	greaterthan_operator	297
#define	leftshift_operator	298
#define	rightshift_operator	299
#define	add_operator	300
#define	subtract_operator	301
#define	multiplication_operator	302
#define	division_operator	303
#define	modulo_operator	304
#define	SIZEOF	305
#define	tilde_operator	306
#define	exclamation_operator	307
#define	increment_operator	308
#define	decrement_operator	309


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int IF;
static const int INT;
static const int CHAR;
static const int FLOAT;
static const int RETURN;
static const int MAIN;
static const int VOID;
static const int WHILE;
static const int FOR;
static const int BREAK;
static const int ENDIF;
static const int CONTINUE;
static const int identifier;
static const int integer_constant;
static const int string_constant;
static const int float_constant;
static const int character_constant;
static const int ELSE;
static const int leftshift_assignment_operator;
static const int rightshift_assignment_operator;
static const int XOR_assignment_operator;
static const int OR_assignment_operator;
static const int AND_assignment_operator;
static const int modulo_assignment_operator;
static const int multiplication_assignment_operator;
static const int division_assignment_operator;
static const int addition_assignment_operator;
static const int subtraction_assignment_operator;
static const int assignment_operator;
static const int OR_operator;
static const int AND_operator;
static const int pipe_operator;
static const int caret_operator;
static const int amp_operator;
static const int equality_operator;
static const int inequality_operator;
static const int lessthan_assignment_operator;
static const int lessthan_operator;
static const int greaterthan_assignment_operator;
static const int greaterthan_operator;
static const int leftshift_operator;
static const int rightshift_operator;
static const int add_operator;
static const int subtract_operator;
static const int multiplication_operator;
static const int division_operator;
static const int modulo_operator;
static const int SIZEOF;
static const int tilde_operator;
static const int exclamation_operator;
static const int increment_operator;
static const int decrement_operator;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,IF=258
	,INT=259
	,CHAR=260
	,FLOAT=261
	,RETURN=262
	,MAIN=263
	,VOID=264
	,WHILE=265
	,FOR=266
	,BREAK=267
	,ENDIF=268
	,CONTINUE=269
	,identifier=270
	,integer_constant=271
	,string_constant=272
	,float_constant=273
	,character_constant=274
	,ELSE=275
	,leftshift_assignment_operator=276
	,rightshift_assignment_operator=277
	,XOR_assignment_operator=278
	,OR_assignment_operator=279
	,AND_assignment_operator=280
	,modulo_assignment_operator=281
	,multiplication_assignment_operator=282
	,division_assignment_operator=283
	,addition_assignment_operator=284
	,subtraction_assignment_operator=285
	,assignment_operator=286
	,OR_operator=287
	,AND_operator=288
	,pipe_operator=289
	,caret_operator=290
	,amp_operator=291
	,equality_operator=292
	,inequality_operator=293
	,lessthan_assignment_operator=294
	,lessthan_operator=295
	,greaterthan_assignment_operator=296
	,greaterthan_operator=297
	,leftshift_operator=298
	,rightshift_operator=299
	,add_operator=300
	,subtract_operator=301
	,multiplication_operator=302
	,division_operator=303
	,modulo_operator=304
	,SIZEOF=305
	,tilde_operator=306
	,exclamation_operator=307
	,increment_operator=308
	,decrement_operator=309


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::IF=258;
const int YY_parse_CLASS::INT=259;
const int YY_parse_CLASS::CHAR=260;
const int YY_parse_CLASS::FLOAT=261;
const int YY_parse_CLASS::RETURN=262;
const int YY_parse_CLASS::MAIN=263;
const int YY_parse_CLASS::VOID=264;
const int YY_parse_CLASS::WHILE=265;
const int YY_parse_CLASS::FOR=266;
const int YY_parse_CLASS::BREAK=267;
const int YY_parse_CLASS::ENDIF=268;
const int YY_parse_CLASS::CONTINUE=269;
const int YY_parse_CLASS::identifier=270;
const int YY_parse_CLASS::integer_constant=271;
const int YY_parse_CLASS::string_constant=272;
const int YY_parse_CLASS::float_constant=273;
const int YY_parse_CLASS::character_constant=274;
const int YY_parse_CLASS::ELSE=275;
const int YY_parse_CLASS::leftshift_assignment_operator=276;
const int YY_parse_CLASS::rightshift_assignment_operator=277;
const int YY_parse_CLASS::XOR_assignment_operator=278;
const int YY_parse_CLASS::OR_assignment_operator=279;
const int YY_parse_CLASS::AND_assignment_operator=280;
const int YY_parse_CLASS::modulo_assignment_operator=281;
const int YY_parse_CLASS::multiplication_assignment_operator=282;
const int YY_parse_CLASS::division_assignment_operator=283;
const int YY_parse_CLASS::addition_assignment_operator=284;
const int YY_parse_CLASS::subtraction_assignment_operator=285;
const int YY_parse_CLASS::assignment_operator=286;
const int YY_parse_CLASS::OR_operator=287;
const int YY_parse_CLASS::AND_operator=288;
const int YY_parse_CLASS::pipe_operator=289;
const int YY_parse_CLASS::caret_operator=290;
const int YY_parse_CLASS::amp_operator=291;
const int YY_parse_CLASS::equality_operator=292;
const int YY_parse_CLASS::inequality_operator=293;
const int YY_parse_CLASS::lessthan_assignment_operator=294;
const int YY_parse_CLASS::lessthan_operator=295;
const int YY_parse_CLASS::greaterthan_assignment_operator=296;
const int YY_parse_CLASS::greaterthan_operator=297;
const int YY_parse_CLASS::leftshift_operator=298;
const int YY_parse_CLASS::rightshift_operator=299;
const int YY_parse_CLASS::add_operator=300;
const int YY_parse_CLASS::subtract_operator=301;
const int YY_parse_CLASS::multiplication_operator=302;
const int YY_parse_CLASS::division_operator=303;
const int YY_parse_CLASS::modulo_operator=304;
const int YY_parse_CLASS::SIZEOF=305;
const int YY_parse_CLASS::tilde_operator=306;
const int YY_parse_CLASS::exclamation_operator=307;
const int YY_parse_CLASS::increment_operator=308;
const int YY_parse_CLASS::decrement_operator=309;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		214
#define	YYFLAG		-32768
#define	YYNTBASE	64

#define YYTRANSLATE(x) ((unsigned)(x) <= 309 ? yytranslate[x] : 134)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,    61,
    62,     2,     2,    56,     2,    63,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    55,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    57,     2,    58,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    59,     2,    60,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     5,     7,     8,    10,    12,    16,    19,    22,
    23,    25,    26,    30,    31,    34,    35,    38,    39,    43,
    49,    51,    53,    57,    60,    65,    70,    76,    80,    84,
    86,    89,    93,    96,    98,   100,   101,   103,   105,   107,
   109,   112,   116,   120,   122,   123,   126,   129,   132,   133,
   134,   138,   141,   142,   144,   146,   148,   150,   152,   154,
   156,   160,   163,   164,   167,   169,   176,   179,   180,   186,
   195,   198,   200,   203,   206,   209,   214,   217,   220,   221,
   224,   226,   229,   232,   235,   238,   241,   244,   246,   248,
   251,   255,   256,   259,   263,   264,   267,   269,   272,   275,
   276,   278,   280,   282,   284,   286,   288,   292,   294,   296,
   298,   302,   304,   306,   308,   310,   312,   314,   316,   319,
   323,   326,   330,   332,   334,   339,   341,   342,   345,   349,
   350,   352,   354,   356
};

static const short yyrhs[] = {    65,
     0,    67,    66,     0,    65,     0,     0,    68,     0,    87,
     0,    86,    69,    55,     0,    71,    70,     0,    56,    69,
     0,     0,    15,     0,     0,    15,    72,    73,     0,     0,
    74,    77,     0,     0,    75,    83,     0,     0,    76,    31,
   111,     0,    57,    78,    58,    57,    79,     0,    16,     0,
    15,     0,    78,    58,    80,     0,    78,    58,     0,    31,
    59,    81,    60,     0,    31,    59,    82,    60,     0,    59,
   109,    60,    56,    81,     0,    59,   109,    60,     0,    17,
    56,    82,     0,    17,     0,    57,    84,     0,    16,    58,
    85,     0,    58,   107,     0,   107,     0,   108,     0,     0,
     4,     0,     5,     0,     6,     0,     9,     0,    88,    89,
     0,    86,    15,    61,     0,    90,    62,    97,     0,    91,
     0,     0,    86,    92,     0,    94,    93,     0,    56,    91,
     0,     0,     0,    15,    95,    96,     0,    57,    58,     0,
     0,   100,     0,    98,     0,   101,     0,   103,     0,   104,
     0,   106,     0,    68,     0,    59,    99,    60,     0,    97,
    99,     0,     0,   111,    55,     0,    55,     0,     3,    61,
   113,    62,    97,   102,     0,    20,    97,     0,     0,    10,
    61,   113,    62,    97,     0,    11,    61,   111,    55,   113,
    55,   111,    62,     0,     7,   105,     0,    55,     0,   111,
    55,     0,    12,    55,     0,    31,    17,     0,    31,    59,
   109,    60,     0,    16,   110,     0,    56,   109,     0,     0,
   126,   112,     0,   113,     0,    31,   111,     0,    29,   111,
     0,    30,   111,     0,    27,   111,     0,    28,   111,     0,
    26,   111,     0,    53,     0,    54,     0,   115,   114,     0,
    32,   115,   114,     0,     0,   117,   116,     0,    33,   117,
   116,     0,     0,    52,   117,     0,   118,     0,   121,   119,
     0,   120,   121,     0,     0,    41,     0,    39,     0,    42,
     0,    40,     0,    37,     0,    38,     0,   121,   122,   123,
     0,   123,     0,    45,     0,    46,     0,   123,   124,   125,
     0,   125,     0,    47,     0,    48,     0,    49,     0,   128,
     0,   126,     0,    15,     0,   126,   127,     0,    57,   111,
    58,     0,    63,    15,     0,    61,   111,    62,     0,   129,
     0,   133,     0,    15,    61,   130,    62,     0,   131,     0,
     0,   111,   132,     0,    56,   111,   132,     0,     0,    16,
     0,    17,     0,    18,     0,    19,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    65,    68,    71,    72,    75,    76,    80,    84,    87,    88,
    91,    91,    91,    93,    94,    94,    95,    95,    95,   105,
   109,   111,   114,   115,   118,   119,   122,   123,   126,   127,
   133,   136,   137,   140,   141,   142,   145,   145,   145,   146,
   158,   161,   164,   167,   167,   170,   173,   176,   177,   180,
   180,   183,   184,   187,   187,   188,   188,   189,   189,   190,
   193,   196,   197,   200,   201,   204,   207,   208,   211,   212,
   216,   219,   220,   223,   226,   229,   232,   235,   236,   239,
   240,   243,   244,   245,   246,   247,   248,   249,   250,   253,
   256,   256,   259,   262,   263,   266,   267,   270,   273,   274,
   277,   277,   277,   278,   278,   278,   281,   282,   285,   286,
   289,   290,   293,   293,   293,   296,   296,   299,   300,   303,
   304,   307,   308,   308,   311,   314,   314,   317,   320,   321,
   324,   325,   326,   327
};

static const char * const yytname[] = {   "$","error","$illegal.","IF","INT",
"CHAR","FLOAT","RETURN","MAIN","VOID","WHILE","FOR","BREAK","ENDIF","CONTINUE",
"identifier","integer_constant","string_constant","float_constant","character_constant",
"ELSE","leftshift_assignment_operator","rightshift_assignment_operator","XOR_assignment_operator",
"OR_assignment_operator","AND_assignment_operator","modulo_assignment_operator",
"multiplication_assignment_operator","division_assignment_operator","addition_assignment_operator",
"subtraction_assignment_operator","assignment_operator","OR_operator","AND_operator",
"pipe_operator","caret_operator","amp_operator","equality_operator","inequality_operator",
"lessthan_assignment_operator","lessthan_operator","greaterthan_assignment_operator",
"greaterthan_operator","leftshift_operator","rightshift_operator","add_operator",
"subtract_operator","multiplication_operator","division_operator","modulo_operator",
"SIZEOF","tilde_operator","exclamation_operator","increment_operator","decrement_operator",
"';'","','","'['","']'","'{'","'}'","'('","')'","'.'","program","declaration_list",
"D","declaration","variable_declaration","variable_declaration_list","V","variable_declaration_identifier",
"@1","vdi","@2","@3","@4","identifier_twod_array_type","initilization_params_2d",
"initilization_params_new","initilization_2d","array_init_2d","string_init_2d",
"identifier_array_type","initilization_params","initilization","type_specifier",
"function_declaration","function_declaration_type","function_declaration_param_statement",
"params","parameters_list","parameters_identifier_list","parameters_identifier_list_breakup",
"param_identifier","@5","param_identifier_breakup","statement","compound_statement",
"statment_list","expression_statment","conditional_statements","conditional_statements_breakup",
"iterative_statements","return_statement","return_statement_breakup","break_statement",
"string_initilization","array_initialization","array_int_declarations","array_int_declarations_breakup",
"expression","expression_breakup","simple_expression","simple_expression_breakup",
"and_expression","and_expression_breakup","unary_relation_expression","regular_expression",
"regular_expression_breakup","relational_operators","sum_expression","sum_operators",
"term","MULOP","factor","mutable","mutable_breakup","immutable","call","arguments",
"arguments_list","A","constant",""
};
#endif

static const short yyr1[] = {     0,
    64,    65,    66,    66,    67,    67,    68,    69,    70,    70,
    71,    72,    71,    74,    73,    75,    73,    76,    73,    77,
    78,    78,    79,    79,    80,    80,    81,    81,    82,    82,
    83,    84,    84,    85,    85,    85,    86,    86,    86,    86,
    87,    88,    89,    90,    90,    91,    92,    93,    93,    95,
    94,    96,    96,    97,    97,    97,    97,    97,    97,    97,
    98,    99,    99,   100,   100,   101,   102,   102,   103,   103,
   104,   105,   105,   106,   107,   108,   109,   110,   110,   111,
   111,   112,   112,   112,   112,   112,   112,   112,   112,   113,
   114,   114,   115,   116,   116,   117,   117,   118,   119,   119,
   120,   120,   120,   120,   120,   120,   121,   121,   122,   122,
   123,   123,   124,   124,   124,   125,   125,   126,   126,   127,
   127,   128,   128,   128,   129,   130,   130,   131,   132,   132,
   133,   133,   133,   133
};

static const short yyr2[] = {     0,
     1,     2,     1,     0,     1,     1,     3,     2,     2,     0,
     1,     0,     3,     0,     2,     0,     2,     0,     3,     5,
     1,     1,     3,     2,     4,     4,     5,     3,     3,     1,
     2,     3,     2,     1,     1,     0,     1,     1,     1,     1,
     2,     3,     3,     1,     0,     2,     2,     2,     0,     0,
     3,     2,     0,     1,     1,     1,     1,     1,     1,     1,
     3,     2,     0,     2,     1,     6,     2,     0,     5,     8,
     2,     1,     2,     2,     2,     4,     2,     2,     0,     2,
     1,     2,     2,     2,     2,     2,     2,     1,     1,     2,
     3,     0,     2,     3,     0,     2,     1,     2,     2,     0,
     1,     1,     1,     1,     1,     1,     3,     1,     1,     1,
     3,     1,     1,     1,     1,     1,     1,     1,     2,     3,
     2,     3,     1,     1,     4,     1,     0,     2,     3,     0,
     1,     1,     1,     1
};

static const short yydefact[] = {     0,
    37,    38,    39,    40,     1,     4,     5,     0,     6,    45,
     3,     2,    11,     0,    10,     0,    41,     0,    44,    42,
    14,     7,     0,     8,    50,    46,    49,     0,    13,     0,
     0,     0,    11,     9,    53,     0,    47,     0,     0,     0,
     0,     0,   118,   131,   132,   133,   134,     0,    65,    63,
     0,    60,     0,    43,    55,    54,    56,    57,    58,    59,
     0,    81,    92,    95,    97,   100,   108,   112,   117,   116,
   123,   124,     0,    15,     0,    17,     0,     0,    51,    48,
     0,    72,    71,     0,     0,     0,    74,   127,    96,   117,
    63,     0,     0,    64,     0,    90,     0,    93,   105,   106,
   102,   104,   101,   103,   109,   110,    98,     0,     0,   113,
   114,   115,     0,     0,     0,     0,     0,     0,     0,    88,
    89,     0,     0,    80,   119,    22,    21,     0,     0,     0,
    31,    19,    52,     0,    73,     0,     0,   130,     0,   126,
    62,    61,   122,    92,    95,    99,   107,   111,    87,    85,
    86,    83,    84,    82,     0,   121,     0,    36,     0,    33,
     0,     0,     0,     0,   128,   125,    91,    94,   120,     0,
     0,    32,    34,    35,    75,    68,    69,     0,   130,     0,
    20,     0,     0,    66,     0,   129,    24,    79,     0,    67,
     0,     0,    23,     0,    77,    76,    70,     0,    78,    30,
     0,     0,     0,     0,     0,    25,    26,    29,    28,     0,
    27,     0,     0,     0
};

static const short yydefgoto[] = {   212,
     5,    12,     6,    52,    14,    24,    15,    21,    29,    30,
    31,    32,    74,   128,   181,   193,   202,   203,    76,   131,
   172,    53,     9,    10,    17,    18,    19,    26,    37,    27,
    35,    79,    91,    55,    92,    56,    57,   184,    58,    59,
    83,    60,   160,   174,   189,   195,    61,   124,    62,    96,
    63,    98,    64,    65,   107,   108,    66,   109,    67,   113,
    68,    69,   125,    70,    71,   139,   140,   165,    72
};

static const short yypact[] = {    98,
-32768,-32768,-32768,-32768,-32768,    98,-32768,    -6,-32768,    98,
-32768,-32768,    14,   -30,   -45,    18,-32768,   -22,-32768,-32768,
    29,-32768,    47,-32768,-32768,-32768,    17,    11,-32768,    10,
    25,    52,   -23,-32768,    34,    98,-32768,    13,    40,    33,
    44,    38,    45,-32768,-32768,-32768,-32768,    71,-32768,    11,
    71,-32768,    47,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
    62,-32768,    86,    87,-32768,   111,    67,-32768,    82,-32768,
-32768,-32768,    20,-32768,   -14,-32768,    71,    63,-32768,-32768,
    71,-32768,-32768,    69,    71,    71,-32768,    71,-32768,   -51,
    11,    65,    60,-32768,    71,-32768,    71,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,    81,    81,-32768,
-32768,-32768,    81,    71,    71,    71,    71,    71,    71,-32768,
-32768,    71,   112,-32768,-32768,-32768,-32768,    70,    72,   100,
-32768,-32768,-32768,    75,-32768,    76,    74,    84,    79,-32768,
-32768,-32768,-32768,    86,    87,     1,    67,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,    85,-32768,    89,   113,   137,-32768,
    11,    11,    71,    71,-32768,-32768,-32768,-32768,-32768,    20,
    -7,-32768,-32768,-32768,-32768,   138,-32768,   104,    84,   102,
-32768,   145,    11,-32768,    71,-32768,   131,   107,   105,-32768,
   106,   108,-32768,   145,-32768,-32768,-32768,     2,-32768,   110,
   145,   109,   114,   147,   115,-32768,-32768,-32768,   116,   117,
-32768,   170,   171,-32768
};

static const short yypgoto[] = {-32768,
   167,-32768,-32768,    43,   154,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,     8,-32768,-32768,   -31,   -24,-32768,-32768,
-32768,    32,-32768,-32768,-32768,-32768,   146,-32768,-32768,-32768,
-32768,-32768,   -28,-32768,    90,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,    26,-32768,  -170,-32768,   -38,-32768,   -78,    39,
    91,    42,   -43,-32768,-32768,-32768,    77,-32768,    80,-32768,
    78,   -44,-32768,-32768,-32768,-32768,-32768,     9,-32768
};


#define	YYLAST		191


static const short yytable[] = {    54,
    84,   129,   134,    90,    89,   122,   136,   -12,    13,   175,
    23,   123,    93,    38,     1,     2,     3,    39,   200,     4,
    40,    41,    42,   199,    22,    43,    44,    45,    46,    47,
   205,     8,    25,   -12,   126,   127,    90,     8,   132,    28,
    90,    16,     7,   130,   -12,   105,   106,   137,     7,   138,
    90,   182,    90,   145,    43,    44,    45,    46,    47,   -18,
   201,    33,    48,    90,    90,    49,    73,    16,    90,    50,
   -12,    51,    36,    81,    20,   149,   150,   151,   152,   153,
   154,    75,    77,   155,   178,    43,    44,    45,    46,    47,
    78,    48,    87,    85,    82,    43,    44,    45,    46,    47,
    51,     1,     2,     3,    86,    88,     4,   114,   115,   116,
   117,   118,   119,   110,   111,   112,    94,    95,    90,    97,
   133,   143,    48,   135,   142,   179,   156,   157,   163,   158,
   159,    51,   176,   177,   120,   121,   161,   162,   122,   164,
   166,    51,   169,   171,   123,   170,   191,    99,   100,   101,
   102,   103,   104,   175,   190,   105,   106,   183,   185,   187,
   188,   192,   194,   200,   196,   204,   198,   197,   206,   213,
   214,   210,    11,   207,   209,   201,    34,   180,   211,   208,
   141,    80,   167,   173,   146,   144,   168,   186,   147,     0,
   148
};

static const short yycheck[] = {    28,
    39,    16,    81,    48,    48,    57,    85,    31,    15,    17,
    56,    63,    51,     3,     4,     5,     6,     7,    17,     9,
    10,    11,    12,   194,    55,    15,    16,    17,    18,    19,
   201,     0,    15,    57,    15,    16,    81,     6,    77,    62,
    85,    10,     0,    58,    31,    45,    46,    86,     6,    88,
    95,    59,    97,    97,    15,    16,    17,    18,    19,    31,
    59,    15,    52,   108,   109,    55,    57,    36,   113,    59,
    57,    61,    56,    61,    61,   114,   115,   116,   117,   118,
   119,    57,    31,   122,   163,    15,    16,    17,    18,    19,
    57,    52,    55,    61,    55,    15,    16,    17,    18,    19,
    61,     4,     5,     6,    61,    61,     9,    26,    27,    28,
    29,    30,    31,    47,    48,    49,    55,    32,   163,    33,
    58,    62,    52,    55,    60,   164,    15,    58,    55,    58,
    31,    61,   161,   162,    53,    54,    62,    62,    57,    56,
    62,    61,    58,    31,    63,    57,   185,    37,    38,    39,
    40,    41,    42,    17,   183,    45,    46,    20,    55,    58,
    16,    31,    56,    17,    60,    56,    59,    62,    60,     0,
     0,    56,     6,    60,    60,    59,    23,   170,   210,   204,
    91,    36,   144,   158,   108,    95,   145,   179,   109,    -1,
   113
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 11:
#line 91 "parser.y"
{ ins(); ;
    break;}
case 12:
#line 91 "parser.y"
{ ins(); ;
    break;}
case 14:
#line 93 "parser.y"
{;
    break;}
case 16:
#line 94 "parser.y"
{;
    break;}
case 18:
#line 95 "parser.y"
{;
    break;}
case 42:
#line 161 "parser.y"
{ ins();;
    break;}
case 50:
#line 180 "parser.y"
{ ins(); ;
    break;}
case 75:
#line 226 "parser.y"
{ insV(); ;
    break;}
case 131:
#line 324 "parser.y"
{ insV(); ;
    break;}
case 132:
#line 325 "parser.y"
{ insV(); ;
    break;}
case 133:
#line 326 "parser.y"
{ insV(); ;
    break;}
case 134:
#line 327 "parser.y"
{ insV(); ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 329 "parser.y"


extern FILE *yyin;
extern int yylineno;
extern char *yytext;
void insertSTtype(char *,char *);
void insertSTvalue(char *, char *);
void incertCT(char *, char *);
void printST();
void printCT();

int main(int argc , char **argv)
{
	yyin = fopen(argv[1], "r");
	yyparse();

	if(flag == 0)
	{
		printf(ANSI_COLOR_GREEN "Status: Parsing Complete - Valid" ANSI_COLOR_RESET "\n");
		printf("%30s" ANSI_COLOR_CYAN "SYMBOL TABLE" ANSI_COLOR_RESET "\n", " ");
		printf("%30s %s\n", " ", "------------");
		printST();

		printf("\n\n%30s" ANSI_COLOR_CYAN "CONSTANT TABLE" ANSI_COLOR_RESET "\n", " ");
		printf("%30s %s\n", " ", "--------------");
		printCT();
	}
}

void yyerror(char *s)
{
	printf("%d %s %s\n", yylineno, s, yytext);
	flag=1;
	printf(ANSI_COLOR_RED "Status: Parsing Failed - Invalid\n" ANSI_COLOR_RESET);
}

void ins()
{
	insertSTtype(curid,curtype);
}

void insV()
{
	insertSTvalue(curid,curval);
}

int yywrap()
{
	return 1;
}