#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from prakhar.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "prakhar.y"

	void yyerror(char* s);
	int yylex();
	#include "stdio.h"
	#include "stdlib.h"
	#include "ctype.h"
	#include "string.h"
	void ins();
	void insV();
	int flag=0;
 
	#define ANSI_COLOR_RED		"\x1b[31m"
	#define ANSI_COLOR_GREEN	"\x1b[32m"
	#define ANSI_COLOR_CYAN		"\x1b[36m"
	#define ANSI_COLOR_RESET	"\x1b[0m"
 
	extern char curid[20];
	extern char curtype[20];
	extern char curval[20];
 

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	IF	258
#define	INT	259
#define	CHAR	260
#define	FLOAT	261
#define	DOUBLE	262
#define	LONG	263
#define	SHORT	264
#define	SIGNED	265
#define	UNSIGNED	266
#define	STRUCT	267
#define	RETURN	268
#define	MAIN	269
#define	VOID	270
#define	WHILE	271
#define	FOR	272
#define	DO	273
#define	BREAK	274
#define	PRINTF	275
#define	CONTINUE	276
#define	ENDIF	277
#define	identifier	278
#define	integer_constant	279
#define	string_constant	280
#define	float_constant	281
#define	character_constant	282
#define	ELSE	283
#define	leftshift_assignment_operator	284
#define	rightshift_assignment_operator	285
#define	XOR_assignment_operator	286
#define	OR_assignment_operator	287
#define	AND_assignment_operator	288
#define	modulo_assignment_operator	289
#define	multiplication_assignment_operator	290
#define	division_assignment_operator	291
#define	addition_assignment_operator	292
#define	subtraction_assignment_operator	293
#define	assignment_operator	294
#define	OR_operator	295
#define	AND_operator	296
#define	pipe_operator	297
#define	caret_operator	298
#define	amp_operator	299
#define	equality_operator	300
#define	inequality_operator	301
#define	lessthan_assignment_operator	302
#define	lessthan_operator	303
#define	greaterthan_assignment_operator	304
#define	greaterthan_operator	305
#define	leftshift_operator	306
#define	rightshift_operator	307
#define	add_operator	308
#define	subtract_operator	309
#define	multiplication_operator	310
#define	division_operator	311
#define	modulo_operator	312
#define	SIZEOF	313
#define	tilde_operator	314
#define	exclamation_operator	315
#define	increment_operator	316
#define	decrement_operator	317


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int IF;
static const int INT;
static const int CHAR;
static const int FLOAT;
static const int DOUBLE;
static const int LONG;
static const int SHORT;
static const int SIGNED;
static const int UNSIGNED;
static const int STRUCT;
static const int RETURN;
static const int MAIN;
static const int VOID;
static const int WHILE;
static const int FOR;
static const int DO;
static const int BREAK;
static const int PRINTF;
static const int CONTINUE;
static const int ENDIF;
static const int identifier;
static const int integer_constant;
static const int string_constant;
static const int float_constant;
static const int character_constant;
static const int ELSE;
static const int leftshift_assignment_operator;
static const int rightshift_assignment_operator;
static const int XOR_assignment_operator;
static const int OR_assignment_operator;
static const int AND_assignment_operator;
static const int modulo_assignment_operator;
static const int multiplication_assignment_operator;
static const int division_assignment_operator;
static const int addition_assignment_operator;
static const int subtraction_assignment_operator;
static const int assignment_operator;
static const int OR_operator;
static const int AND_operator;
static const int pipe_operator;
static const int caret_operator;
static const int amp_operator;
static const int equality_operator;
static const int inequality_operator;
static const int lessthan_assignment_operator;
static const int lessthan_operator;
static const int greaterthan_assignment_operator;
static const int greaterthan_operator;
static const int leftshift_operator;
static const int rightshift_operator;
static const int add_operator;
static const int subtract_operator;
static const int multiplication_operator;
static const int division_operator;
static const int modulo_operator;
static const int SIZEOF;
static const int tilde_operator;
static const int exclamation_operator;
static const int increment_operator;
static const int decrement_operator;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,IF=258
	,INT=259
	,CHAR=260
	,FLOAT=261
	,DOUBLE=262
	,LONG=263
	,SHORT=264
	,SIGNED=265
	,UNSIGNED=266
	,STRUCT=267
	,RETURN=268
	,MAIN=269
	,VOID=270
	,WHILE=271
	,FOR=272
	,DO=273
	,BREAK=274
	,PRINTF=275
	,CONTINUE=276
	,ENDIF=277
	,identifier=278
	,integer_constant=279
	,string_constant=280
	,float_constant=281
	,character_constant=282
	,ELSE=283
	,leftshift_assignment_operator=284
	,rightshift_assignment_operator=285
	,XOR_assignment_operator=286
	,OR_assignment_operator=287
	,AND_assignment_operator=288
	,modulo_assignment_operator=289
	,multiplication_assignment_operator=290
	,division_assignment_operator=291
	,addition_assignment_operator=292
	,subtraction_assignment_operator=293
	,assignment_operator=294
	,OR_operator=295
	,AND_operator=296
	,pipe_operator=297
	,caret_operator=298
	,amp_operator=299
	,equality_operator=300
	,inequality_operator=301
	,lessthan_assignment_operator=302
	,lessthan_operator=303
	,greaterthan_assignment_operator=304
	,greaterthan_operator=305
	,leftshift_operator=306
	,rightshift_operator=307
	,add_operator=308
	,subtract_operator=309
	,multiplication_operator=310
	,division_operator=311
	,modulo_operator=312
	,SIZEOF=313
	,tilde_operator=314
	,exclamation_operator=315
	,increment_operator=316
	,decrement_operator=317


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::IF=258;
const int YY_parse_CLASS::INT=259;
const int YY_parse_CLASS::CHAR=260;
const int YY_parse_CLASS::FLOAT=261;
const int YY_parse_CLASS::DOUBLE=262;
const int YY_parse_CLASS::LONG=263;
const int YY_parse_CLASS::SHORT=264;
const int YY_parse_CLASS::SIGNED=265;
const int YY_parse_CLASS::UNSIGNED=266;
const int YY_parse_CLASS::STRUCT=267;
const int YY_parse_CLASS::RETURN=268;
const int YY_parse_CLASS::MAIN=269;
const int YY_parse_CLASS::VOID=270;
const int YY_parse_CLASS::WHILE=271;
const int YY_parse_CLASS::FOR=272;
const int YY_parse_CLASS::DO=273;
const int YY_parse_CLASS::BREAK=274;
const int YY_parse_CLASS::PRINTF=275;
const int YY_parse_CLASS::CONTINUE=276;
const int YY_parse_CLASS::ENDIF=277;
const int YY_parse_CLASS::identifier=278;
const int YY_parse_CLASS::integer_constant=279;
const int YY_parse_CLASS::string_constant=280;
const int YY_parse_CLASS::float_constant=281;
const int YY_parse_CLASS::character_constant=282;
const int YY_parse_CLASS::ELSE=283;
const int YY_parse_CLASS::leftshift_assignment_operator=284;
const int YY_parse_CLASS::rightshift_assignment_operator=285;
const int YY_parse_CLASS::XOR_assignment_operator=286;
const int YY_parse_CLASS::OR_assignment_operator=287;
const int YY_parse_CLASS::AND_assignment_operator=288;
const int YY_parse_CLASS::modulo_assignment_operator=289;
const int YY_parse_CLASS::multiplication_assignment_operator=290;
const int YY_parse_CLASS::division_assignment_operator=291;
const int YY_parse_CLASS::addition_assignment_operator=292;
const int YY_parse_CLASS::subtraction_assignment_operator=293;
const int YY_parse_CLASS::assignment_operator=294;
const int YY_parse_CLASS::OR_operator=295;
const int YY_parse_CLASS::AND_operator=296;
const int YY_parse_CLASS::pipe_operator=297;
const int YY_parse_CLASS::caret_operator=298;
const int YY_parse_CLASS::amp_operator=299;
const int YY_parse_CLASS::equality_operator=300;
const int YY_parse_CLASS::inequality_operator=301;
const int YY_parse_CLASS::lessthan_assignment_operator=302;
const int YY_parse_CLASS::lessthan_operator=303;
const int YY_parse_CLASS::greaterthan_assignment_operator=304;
const int YY_parse_CLASS::greaterthan_operator=305;
const int YY_parse_CLASS::leftshift_operator=306;
const int YY_parse_CLASS::rightshift_operator=307;
const int YY_parse_CLASS::add_operator=308;
const int YY_parse_CLASS::subtract_operator=309;
const int YY_parse_CLASS::multiplication_operator=310;
const int YY_parse_CLASS::division_operator=311;
const int YY_parse_CLASS::modulo_operator=312;
const int YY_parse_CLASS::SIZEOF=313;
const int YY_parse_CLASS::tilde_operator=314;
const int YY_parse_CLASS::exclamation_operator=315;
const int YY_parse_CLASS::increment_operator=316;
const int YY_parse_CLASS::decrement_operator=317;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		298
#define	YYFLAG		-32768
#define	YYNTBASE	71

#define YYTRANSLATE(x) ((unsigned)(x) <= 317 ? yytranslate[x] : 153)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,    69,
    70,     2,     2,    64,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    63,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    65,     2,    66,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    67,     2,    68,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54,    55,
    56,    57,    58,    59,    60,    61,    62
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     5,     7,     8,    10,    12,    14,    18,    20,
    23,    26,    27,    28,    32,    34,    36,    39,    40,    45,
    53,    55,    57,    59,    61,    67,    73,    78,    81,    85,
    88,    90,    92,    96,    99,   102,   104,   106,   107,   112,
   117,   122,   128,   132,   134,   140,   144,   146,   148,   152,
   154,   156,   158,   160,   162,   165,   168,   171,   174,   176,
   178,   181,   184,   185,   187,   190,   193,   194,   196,   197,
   199,   200,   201,   209,   212,   213,   217,   220,   224,   228,
   230,   231,   234,   237,   240,   241,   242,   246,   249,   250,
   252,   254,   256,   258,   260,   262,   264,   266,   268,   275,
   279,   283,   284,   288,   291,   292,   295,   297,   304,   307,
   308,   314,   323,   331,   334,   336,   339,   342,   345,   348,
   353,   358,   361,   364,   367,   370,   371,   374,   375,   378,
   380,   383,   386,   389,   392,   395,   398,   400,   402,   405,
   409,   410,   413,   417,   418,   421,   423,   426,   429,   430,
   432,   434,   436,   438,   440,   442,   446,   448,   450,   452,
   456,   458,   460,   462,   464,   466,   468,   470,   472,   476,
   478,   480,   485,   487,   488,   491,   495,   496,   498,   500,
   502
};

static const short yyrhs[] = {    72,
     0,    74,    73,     0,    72,     0,     0,    75,     0,   102,
     0,    98,     0,    93,    76,    63,     0,   101,     0,    78,
    77,     0,    64,    76,     0,     0,     0,    23,    79,    80,
     0,    84,     0,    83,     0,    39,   131,     0,     0,    23,
    65,    82,    66,     0,    23,    65,    82,    66,    65,    82,
    66,     0,    24,     0,    23,     0,    81,     0,   131,     0,
    65,    24,    66,    65,    85,     0,    65,    23,    66,    65,
    85,     0,    65,    66,    65,    85,     0,    65,    87,     0,
    86,    66,    89,     0,    86,    66,     0,    24,     0,    23,
     0,    24,    66,    88,     0,    66,    88,     0,    66,   125,
     0,   125,     0,   126,     0,     0,    39,    67,    90,    68,
     0,    39,    67,    91,    68,     0,    39,    67,    92,    68,
     0,    67,   127,    68,    64,    90,     0,    67,   127,    68,
     0,    24,     0,    67,   128,    68,    64,    91,     0,    67,
   128,    68,     0,    24,     0,    26,     0,    25,    64,    92,
     0,    25,     0,     4,     0,     5,     0,     6,     0,     7,
     0,     8,    96,     0,     9,    97,     0,    11,    94,     0,
    10,    95,     0,    15,     0,     4,     0,     8,    96,     0,
     9,    97,     0,     0,     4,     0,     8,    96,     0,     9,
    97,     0,     0,     4,     0,     0,     4,     0,     0,     0,
    12,    23,    99,    67,   100,    68,    63,     0,    75,   100,
     0,     0,    12,    23,    76,     0,   103,   104,     0,    93,
    23,    69,     0,   105,    70,   112,     0,   106,     0,     0,
    93,   107,     0,   109,   108,     0,    64,   106,     0,     0,
     0,    23,   110,   111,     0,    65,    66,     0,     0,   117,
     0,   115,     0,   118,     0,   120,     0,   121,     0,   123,
     0,    75,     0,   113,     0,   124,     0,    20,    69,    25,
   114,    70,    63,     0,    64,    23,   114,     0,    64,    81,
   114,     0,     0,    67,   116,    68,     0,   112,   116,     0,
     0,   131,    63,     0,    63,     0,     3,    69,   133,    70,
   112,   119,     0,    28,   112,     0,     0,    16,    69,   133,
    70,   112,     0,    17,    69,   131,    63,   133,    63,   131,
    70,     0,    18,   112,    16,    69,   133,    70,    63,     0,
    13,   122,     0,    63,     0,   131,    63,     0,    19,    63,
     0,    21,    63,     0,    39,    25,     0,    39,    67,   127,
    68,     0,    39,    67,   128,    68,     0,    24,   129,     0,
    26,   130,     0,    24,   130,     0,    64,   127,     0,     0,
    64,   128,     0,     0,   146,   132,     0,   133,     0,    39,
   131,     0,    37,   131,     0,    38,   131,     0,    35,   131,
     0,    36,   131,     0,    34,   131,     0,    61,     0,    62,
     0,   135,   134,     0,    40,   135,   134,     0,     0,   137,
   136,     0,    41,   137,   136,     0,     0,    60,   137,     0,
   138,     0,   141,   139,     0,   140,   141,     0,     0,    49,
     0,    47,     0,    50,     0,    48,     0,    45,     0,    46,
     0,   141,   142,   143,     0,   143,     0,    53,     0,    54,
     0,   143,   144,   145,     0,   145,     0,    55,     0,    56,
     0,    57,     0,   147,     0,   146,     0,    23,     0,    81,
     0,    69,   131,    70,     0,   148,     0,   152,     0,    23,
    69,   149,    70,     0,   150,     0,     0,   131,   151,     0,
    64,   131,   151,     0,     0,    24,     0,    25,     0,    26,
     0,    27,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    69,    72,    75,    76,    79,    80,    81,    84,    85,    88,
    91,    92,    95,    95,    98,    99,   100,   101,   104,   105,
   112,   113,   114,   115,   120,   121,   122,   125,   128,   129,
   132,   133,   136,   137,   138,   141,   142,   143,   146,   147,
   148,   151,   152,   153,   156,   157,   158,   159,   162,   163,
   167,   167,   167,   167,   168,   169,   170,   171,   172,   175,
   175,   175,   175,   178,   178,   178,   178,   181,   181,   184,
   184,   187,   187,   189,   189,   192,   196,   199,   202,   205,
   205,   208,   211,   214,   215,   218,   218,   221,   222,   225,
   225,   226,   226,   227,   227,   228,   228,   228,   231,   234,
   235,   236,   239,   242,   243,   246,   247,   250,   253,   254,
   257,   258,   259,   262,   265,   266,   269,   272,   275,   278,
   279,   282,   285,   286,   289,   290,   293,   294,   297,   298,
   301,   302,   303,   304,   305,   306,   307,   308,   311,   314,
   314,   317,   320,   321,   324,   325,   328,   331,   332,   335,
   335,   335,   336,   336,   336,   339,   340,   343,   344,   347,
   348,   351,   351,   351,   354,   354,   357,   358,   366,   367,
   367,   370,   373,   373,   376,   379,   380,   383,   384,   385,
   386
};

static const char * const yytname[] = {   "$","error","$illegal.","IF","INT",
"CHAR","FLOAT","DOUBLE","LONG","SHORT","SIGNED","UNSIGNED","STRUCT","RETURN",
"MAIN","VOID","WHILE","FOR","DO","BREAK","PRINTF","CONTINUE","ENDIF","identifier",
"integer_constant","string_constant","float_constant","character_constant","ELSE",
"leftshift_assignment_operator","rightshift_assignment_operator","XOR_assignment_operator",
"OR_assignment_operator","AND_assignment_operator","modulo_assignment_operator",
"multiplication_assignment_operator","division_assignment_operator","addition_assignment_operator",
"subtraction_assignment_operator","assignment_operator","OR_operator","AND_operator",
"pipe_operator","caret_operator","amp_operator","equality_operator","inequality_operator",
"lessthan_assignment_operator","lessthan_operator","greaterthan_assignment_operator",
"greaterthan_operator","leftshift_operator","rightshift_operator","add_operator",
"subtract_operator","multiplication_operator","division_operator","modulo_operator",
"SIZEOF","tilde_operator","exclamation_operator","increment_operator","decrement_operator",
"';'","','","'['","']'","'{'","'}'","'('","')'","program","declaration_list",
"D","declaration","variable_declaration","variable_declaration_list","V","variable_declaration_identifier",
"@1","vdi","array_random_access","array_random_access_breakup","identifier_twod_array_type",
"identifier_array_type","initialization_params_new","initialization_params_2d",
"initialization_params","initialization","initialization_2d","array_init_int_2d",
"array_init_float_2d","array_init_string_2d","type_specifier","unsigned_grammar",
"signed_grammar","long_grammar","short_grammar","structure_definition","@2",
"V1","structure_declaration","function_declaration","function_declaration_type",
"function_declaration_param_statement","params","parameters_list","parameters_identifier_list",
"parameters_identifier_list_breakup","param_identifier","@3","param_identifier_breakup",
"statement","printf_statement","printf_identifier_list","compound_statement",
"statment_list","expression_statment","conditional_statements","conditional_statements_breakup",
"iterative_statements","return_statement","return_statement_breakup","break_statement",
"continue_statement","string_initialization","array_initialization","array_int_declarations",
"array_float_declarations","array_int_declarations_breakup","array_float_declarations_breakup",
"expression","expression_breakup","simple_expression","simple_expression_breakup",
"and_expression","and_expression_breakup","unary_relation_expression","regular_expression",
"regular_expression_breakup","relational_operators","sum_expression","sum_operators",
"term","MULOP","factor","mutable","immutable","call","arguments","arguments_list",
"A","constant",""
};
#endif

static const short yyr1[] = {     0,
    71,    72,    73,    73,    74,    74,    74,    75,    75,    76,
    77,    77,    79,    78,    80,    80,    80,    80,    81,    81,
    82,    82,    82,    82,    83,    83,    83,    84,    85,    85,
    86,    86,    87,    87,    87,    88,    88,    88,    89,    89,
    89,    90,    90,    90,    91,    91,    91,    91,    92,    92,
    93,    93,    93,    93,    93,    93,    93,    93,    93,    94,
    94,    94,    94,    95,    95,    95,    95,    96,    96,    97,
    97,    99,    98,   100,   100,   101,   102,   103,   104,   105,
   105,   106,   107,   108,   108,   110,   109,   111,   111,   112,
   112,   112,   112,   112,   112,   112,   112,   112,   113,   114,
   114,   114,   115,   116,   116,   117,   117,   118,   119,   119,
   120,   120,   120,   121,   122,   122,   123,   124,   125,   126,
   126,   127,   128,   128,   129,   129,   130,   130,   131,   131,
   132,   132,   132,   132,   132,   132,   132,   132,   133,   134,
   134,   135,   136,   136,   137,   137,   138,   139,   139,   140,
   140,   140,   140,   140,   140,   141,   141,   142,   142,   143,
   143,   144,   144,   144,   145,   145,   146,   146,   147,   147,
   147,   148,   149,   149,   150,   151,   151,   152,   152,   152,
   152
};

static const short yyr2[] = {     0,
     1,     2,     1,     0,     1,     1,     1,     3,     1,     2,
     2,     0,     0,     3,     1,     1,     2,     0,     4,     7,
     1,     1,     1,     1,     5,     5,     4,     2,     3,     2,
     1,     1,     3,     2,     2,     1,     1,     0,     4,     4,
     4,     5,     3,     1,     5,     3,     1,     1,     3,     1,
     1,     1,     1,     1,     2,     2,     2,     2,     1,     1,
     2,     2,     0,     1,     2,     2,     0,     1,     0,     1,
     0,     0,     7,     2,     0,     3,     2,     3,     3,     1,
     0,     2,     2,     2,     0,     0,     3,     2,     0,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     6,     3,
     3,     0,     3,     2,     0,     2,     1,     6,     2,     0,
     5,     8,     7,     2,     1,     2,     2,     2,     2,     4,
     4,     2,     2,     2,     2,     0,     2,     0,     2,     1,
     2,     2,     2,     2,     2,     2,     1,     1,     2,     3,
     0,     2,     3,     0,     2,     1,     2,     2,     0,     1,
     1,     1,     1,     1,     1,     3,     1,     1,     1,     3,
     1,     1,     1,     1,     1,     1,     1,     1,     3,     1,
     1,     4,     1,     0,     2,     3,     0,     1,     1,     1,
     1
};

static const short yydefact[] = {     0,
    51,    52,    53,    54,    69,    71,    67,    63,     0,    59,
     1,     4,     5,     0,     7,     9,     6,    81,    68,    55,
    70,    56,    64,    69,    71,    58,    60,    69,    71,    57,
    72,     3,     2,    13,     0,    12,     0,    77,     0,    80,
    65,    66,    61,    62,    13,    76,     0,    78,    18,     8,
     0,    10,    86,    82,    85,     0,    75,     0,     0,    14,
    16,    15,    11,    89,     0,    83,     0,     0,     0,     0,
     0,     0,     0,     0,     0,   167,   178,   179,   180,   181,
     0,   107,   105,     0,    96,   168,     0,    79,    97,    91,
    90,    92,    93,    94,    95,    98,     0,   130,   141,   144,
   146,   149,   157,   161,   166,   165,   170,   171,    75,     0,
    17,     0,     0,    38,    28,     0,    87,    84,     0,     0,
   115,   114,     0,     0,     0,     0,   117,     0,   118,     0,
   174,   145,   166,   105,     0,     0,   106,     0,   139,     0,
   142,   154,   155,   151,   153,   150,   152,   158,   159,   147,
     0,     0,   162,   163,   164,     0,     0,     0,     0,     0,
     0,     0,   137,   138,   129,    74,     0,     0,    38,     0,
     0,    34,    35,    37,    88,     0,   116,     0,     0,     0,
   102,   167,   178,   168,     0,    24,   177,     0,   173,   104,
   103,   169,   141,   144,   148,   156,   160,   136,   134,   135,
   132,   133,   131,    73,     0,     0,    33,    36,   119,     0,
    32,    31,    27,     0,     0,     0,     0,     0,     0,     0,
    19,     0,   175,   172,   140,   143,    26,    25,   126,   128,
     0,     0,    30,   110,   111,     0,     0,   102,   102,     0,
     0,   177,     0,   122,   124,     0,   123,   120,   121,     0,
    29,     0,   108,     0,     0,   100,   101,    99,     0,   176,
   125,   127,   128,     0,   109,     0,   113,    20,    44,    50,
    48,     0,     0,     0,     0,   112,     0,     0,     0,    39,
    40,    41,    49,    43,    46,     0,     0,    44,     0,    42,
    47,     0,    45,   126,     0,     0,     0,     0
};

static const short yydefgoto[] = {   296,
    11,    33,    12,    85,    35,    52,    36,    49,    60,    86,
   185,    61,    62,   213,   214,   115,   172,   251,   273,   274,
   275,    87,    30,    26,    20,    22,    15,    47,   110,    16,
    17,    18,    38,    39,    40,    54,    66,    55,    64,   117,
   134,    89,   220,    90,   135,    91,    92,   253,    93,    94,
   122,    95,    96,   173,   174,   261,   262,   244,   245,    97,
   165,    98,   139,    99,   141,   100,   101,   150,   151,   102,
   152,   103,   156,   104,   105,   106,   107,   188,   189,   223,
   108
};

static const short yypact[] = {   180,
-32768,-32768,-32768,-32768,     5,    23,    37,   138,     1,-32768,
-32768,   180,-32768,    39,-32768,-32768,-32768,   206,-32768,-32768,
-32768,-32768,-32768,     5,    23,-32768,-32768,     5,    23,-32768,
    42,-32768,-32768,    56,   -20,    28,   146,-32768,    63,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,    76,-32768,    -8,-32768,
    42,-32768,-32768,-32768,   112,   111,   194,    26,   -10,-32768,
-32768,-32768,-32768,   114,   206,-32768,   106,   154,    -5,   124,
   125,   111,   145,   149,   156,   -21,-32768,-32768,-32768,-32768,
    26,-32768,   111,    26,-32768,-32768,    42,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,   157,-32768,   167,   187,
-32768,   177,   110,-32768,   120,-32768,-32768,-32768,   194,   161,
-32768,   166,   168,    15,-32768,   169,-32768,-32768,    26,    42,
-32768,-32768,   170,    26,    26,   220,-32768,   212,-32768,    84,
    26,-32768,-32768,   111,   171,   172,-32768,    26,-32768,    26,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
    13,    13,-32768,-32768,-32768,    13,    26,    26,    26,    26,
    26,    26,-32768,-32768,-32768,-32768,   175,   176,    20,     4,
    54,-32768,-32768,-32768,-32768,   173,-32768,   174,   182,   178,
   184,    24,   183,   185,   186,-32768,   189,   188,-32768,-32768,
-32768,-32768,   167,   187,    30,   110,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,    54,    54,-32768,-32768,-32768,     6,
-32768,-32768,-32768,   190,   111,   111,    26,    26,   217,   191,
   181,    26,-32768,-32768,-32768,-32768,-32768,-32768,   193,   195,
   192,   196,   211,   226,-32768,   199,   197,    86,   184,   200,
    84,   189,     6,-32768,-32768,   144,-32768,-32768,-32768,   198,
-32768,   111,-32768,    26,   203,-32768,-32768,-32768,   202,-32768,
-32768,-32768,   195,    72,-32768,   201,-32768,-32768,-32768,   205,
-32768,     6,   204,   207,   208,-32768,   230,   209,   210,-32768,
-32768,-32768,-32768,   215,   216,    -1,     9,-32768,   246,-32768,
-32768,   144,-32768,   218,   246,   273,   274,-32768
};

static const short yypgoto[] = {-32768,
   269,-32768,-32768,     3,   -26,-32768,-32768,-32768,-32768,  -128,
    43,-32768,-32768,   -43,-32768,-32768,   116,-32768,    -3,     0,
    11,    16,-32768,-32768,   121,   123,-32768,-32768,   213,-32768,
-32768,-32768,-32768,-32768,   221,-32768,-32768,-32768,-32768,-32768,
   -55,-32768,   -66,-32768,   155,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,   122,-32768,  -202,  -204,-32768,    60,   -58,
-32768,  -112,    99,   158,   100,   -71,-32768,-32768,-32768,   142,
-32768,   143,-32768,   141,   -77,-32768,-32768,-32768,-32768,    57,
-32768
};


#define	YYLAST		322


static const short yytable[] = {   111,
    88,   184,    13,   133,    46,   232,   176,   231,    19,   132,
   123,   178,   112,   113,    13,    14,   126,    76,    77,    78,
    79,    80,   288,    31,    63,   136,    21,    14,   209,   229,
    58,   230,   291,    37,   271,    76,    77,    78,    79,    80,
    23,   133,    50,   130,    24,    25,   133,   131,    76,    77,
    78,    79,    80,   170,    81,   114,    59,   121,   170,   109,
   133,    34,   133,    84,    45,   289,   179,   279,   194,   278,
   210,   186,   187,   133,   133,   292,   211,   212,   133,   171,
    37,    84,   148,   149,   206,    81,   278,   279,   130,   -22,
   239,    51,   131,    46,    84,   269,   270,   271,   198,   199,
   200,   201,   202,   203,   236,   237,   182,   183,    78,    79,
    80,   109,   184,    67,     1,     2,     3,     4,     5,     6,
     7,     8,    68,    69,    48,    10,    70,    71,    72,    73,
    74,    75,    56,    76,    77,    78,    79,    80,   272,   133,
   133,    27,    57,    81,    41,    28,    29,    42,    43,   219,
   130,    44,    84,   157,   158,   159,   160,   161,   162,   234,
   235,   227,   228,   242,   153,   154,   155,   263,    53,   230,
    81,   256,   257,    82,   119,    65,   120,    83,   116,    84,
   163,   164,   186,     1,     2,     3,     4,     5,     6,     7,
     8,     9,   124,   125,    10,   266,   265,     1,     2,     3,
     4,     5,     6,     7,     8,    68,   138,   127,    10,     1,
     2,     3,     4,     5,     6,     7,     8,   128,   129,   137,
    10,   142,   143,   144,   145,   146,   147,   140,   167,   148,
   149,   168,   177,   169,   175,   180,   181,   204,   191,   238,
   205,   192,   215,   216,   217,   241,   218,   219,   -21,   250,
   -23,   221,   222,   252,   270,   233,   243,   224,   246,   248,
   240,   254,   258,   249,   264,   267,   255,   268,   277,   294,
   276,   280,   297,   298,   281,   282,   284,   285,   286,   287,
    32,   295,   290,   259,   207,   118,   293,   283,   190,   247,
   208,   225,   195,   226,   196,   193,   197,     0,   260,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,   166
};

static const short yycheck[] = {    58,
    56,   130,     0,    81,    31,   210,   119,   210,     4,    81,
    69,   124,    23,    24,    12,     0,    72,    23,    24,    25,
    26,    27,    24,    23,    51,    84,     4,    12,    25,    24,
    39,    26,    24,    18,    26,    23,    24,    25,    26,    27,
     4,   119,    63,    65,     8,     9,   124,    69,    23,    24,
    25,    26,    27,    39,    60,    66,    65,    63,    39,    57,
   138,    23,   140,    69,    23,    67,   125,   272,   140,   272,
    67,   130,   131,   151,   152,    67,    23,    24,   156,    65,
    65,    69,    53,    54,    65,    60,   289,   292,    65,    66,
   219,    64,    69,   120,    69,    24,    25,    26,   157,   158,
   159,   160,   161,   162,   217,   218,    23,    24,    25,    26,
    27,   109,   241,     3,     4,     5,     6,     7,     8,     9,
    10,    11,    12,    13,    69,    15,    16,    17,    18,    19,
    20,    21,    70,    23,    24,    25,    26,    27,    67,   217,
   218,     4,    67,    60,    24,     8,     9,    25,    28,    64,
    65,    29,    69,    34,    35,    36,    37,    38,    39,   215,
   216,   205,   206,   222,    55,    56,    57,    24,    23,    26,
    60,   238,   239,    63,    69,    64,    23,    67,    65,    69,
    61,    62,   241,     4,     5,     6,     7,     8,     9,    10,
    11,    12,    69,    69,    15,   254,   252,     4,     5,     6,
     7,     8,     9,    10,    11,    12,    40,    63,    15,     4,
     5,     6,     7,     8,     9,    10,    11,    69,    63,    63,
    15,    45,    46,    47,    48,    49,    50,    41,    68,    53,
    54,    66,    63,    66,    66,    16,    25,    63,    68,    23,
    65,    70,    70,    70,    63,    65,    69,    64,    66,    39,
    66,    66,    64,    28,    25,    66,    64,    70,    64,    68,
    70,    63,    63,    68,    67,    63,    70,    66,    64,    24,
    70,    68,     0,     0,    68,    68,    68,    68,    64,    64,
    12,    64,   286,   241,   169,    65,   287,   277,   134,   230,
   169,   193,   151,   194,   152,   138,   156,    -1,   242,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,   109
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 13:
#line 95 "prakhar.y"
{ ins(); ;
    break;}
case 72:
#line 187 "prakhar.y"
{ ins(); ;
    break;}
case 78:
#line 199 "prakhar.y"
{ ins();;
    break;}
case 86:
#line 218 "prakhar.y"
{ ins(); ;
    break;}
case 119:
#line 275 "prakhar.y"
{ insV(); ;
    break;}
case 178:
#line 383 "prakhar.y"
{ insV(); ;
    break;}
case 179:
#line 384 "prakhar.y"
{ insV(); ;
    break;}
case 180:
#line 385 "prakhar.y"
{ insV(); ;
    break;}
case 181:
#line 386 "prakhar.y"
{ insV(); ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 388 "prakhar.y"

 
extern FILE *yyin;
extern int yylineno;
extern char *yytext;
void insertSTtype(char *,char *);
void insertSTvalue(char *, char *);
void incertCT(char *, char *);
void printST();
void printCT();
 
int main(int argc , char **argv)
{
	yyin = fopen(argv[1], "r");
	yyparse();
 
	if(flag == 0)
	{
		printf(ANSI_COLOR_GREEN "Status: Parsing Complete - Valid" ANSI_COLOR_RESET "\n");
		printf("%30s" ANSI_COLOR_CYAN "SYMBOL TABLE" ANSI_COLOR_RESET "\n", " ");
		printf("%30s %s\n", " ", "------------");
		printST();
 
		printf("\n\n%30s" ANSI_COLOR_CYAN "CONSTANT TABLE" ANSI_COLOR_RESET "\n", " ");
		printf("%30s %s\n", " ", "--------------");
		printCT();
	}
}
 
void yyerror(char *s)
{
	printf("%d %s %s\n", yylineno, s, yytext);
	flag=1;
	printf(ANSI_COLOR_RED "Status: Parsing Failed - Invalid\n" ANSI_COLOR_RESET);
}
 
void ins()
{
	insertSTtype(curid,curtype);
}
 
void insV()
{
	insertSTvalue(curid,curval);
}
 
int yywrap()
{
	return 1;
}