#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from prakhar.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "prakhar.y"

	void yyerror(char* s);
	int yylex();
	#include "stdio.h"
	#include "stdlib.h"
	#include "ctype.h"
	#include "string.h"
	void ins();
	void insV();
	int flag=0;

	#define ANSI_COLOR_RED		"\x1b[31m"
	#define ANSI_COLOR_GREEN	"\x1b[32m"
	#define ANSI_COLOR_CYAN		"\x1b[36m"
	#define ANSI_COLOR_RESET	"\x1b[0m"

	extern char curid[20];
	extern char curtype[20];
	extern char curval[20];


#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	IF	258
#define	INT	259
#define	CHAR	260
#define	FLOAT	261
#define	DOUBLE	262
#define	LONG	263
#define	SHORT	264
#define	SIGNED	265
#define	UNSIGNED	266
#define	STRUCT	267
#define	RETURN	268
#define	MAIN	269
#define	VOID	270
#define	WHILE	271
#define	FOR	272
#define	DO	273
#define	BREAK	274
#define	PRINTF	275
#define	CONTINUE	276
#define	ENDIF	277
#define	identifier	278
#define	integer_constant	279
#define	string_constant	280
#define	float_constant	281
#define	character_constant	282
#define	ELSE	283
#define	leftshift_assignment_operator	284
#define	rightshift_assignment_operator	285
#define	XOR_assignment_operator	286
#define	OR_assignment_operator	287
#define	AND_assignment_operator	288
#define	modulo_assignment_operator	289
#define	multiplication_assignment_operator	290
#define	division_assignment_operator	291
#define	addition_assignment_operator	292
#define	subtraction_assignment_operator	293
#define	assignment_operator	294
#define	OR_operator	295
#define	AND_operator	296
#define	pipe_operator	297
#define	caret_operator	298
#define	amp_operator	299
#define	equality_operator	300
#define	inequality_operator	301
#define	lessthan_assignment_operator	302
#define	lessthan_operator	303
#define	greaterthan_assignment_operator	304
#define	greaterthan_operator	305
#define	leftshift_operator	306
#define	rightshift_operator	307
#define	add_operator	308
#define	subtract_operator	309
#define	multiplication_operator	310
#define	division_operator	311
#define	modulo_operator	312
#define	SIZEOF	313
#define	tilde_operator	314
#define	exclamation_operator	315
#define	increment_operator	316
#define	decrement_operator	317


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int IF;
static const int INT;
static const int CHAR;
static const int FLOAT;
static const int DOUBLE;
static const int LONG;
static const int SHORT;
static const int SIGNED;
static const int UNSIGNED;
static const int STRUCT;
static const int RETURN;
static const int MAIN;
static const int VOID;
static const int WHILE;
static const int FOR;
static const int DO;
static const int BREAK;
static const int PRINTF;
static const int CONTINUE;
static const int ENDIF;
static const int identifier;
static const int integer_constant;
static const int string_constant;
static const int float_constant;
static const int character_constant;
static const int ELSE;
static const int leftshift_assignment_operator;
static const int rightshift_assignment_operator;
static const int XOR_assignment_operator;
static const int OR_assignment_operator;
static const int AND_assignment_operator;
static const int modulo_assignment_operator;
static const int multiplication_assignment_operator;
static const int division_assignment_operator;
static const int addition_assignment_operator;
static const int subtraction_assignment_operator;
static const int assignment_operator;
static const int OR_operator;
static const int AND_operator;
static const int pipe_operator;
static const int caret_operator;
static const int amp_operator;
static const int equality_operator;
static const int inequality_operator;
static const int lessthan_assignment_operator;
static const int lessthan_operator;
static const int greaterthan_assignment_operator;
static const int greaterthan_operator;
static const int leftshift_operator;
static const int rightshift_operator;
static const int add_operator;
static const int subtract_operator;
static const int multiplication_operator;
static const int division_operator;
static const int modulo_operator;
static const int SIZEOF;
static const int tilde_operator;
static const int exclamation_operator;
static const int increment_operator;
static const int decrement_operator;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,IF=258
	,INT=259
	,CHAR=260
	,FLOAT=261
	,DOUBLE=262
	,LONG=263
	,SHORT=264
	,SIGNED=265
	,UNSIGNED=266
	,STRUCT=267
	,RETURN=268
	,MAIN=269
	,VOID=270
	,WHILE=271
	,FOR=272
	,DO=273
	,BREAK=274
	,PRINTF=275
	,CONTINUE=276
	,ENDIF=277
	,identifier=278
	,integer_constant=279
	,string_constant=280
	,float_constant=281
	,character_constant=282
	,ELSE=283
	,leftshift_assignment_operator=284
	,rightshift_assignment_operator=285
	,XOR_assignment_operator=286
	,OR_assignment_operator=287
	,AND_assignment_operator=288
	,modulo_assignment_operator=289
	,multiplication_assignment_operator=290
	,division_assignment_operator=291
	,addition_assignment_operator=292
	,subtraction_assignment_operator=293
	,assignment_operator=294
	,OR_operator=295
	,AND_operator=296
	,pipe_operator=297
	,caret_operator=298
	,amp_operator=299
	,equality_operator=300
	,inequality_operator=301
	,lessthan_assignment_operator=302
	,lessthan_operator=303
	,greaterthan_assignment_operator=304
	,greaterthan_operator=305
	,leftshift_operator=306
	,rightshift_operator=307
	,add_operator=308
	,subtract_operator=309
	,multiplication_operator=310
	,division_operator=311
	,modulo_operator=312
	,SIZEOF=313
	,tilde_operator=314
	,exclamation_operator=315
	,increment_operator=316
	,decrement_operator=317


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::IF=258;
const int YY_parse_CLASS::INT=259;
const int YY_parse_CLASS::CHAR=260;
const int YY_parse_CLASS::FLOAT=261;
const int YY_parse_CLASS::DOUBLE=262;
const int YY_parse_CLASS::LONG=263;
const int YY_parse_CLASS::SHORT=264;
const int YY_parse_CLASS::SIGNED=265;
const int YY_parse_CLASS::UNSIGNED=266;
const int YY_parse_CLASS::STRUCT=267;
const int YY_parse_CLASS::RETURN=268;
const int YY_parse_CLASS::MAIN=269;
const int YY_parse_CLASS::VOID=270;
const int YY_parse_CLASS::WHILE=271;
const int YY_parse_CLASS::FOR=272;
const int YY_parse_CLASS::DO=273;
const int YY_parse_CLASS::BREAK=274;
const int YY_parse_CLASS::PRINTF=275;
const int YY_parse_CLASS::CONTINUE=276;
const int YY_parse_CLASS::ENDIF=277;
const int YY_parse_CLASS::identifier=278;
const int YY_parse_CLASS::integer_constant=279;
const int YY_parse_CLASS::string_constant=280;
const int YY_parse_CLASS::float_constant=281;
const int YY_parse_CLASS::character_constant=282;
const int YY_parse_CLASS::ELSE=283;
const int YY_parse_CLASS::leftshift_assignment_operator=284;
const int YY_parse_CLASS::rightshift_assignment_operator=285;
const int YY_parse_CLASS::XOR_assignment_operator=286;
const int YY_parse_CLASS::OR_assignment_operator=287;
const int YY_parse_CLASS::AND_assignment_operator=288;
const int YY_parse_CLASS::modulo_assignment_operator=289;
const int YY_parse_CLASS::multiplication_assignment_operator=290;
const int YY_parse_CLASS::division_assignment_operator=291;
const int YY_parse_CLASS::addition_assignment_operator=292;
const int YY_parse_CLASS::subtraction_assignment_operator=293;
const int YY_parse_CLASS::assignment_operator=294;
const int YY_parse_CLASS::OR_operator=295;
const int YY_parse_CLASS::AND_operator=296;
const int YY_parse_CLASS::pipe_operator=297;
const int YY_parse_CLASS::caret_operator=298;
const int YY_parse_CLASS::amp_operator=299;
const int YY_parse_CLASS::equality_operator=300;
const int YY_parse_CLASS::inequality_operator=301;
const int YY_parse_CLASS::lessthan_assignment_operator=302;
const int YY_parse_CLASS::lessthan_operator=303;
const int YY_parse_CLASS::greaterthan_assignment_operator=304;
const int YY_parse_CLASS::greaterthan_operator=305;
const int YY_parse_CLASS::leftshift_operator=306;
const int YY_parse_CLASS::rightshift_operator=307;
const int YY_parse_CLASS::add_operator=308;
const int YY_parse_CLASS::subtract_operator=309;
const int YY_parse_CLASS::multiplication_operator=310;
const int YY_parse_CLASS::division_operator=311;
const int YY_parse_CLASS::modulo_operator=312;
const int YY_parse_CLASS::SIZEOF=313;
const int YY_parse_CLASS::tilde_operator=314;
const int YY_parse_CLASS::exclamation_operator=315;
const int YY_parse_CLASS::increment_operator=316;
const int YY_parse_CLASS::decrement_operator=317;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		303
#define	YYFLAG		-32768
#define	YYNTBASE	72

#define YYTRANSLATE(x) ((unsigned)(x) <= 317 ? yytranslate[x] : 155)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,    69,
    70,     2,     2,    64,     2,    71,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    63,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    65,     2,    66,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    67,     2,    68,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54,    55,
    56,    57,    58,    59,    60,    61,    62
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     5,     7,     8,    10,    12,    14,    18,    20,
    23,    26,    27,    28,    32,    34,    36,    39,    40,    45,
    53,    55,    57,    59,    65,    71,    76,    79,    83,    86,
    88,    90,    94,    97,   100,   102,   104,   105,   110,   115,
   120,   126,   130,   132,   138,   142,   144,   146,   150,   152,
   154,   156,   158,   160,   163,   166,   169,   172,   174,   176,
   179,   182,   183,   185,   188,   191,   192,   194,   195,   197,
   198,   199,   207,   210,   211,   215,   218,   222,   226,   228,
   229,   232,   235,   238,   239,   240,   244,   247,   248,   250,
   252,   254,   256,   258,   260,   262,   264,   266,   273,   277,
   281,   282,   285,   289,   292,   293,   296,   298,   305,   308,
   309,   315,   324,   332,   335,   337,   340,   343,   346,   349,
   354,   359,   362,   365,   368,   371,   372,   375,   376,   379,
   381,   384,   387,   390,   393,   396,   399,   401,   403,   406,
   410,   411,   414,   418,   419,   422,   424,   427,   430,   431,
   433,   435,   437,   439,   441,   443,   447,   449,   451,   453,
   457,   459,   461,   463,   465,   467,   469,   471,   473,   476,
   480,   483,   487,   489,   491,   496,   498,   499,   502,   506,
   507,   509,   511,   513
};

static const short yyrhs[] = {    73,
     0,    75,    74,     0,    73,     0,     0,    76,     0,   103,
     0,    99,     0,    94,    77,    63,     0,   102,     0,    79,
    78,     0,    64,    77,     0,     0,     0,    23,    80,    81,
     0,    85,     0,    84,     0,    39,   132,     0,     0,    23,
    65,    83,    66,     0,    23,    65,    83,    66,    65,    83,
    66,     0,    24,     0,    23,     0,    82,     0,    65,    24,
    66,    65,    86,     0,    65,    23,    66,    65,    86,     0,
    65,    66,    65,    86,     0,    65,    88,     0,    87,    66,
    90,     0,    87,    66,     0,    24,     0,    23,     0,    24,
    66,    89,     0,    66,    89,     0,    66,   126,     0,   126,
     0,   127,     0,     0,    39,    67,    91,    68,     0,    39,
    67,    92,    68,     0,    39,    67,    93,    68,     0,    67,
   128,    68,    64,    91,     0,    67,   128,    68,     0,    24,
     0,    67,   129,    68,    64,    92,     0,    67,   129,    68,
     0,    24,     0,    26,     0,    25,    64,    93,     0,    25,
     0,     4,     0,     5,     0,     6,     0,     7,     0,     8,
    97,     0,     9,    98,     0,    11,    95,     0,    10,    96,
     0,    15,     0,     4,     0,     8,    97,     0,     9,    98,
     0,     0,     4,     0,     8,    97,     0,     9,    98,     0,
     0,     4,     0,     0,     4,     0,     0,     0,    12,    23,
   100,    67,   101,    68,    63,     0,    76,   101,     0,     0,
    12,    23,    77,     0,   104,   105,     0,    94,    23,    69,
     0,   106,    70,   113,     0,   107,     0,     0,    94,   108,
     0,   110,   109,     0,    64,   107,     0,     0,     0,    23,
   111,   112,     0,    65,    66,     0,     0,   119,     0,   117,
     0,   120,     0,   122,     0,   123,     0,   125,     0,    76,
     0,   114,     0,   116,     0,    20,    69,    25,   115,    70,
    63,     0,    64,    23,   115,     0,    64,    82,   115,     0,
     0,    21,    63,     0,    67,   118,    68,     0,   113,   118,
     0,     0,   132,    63,     0,    63,     0,     3,    69,   134,
    70,   113,   121,     0,    28,   113,     0,     0,    16,    69,
   134,    70,   113,     0,    17,    69,   132,    63,   134,    63,
   132,    70,     0,    18,   113,    16,    69,   134,    70,    63,
     0,    13,   124,     0,    63,     0,   132,    63,     0,    19,
    63,     0,    21,    63,     0,    39,    25,     0,    39,    67,
   128,    68,     0,    39,    67,   129,    68,     0,    24,   130,
     0,    26,   131,     0,    24,   131,     0,    64,   128,     0,
     0,    64,   129,     0,     0,   147,   133,     0,   134,     0,
    39,   132,     0,    37,   132,     0,    38,   132,     0,    35,
   132,     0,    36,   132,     0,    34,   132,     0,    61,     0,
    62,     0,   136,   135,     0,    40,   136,   135,     0,     0,
   138,   137,     0,    41,   138,   137,     0,     0,    60,   138,
     0,   139,     0,   142,   140,     0,   141,   142,     0,     0,
    49,     0,    47,     0,    50,     0,    48,     0,    45,     0,
    46,     0,   142,   143,   144,     0,   144,     0,    53,     0,
    54,     0,   144,   145,   146,     0,   146,     0,    55,     0,
    56,     0,    57,     0,   149,     0,   147,     0,    23,     0,
    82,     0,   147,   148,     0,    65,   132,    66,     0,    71,
    23,     0,    69,   132,    70,     0,   150,     0,   154,     0,
    23,    69,   151,    70,     0,   152,     0,     0,   132,   153,
     0,    64,   132,   153,     0,     0,    24,     0,    25,     0,
    26,     0,    27,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    69,    72,    75,    76,    79,    80,    81,    84,    85,    88,
    91,    92,    95,    95,    98,    99,   100,   101,   104,   105,
   112,   113,   114,   131,   132,   133,   136,   139,   140,   143,
   144,   148,   149,   150,   153,   154,   155,   158,   159,   160,
   164,   165,   166,   169,   170,   171,   172,   175,   176,   180,
   180,   180,   180,   181,   182,   183,   184,   185,   188,   188,
   188,   188,   191,   191,   191,   191,   194,   194,   197,   197,
   200,   200,   202,   202,   205,   209,   212,   215,   218,   218,
   221,   224,   227,   228,   231,   231,   234,   235,   238,   238,
   239,   239,   240,   240,   241,   241,   241,   244,   247,   248,
   249,   252,   255,   258,   259,   262,   263,   266,   269,   270,
   273,   274,   275,   278,   281,   282,   285,   288,   291,   294,
   295,   298,   301,   302,   305,   306,   309,   310,   313,   314,
   317,   318,   319,   320,   321,   322,   323,   324,   327,   330,
   330,   333,   336,   337,   340,   341,   344,   347,   348,   351,
   351,   351,   352,   352,   352,   355,   356,   359,   360,   363,
   364,   367,   367,   367,   370,   370,   373,   374,   375,   378,
   379,   382,   383,   383,   386,   389,   389,   392,   395,   396,
   399,   400,   401,   402
};

static const char * const yytname[] = {   "$","error","$illegal.","IF","INT",
"CHAR","FLOAT","DOUBLE","LONG","SHORT","SIGNED","UNSIGNED","STRUCT","RETURN",
"MAIN","VOID","WHILE","FOR","DO","BREAK","PRINTF","CONTINUE","ENDIF","identifier",
"integer_constant","string_constant","float_constant","character_constant","ELSE",
"leftshift_assignment_operator","rightshift_assignment_operator","XOR_assignment_operator",
"OR_assignment_operator","AND_assignment_operator","modulo_assignment_operator",
"multiplication_assignment_operator","division_assignment_operator","addition_assignment_operator",
"subtraction_assignment_operator","assignment_operator","OR_operator","AND_operator",
"pipe_operator","caret_operator","amp_operator","equality_operator","inequality_operator",
"lessthan_assignment_operator","lessthan_operator","greaterthan_assignment_operator",
"greaterthan_operator","leftshift_operator","rightshift_operator","add_operator",
"subtract_operator","multiplication_operator","division_operator","modulo_operator",
"SIZEOF","tilde_operator","exclamation_operator","increment_operator","decrement_operator",
"';'","','","'['","']'","'{'","'}'","'('","')'","'.'","program","declaration_list",
"D","declaration","variable_declaration","variable_declaration_list","V","variable_declaration_identifier",
"@1","vdi","array_random_access","array_random_access_breakup","identifier_twod_array_type",
"identifier_array_type","initialization_params_new","initialization_params_2d",
"initialization_params","initialization","initialization_2d","array_init_int_2d",
"array_init_float_2d","array_init_string_2d","type_specifier","unsigned_grammar",
"signed_grammar","long_grammar","short_grammar","structure_definition","@2",
"V1","structure_declaration","function_declaration","function_declaration_type",
"function_declaration_param_statement","params","parameters_list","parameters_identifier_list",
"parameters_identifier_list_breakup","param_identifier","@3","param_identifier_breakup",
"statement","printf_statement","printf_identifier_list","continue_statement",
"compound_statement","statment_list","expression_statment","conditional_statements",
"conditional_statements_breakup","iterative_statements","return_statement","return_statement_breakup",
"break_statement","string_initialization","array_initialization","array_int_declarations",
"array_float_declarations","array_int_declarations_breakup","array_float_declarations_breakup",
"expression","expression_breakup","simple_expression","simple_expression_breakup",
"and_expression","and_expression_breakup","unary_relation_expression","regular_expression",
"regular_expression_breakup","relational_operators","sum_expression","sum_operators",
"term","MULOP","factor","mutable","mutable_breakup","immutable","call","arguments",
"arguments_list","A","constant",""
};
#endif

static const short yyr1[] = {     0,
    72,    73,    74,    74,    75,    75,    75,    76,    76,    77,
    78,    78,    80,    79,    81,    81,    81,    81,    82,    82,
    83,    83,    83,    84,    84,    84,    85,    86,    86,    87,
    87,    88,    88,    88,    89,    89,    89,    90,    90,    90,
    91,    91,    91,    92,    92,    92,    92,    93,    93,    94,
    94,    94,    94,    94,    94,    94,    94,    94,    95,    95,
    95,    95,    96,    96,    96,    96,    97,    97,    98,    98,
   100,    99,   101,   101,   102,   103,   104,   105,   106,   106,
   107,   108,   109,   109,   111,   110,   112,   112,   113,   113,
   113,   113,   113,   113,   113,   113,   113,   114,   115,   115,
   115,   116,   117,   118,   118,   119,   119,   120,   121,   121,
   122,   122,   122,   123,   124,   124,   125,   116,   126,   127,
   127,   128,   129,   129,   130,   130,   131,   131,   132,   132,
   133,   133,   133,   133,   133,   133,   133,   133,   134,   135,
   135,   136,   137,   137,   138,   138,   139,   140,   140,   141,
   141,   141,   141,   141,   141,   142,   142,   143,   143,   144,
   144,   145,   145,   145,   146,   146,   147,   147,   147,   148,
   148,   149,   149,   149,   150,   151,   151,   152,   153,   153,
   154,   154,   154,   154
};

static const short yyr2[] = {     0,
     1,     2,     1,     0,     1,     1,     1,     3,     1,     2,
     2,     0,     0,     3,     1,     1,     2,     0,     4,     7,
     1,     1,     1,     5,     5,     4,     2,     3,     2,     1,
     1,     3,     2,     2,     1,     1,     0,     4,     4,     4,
     5,     3,     1,     5,     3,     1,     1,     3,     1,     1,
     1,     1,     1,     2,     2,     2,     2,     1,     1,     2,
     2,     0,     1,     2,     2,     0,     1,     0,     1,     0,
     0,     7,     2,     0,     3,     2,     3,     3,     1,     0,
     2,     2,     2,     0,     0,     3,     2,     0,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     6,     3,     3,
     0,     2,     3,     2,     0,     2,     1,     6,     2,     0,
     5,     8,     7,     2,     1,     2,     2,     2,     2,     4,
     4,     2,     2,     2,     2,     0,     2,     0,     2,     1,
     2,     2,     2,     2,     2,     2,     1,     1,     2,     3,
     0,     2,     3,     0,     2,     1,     2,     2,     0,     1,
     1,     1,     1,     1,     1,     3,     1,     1,     1,     3,
     1,     1,     1,     1,     1,     1,     1,     1,     2,     3,
     2,     3,     1,     1,     4,     1,     0,     2,     3,     0,
     1,     1,     1,     1
};

static const short yydefact[] = {     0,
    50,    51,    52,    53,    68,    70,    66,    62,     0,    58,
     1,     4,     5,     0,     7,     9,     6,    80,    67,    54,
    69,    55,    63,    68,    70,    57,    59,    68,    70,    56,
    71,     3,     2,    13,     0,    12,     0,    76,     0,    79,
    64,    65,    60,    61,    13,    75,     0,    77,    18,     8,
     0,    10,    85,    81,    84,     0,    74,     0,     0,    14,
    16,    15,    11,    88,     0,    82,     0,     0,     0,     0,
     0,     0,     0,     0,     0,   167,   181,   182,   183,   184,
     0,   107,   105,     0,    95,   168,     0,    78,    96,    97,
    90,    89,    91,    92,    93,    94,     0,   130,   141,   144,
   146,   149,   157,   161,   166,   165,   173,   174,    74,     0,
    17,     0,     0,    37,    27,     0,    86,    83,     0,     0,
   115,   114,     0,     0,     0,     0,   117,     0,   102,     0,
   177,   145,   166,   105,     0,     0,   106,     0,   139,     0,
   142,   154,   155,   151,   153,   150,   152,   158,   159,   147,
     0,     0,   162,   163,   164,     0,     0,     0,     0,     0,
     0,     0,   137,   138,     0,     0,   129,   169,    73,     0,
     0,    37,     0,     0,    33,    34,    36,    87,     0,   116,
     0,     0,     0,   101,    22,    21,    23,     0,   180,     0,
   176,   104,   103,   172,   141,   144,   148,   156,   160,   136,
   134,   135,   132,   133,   131,     0,   171,    72,     0,     0,
    32,    35,   119,     0,    31,    30,    26,     0,     0,     0,
     0,     0,     0,     0,    19,     0,   178,   175,   140,   143,
   170,    25,    24,   126,   128,     0,     0,    29,   110,   111,
     0,     0,   101,   101,     0,     0,   180,     0,   122,   124,
     0,   123,   120,   121,     0,    28,     0,   108,     0,     0,
    99,   100,    98,     0,   179,   125,   127,   128,     0,   109,
     0,   113,    20,    43,    49,    47,     0,     0,     0,     0,
   112,     0,     0,     0,    38,    39,    40,    48,    42,    45,
     0,     0,    43,     0,    41,    46,     0,    44,   126,     0,
     0,     0,     0
};

static const short yydefgoto[] = {   301,
    11,    33,    12,    85,    35,    52,    36,    49,    60,    86,
   188,    61,    62,   217,   218,   115,   175,   256,   278,   279,
   280,    87,    30,    26,    20,    22,    15,    47,   110,    16,
    17,    18,    38,    39,    40,    54,    66,    55,    64,   117,
   134,    89,   224,    90,    91,   135,    92,    93,   258,    94,
    95,   122,    96,   176,   177,   266,   267,   249,   250,    97,
   167,    98,   139,    99,   141,   100,   101,   150,   151,   102,
   152,   103,   156,   104,   105,   168,   106,   107,   190,   191,
   227,   108
};

static const short yypact[] = {   151,
-32768,-32768,-32768,-32768,     6,    20,    37,    40,     4,-32768,
-32768,   151,-32768,    39,-32768,-32768,-32768,   199,-32768,-32768,
-32768,-32768,-32768,     6,    20,-32768,-32768,     6,    20,-32768,
    47,-32768,-32768,   -37,    15,    34,    69,-32768,    35,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,    63,-32768,    26,-32768,
    47,-32768,-32768,-32768,    44,   116,   182,    27,   -10,-32768,
-32768,-32768,-32768,    49,   199,-32768,    77,   115,    -5,    98,
   108,   116,   119,   144,   137,    28,-32768,-32768,-32768,-32768,
    27,-32768,   116,    27,-32768,-32768,    47,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,   158,-32768,   185,   181,
-32768,   170,   114,-32768,   113,-32768,-32768,-32768,   182,   159,
-32768,   160,   162,    41,-32768,   163,-32768,-32768,    27,    47,
-32768,-32768,   167,    27,    27,   215,-32768,   207,-32768,   130,
    27,-32768,    12,   116,   165,   164,-32768,    27,-32768,    27,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
    13,    13,-32768,-32768,-32768,    13,    27,    27,    27,    27,
    27,    27,-32768,-32768,    27,   212,-32768,-32768,-32768,   173,
   172,    51,    18,   149,-32768,-32768,-32768,-32768,   168,-32768,
   169,   177,   174,   178,   176,-32768,-32768,   179,   180,   183,
-32768,-32768,-32768,-32768,   185,   181,   127,   114,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,   184,-32768,-32768,   149,   149,
-32768,-32768,-32768,    33,-32768,-32768,-32768,   186,   116,   116,
    27,    27,   223,   187,   189,    27,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,   191,   192,   190,   193,   208,   220,-32768,
   188,   194,   131,   178,   196,   130,   180,    33,-32768,-32768,
    60,-32768,-32768,-32768,   195,-32768,   116,-32768,    27,   197,
-32768,-32768,-32768,   200,-32768,-32768,-32768,   192,     5,-32768,
   198,-32768,-32768,-32768,   201,-32768,    33,   202,   203,   204,
-32768,   224,   205,   206,-32768,-32768,-32768,-32768,   211,   213,
    -1,     9,-32768,   239,-32768,-32768,    60,-32768,   214,   239,
   267,   269,-32768
};

static const short yypgoto[] = {-32768,
   264,-32768,-32768,     3,   -26,-32768,-32768,-32768,-32768,  -128,
    36,-32768,-32768,   -11,-32768,-32768,   107,-32768,    -8,   -12,
     2,    16,-32768,-32768,    87,    88,-32768,-32768,   209,-32768,
-32768,-32768,-32768,-32768,   216,-32768,-32768,-32768,-32768,-32768,
   -55,-32768,   -32,-32768,-32768,   152,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,   117,-32768,  -206,  -208,-32768,    50,   -58,
-32768,  -112,    92,   150,    94,   -72,-32768,-32768,-32768,   140,
-32768,   141,-32768,   136,   -77,-32768,-32768,-32768,-32768,-32768,
    48,-32768
};


#define	YYLAST		318


static const short yytable[] = {   111,
    88,   187,    13,   133,    46,   237,   179,   236,   132,    19,
   123,   181,   112,   113,    13,    14,   126,    76,    77,    78,
    79,    80,   293,    21,    63,   136,    31,    14,   274,   275,
   276,    48,   296,    37,   276,    76,    77,    78,    79,    80,
    23,   133,   213,    27,    24,    25,   133,    28,    29,    76,
    77,    78,    79,    80,    81,   114,   234,   121,   235,   109,
   133,    34,   133,    84,    58,   294,   182,   196,   284,    45,
   283,   277,   189,   133,   133,   297,   165,    50,   133,   173,
    37,    84,   166,   268,   214,   235,    81,   283,   284,   173,
    59,    53,   130,    46,   244,    84,   131,    51,   200,   201,
   202,   203,   204,   205,    56,   174,   206,    65,   241,   242,
    41,   109,    42,   116,    43,   210,    44,   187,    67,     1,
     2,     3,     4,     5,     6,     7,     8,    68,    69,    57,
    10,    70,    71,    72,    73,    74,    75,   120,    76,    77,
    78,    79,    80,   133,   133,   119,   157,   158,   159,   160,
   161,   162,   185,   186,     1,     2,     3,     4,     5,     6,
     7,     8,     9,   239,   240,    10,   124,   247,   153,   154,
   155,   215,   216,   163,   164,    81,   125,   165,    82,   148,
   149,   127,    83,   166,    84,     1,     2,     3,     4,     5,
     6,     7,     8,    68,   223,   130,    10,   232,   233,   129,
   271,   270,     1,     2,     3,     4,     5,     6,     7,     8,
   261,   262,   128,    10,   142,   143,   144,   145,   146,   147,
   137,   140,   148,   149,   138,   171,   170,   172,   178,   180,
   183,   184,   193,   194,   207,   208,   209,   219,   220,   221,
   130,   223,   222,   226,   225,   243,   255,   257,   275,   231,
   259,   238,   228,   246,   248,   251,   245,   253,   263,   272,
   254,   269,   299,   260,   282,   273,   302,   281,   303,   285,
   286,   287,   289,   290,   291,    32,   292,   300,   211,   298,
   118,   264,   295,   288,   252,   192,   229,   195,   212,   230,
   197,   199,   198,     0,   265,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,   169
};

static const short yycheck[] = {    58,
    56,   130,     0,    81,    31,   214,   119,   214,    81,     4,
    69,   124,    23,    24,    12,     0,    72,    23,    24,    25,
    26,    27,    24,     4,    51,    84,    23,    12,    24,    25,
    26,    69,    24,    18,    26,    23,    24,    25,    26,    27,
     4,   119,    25,     4,     8,     9,   124,     8,     9,    23,
    24,    25,    26,    27,    60,    66,    24,    63,    26,    57,
   138,    23,   140,    69,    39,    67,   125,   140,   277,    23,
   277,    67,   131,   151,   152,    67,    65,    63,   156,    39,
    65,    69,    71,    24,    67,    26,    60,   294,   297,    39,
    65,    23,    65,   120,   223,    69,    69,    64,   157,   158,
   159,   160,   161,   162,    70,    65,   165,    64,   221,   222,
    24,   109,    25,    65,    28,    65,    29,   246,     3,     4,
     5,     6,     7,     8,     9,    10,    11,    12,    13,    67,
    15,    16,    17,    18,    19,    20,    21,    23,    23,    24,
    25,    26,    27,   221,   222,    69,    34,    35,    36,    37,
    38,    39,    23,    24,     4,     5,     6,     7,     8,     9,
    10,    11,    12,   219,   220,    15,    69,   226,    55,    56,
    57,    23,    24,    61,    62,    60,    69,    65,    63,    53,
    54,    63,    67,    71,    69,     4,     5,     6,     7,     8,
     9,    10,    11,    12,    64,    65,    15,   209,   210,    63,
   259,   257,     4,     5,     6,     7,     8,     9,    10,    11,
   243,   244,    69,    15,    45,    46,    47,    48,    49,    50,
    63,    41,    53,    54,    40,    66,    68,    66,    66,    63,
    16,    25,    68,    70,    23,    63,    65,    70,    70,    63,
    65,    64,    69,    64,    66,    23,    39,    28,    25,    66,
    63,    66,    70,    65,    64,    64,    70,    68,    63,    63,
    68,    67,    24,    70,    64,    66,     0,    70,     0,    68,
    68,    68,    68,    68,    64,    12,    64,    64,   172,   292,
    65,   246,   291,   282,   235,   134,   195,   138,   172,   196,
   151,   156,   152,    -1,   247,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,   109
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 13:
#line 95 "prakhar.y"
{ ins(); ;
    break;}
case 71:
#line 200 "prakhar.y"
{ ins(); ;
    break;}
case 77:
#line 212 "prakhar.y"
{ ins();;
    break;}
case 85:
#line 231 "prakhar.y"
{ ins(); ;
    break;}
case 119:
#line 291 "prakhar.y"
{ insV(); ;
    break;}
case 181:
#line 399 "prakhar.y"
{ insV(); ;
    break;}
case 182:
#line 400 "prakhar.y"
{ insV(); ;
    break;}
case 183:
#line 401 "prakhar.y"
{ insV(); ;
    break;}
case 184:
#line 402 "prakhar.y"
{ insV(); ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 404 "prakhar.y"


extern FILE *yyin;
extern int yylineno;
extern char *yytext;
void insertSTtype(char *,char *);
void insertSTvalue(char *, char *);
void incertCT(char *, char *);
void printST();
void printCT();

int main(int argc , char **argv)
{
	yyin = fopen(argv[1], "r");
	yyparse();

	if(flag == 0)
	{
		printf(ANSI_COLOR_GREEN "Status: Parsing Complete - Valid" ANSI_COLOR_RESET "\n");
		printf("%30s" ANSI_COLOR_CYAN "SYMBOL TABLE" ANSI_COLOR_RESET "\n", " ");
		printf("%30s %s\n", " ", "------------");
		printST();

		printf("\n\n%30s" ANSI_COLOR_CYAN "CONSTANT TABLE" ANSI_COLOR_RESET "\n", " ");
		printf("%30s %s\n", " ", "--------------");
		printCT();
	}
}

void yyerror(char *s)
{
	printf("%d %s %s\n", yylineno, s, yytext);
	flag=1;
	printf(ANSI_COLOR_RED "Status: Parsing Failed - Invalid\n" ANSI_COLOR_RESET);
}

void ins()
{
	insertSTtype(curid,curtype);
}

void insV()
{
	insertSTvalue(curid,curval);
}

int yywrap()
{
	return 1;
}